Repository aptos-labs/aptos-core, pull requests merged in 2022-05, with the labels that each got.

#802 [aptos-cli] Add assume-no prompt option
  crates/aptos/src/common/types.rs
  crates/aptos/src/common/utils.rs
  crates/aptos/src/move_tool/mod.rs
  crates/aptos/src/op/key.rs
Labels: tooling

#821 Changing expiration timestamp to 10 seconds from now
  ecosystem/typescript/sdk/src/aptos_client.ts
Labels: bug

#881 [aptos-cli] Add stake amounts to genesis tooling
  aptos-move/vm-genesis/src/lib.rs
  config/management/genesis/src/builder.rs
  crates/aptos/src/genesis/config.rs
  crates/aptos/src/genesis/keys.rs
Labels: bors-high-priority, tooling

#880 [aptos-cli] Add account address to genesis information
  crates/aptos/src/genesis/config.rs
  crates/aptos/src/genesis/keys.rs
  crates/aptos/src/genesis/mod.rs
Labels: bors-high-priority, tooling

#610 fix typos
  config/management/operational/src/keys.rs
  crates/aptos-crypto/src/x25519.rs
  crates/aptos/src/op/key.rs
Labels: bors-squash

#931 [CP] Add support for persona KYC
  ecosystem/platform/server/.env.example
  ecosystem/platform/server/Dockerfile
  ecosystem/platform/server/Gemfile
  ecosystem/platform/server/app/admin/it1_profiles.rb
  ecosystem/platform/server/app/admin/users.rb
  ecosystem/platform/server/app/controllers/application_controller.rb
  ecosystem/platform/server/app/controllers/health_controller.rb
  ecosystem/platform/server/app/controllers/onboarding_controller.rb
  ecosystem/platform/server/app/controllers/welcome_controller.rb
  ecosystem/platform/server/app/helpers/persona_helper.rb
  ecosystem/platform/server/app/jobs/kyc_complete_job.rb
  ecosystem/platform/server/app/models/persona_kyc.rb
  ecosystem/platform/server/app/models/user.rb
  ecosystem/platform/server/app/views/welcome/it1.html.erb
  ecosystem/platform/server/config/initializers/crash_if_no_db.rb
  ecosystem/platform/server/config/initializers/inflections.rb
  ecosystem/platform/server/config/routes.rb
  ecosystem/platform/server/db/migrate/20220511232114_add_guid_to_user.rb
  ecosystem/platform/server/db/migrate/20220512031021_add_kyc_fields_to_users.rb
  ecosystem/platform/server/db/schema.rb
  ecosystem/platform/server/spec/models/persona_kyc_spec.rb
Labels: bors-high-priority

#926 [aptos-cli] Output Validator and VFN identity files for genesis
  config/src/config/mod.rs
  config/src/config/network_config.rs
  config/src/keys.rs
  consensus/safety-rules/src/safety_rules_manager.rs
  crates/aptos/Cargo.toml
  crates/aptos/src/genesis/config.rs
  crates/aptos/src/genesis/keys.rs
Labels: bors-high-priority, tooling

#951 [doc] testnet node liveness criteria
  developer-docs-site/docs/reference/node-liveness-criteria.md
Labels: bors-high-priority

#984 [aptos-cli] Migrate config.yml to config.yaml
  crates/aptos/src/common/init.rs
  crates/aptos/src/common/types.rs
Labels: bors-high-priority, tooling

#1053 [aptos-cli] Ensure all private information is not open to all users
  crates/aptos/src/common/types.rs
  crates/aptos/src/common/utils.rs
  crates/aptos/src/genesis/keys.rs
Labels: tooling

#1061 [aptos-cli] Add fund command to add coins to an existing command
  crates/aptos/src/account/create.rs
  crates/aptos/src/account/fund.rs
  crates/aptos/src/account/mod.rs
  crates/aptos/src/common/init.rs
  crates/aptos/src/common/types.rs
  crates/aptos/src/common/utils.rs
Labels: tooling

#1107 [aptos-cli] Add build size optimizations
  Cargo.toml
  scripts/cli/build_cli_release.sh
Labels: tooling

#1077 [CICD] Build DockerImages on Github Actions with self-hosted runners
  .circleci/config.yml
  .dockerignore
  .github/workflows/build-images.yaml
  docker/docker-bake-rust-all.hcl
  ecosystem/platform/server/docker-bake.hcl
Labels: CICD:build-images

#1176 CICD: fix github action job to trigger on protected branches without the CICD label
  .github/workflows/build-images.yaml
Labels: CICD:build-images
