Repository aptos-labs/aptos-core, pull requests merged in 2022-10, with the labels that each got.

#4691 markuze/haproxy v3
  terraform/helm/aptos-node/files/haproxy.cfg
  terraform/helm/aptos-node/values.yaml
Labels: CICD:run-e2e-tests

#4344 Update to `debian:bullseye-20220912` in our Rust images Dockerfile
  docker/docker-bake-rust-all.sh
  docker/rust-all.Dockerfile
Labels: CICD:build-images, CICD:run-e2e-tests

#4669 [cli] Add typeargs for script support and move example
  aptos-move/move-examples/split_transfer/Move.toml
  aptos-move/move-examples/split_transfer/sources/split_transfer.move
  crates/aptos/src/move_tool/mod.rs
Labels: CICD:run-e2e-tests

#4701 [serde] apply stricter recursion limit on user input
  api/src/transactions.rs
  api/types/src/lib.rs
  api/types/src/move_types.rs
  network/src/protocols/wire/handshake/v1/mod.rs
Labels: CICD:run-e2e-tests

#4718 [Genesis] Move previously hardcoded vesting configurations into genesis configurations
  aptos-move/framework/aptos-framework/sources/genesis.move
  aptos-move/vm-genesis/src/lib.rs
  crates/aptos-genesis/src/builder.rs
  crates/aptos-genesis/src/config.rs
  crates/aptos-genesis/src/lib.rs
  crates/aptos-genesis/src/mainnet.rs
  crates/aptos/src/genesis/mod.rs
Labels: CICD:run-e2e-tests

#4708 [Compression] Enforce size limit before compression
  crates/aptos-compression/src/lib.rs
Labels: CICD:run-e2e-tests

#4716 Add auth token to TS tests / examples to bypass devnet tap ratelimits
  .github/workflows/check-sdk-examples.yaml
  .github/workflows/sdk-release.yaml
Labels: CICD:run-e2e-tests

#4702 [Indexer] Fix token indexing failure when collection table handle is missing
  config/src/config/indexer_config.rs
  config/src/config/mod.rs
  crates/indexer/migrations/2022-10-02-011015_add_table_handle_to_collection/down.sql
  crates/indexer/migrations/2022-10-02-011015_add_table_handle_to_collection/up.sql
  crates/indexer/src/indexer/tailer.rs
  crates/indexer/src/models/token_models/collection_datas.rs
  crates/indexer/src/models/token_models/tokens.rs
  crates/indexer/src/processors/token_processor.rs
  crates/indexer/src/runtime.rs
  crates/indexer/src/schema.rs
Labels: CICD:build-images

#4709 [Aptos Framework] Remove resource accounts' default auth key
  aptos-move/framework/aptos-framework/sources/account.move
Labels: CICD:run-e2e-tests

#4727 [docs] Add haproxy files to docker run commands
  developer-docs-site/docs/nodes/validator-node/operator/running-validator-node/using-docker.md
  docker/compose/aptos-node/README.md
Labels: Do not merge

#4685 [api] reduce submit_batch size to planned 10 txn per single request
  config/src/config/api_config.rs
  crates/transaction-emitter-lib/src/emitter/account_minter.rs
  crates/transaction-emitter-lib/src/emitter/mod.rs
Labels: CICD:run-e2e-tests

#4751 [aptos-vm] further restrictions on governance transaction sizes
  aptos-move/aptos-vm/src/aptos_vm_impl.rs
  aptos-move/aptos-vm/src/transaction_metadata.rs
  aptos-move/e2e-move-tests/src/harness.rs
  aptos-move/e2e-move-tests/src/tests/governance_updates.rs
  aptos-move/e2e-move-tests/src/tests/mod.rs
  aptos-move/e2e-tests/src/executor.rs
Labels: CICD:run-e2e-tests

#4694 [mempool] check hash for rejected transactions
  consensus/consensus-types/src/common.rs
  consensus/src/txn_notifier.rs
  mempool/src/core_mempool/mempool.rs
  mempool/src/core_mempool/transaction_store.rs
  mempool/src/shared_mempool/coordinator.rs
  mempool/src/shared_mempool/tasks.rs
  mempool/src/shared_mempool/types.rs
  mempool/src/tests/core_mempool_test.rs
  mempool/src/tests/mocks.rs
  mempool/src/tests/shared_mempool_test.rs
  mempool/src/tests/test_framework.rs
Labels: CICD:run-e2e-tests

#4715 [telemetry] configure mainnet telemetry service URL
  crates/aptos-telemetry/src/constants.rs
  crates/aptos-telemetry/src/service.rs
Labels: CICD:run-e2e-tests

#4740 [move] fix ambiguity in SignerCapabilityOfferProofChallenge struct
  Cargo.lock
  aptos-move/e2e-move-tests/Cargo.toml
  aptos-move/e2e-move-tests/src/tests/mod.rs
  aptos-move/e2e-move-tests/src/tests/offer_signer_capability.rs
  aptos-move/framework/aptos-framework/sources/account.move
  aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
Labels: CICD:run-e2e-tests

#4771 [Parallel execution] metrics: add counters
  Cargo.lock
  aptos-move/parallel-executor/Cargo.toml
  aptos-move/parallel-executor/src/counters.rs
  aptos-move/parallel-executor/src/executor.rs
  aptos-move/parallel-executor/src/lib.rs
Labels: CICD:run-e2e-tests

#4728 [mempool] bucketed broadcast
  api/src/tests/transactions_test.rs
  config/src/config/mempool_config.rs
  mempool/src/core_mempool/index.rs
  mempool/src/core_mempool/mempool.rs
  mempool/src/core_mempool/transaction_store.rs
  mempool/src/counters.rs
  mempool/src/logging.rs
  mempool/src/shared_mempool/network.rs
  mempool/src/shared_mempool/tasks.rs
  mempool/src/shared_mempool/types.rs
  mempool/src/tests/common.rs
  mempool/src/tests/core_mempool_test.rs
  mempool/src/tests/mocks.rs
  mempool/src/tests/shared_mempool_test.rs
  mempool/src/tests/test_framework.rs
Labels: CICD:run-e2e-tests

#4757 [gas] implement memory quota
  Cargo.lock
  api/Cargo.toml
  api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json
  api/goldens/aptos_api__tests__transactions_test__test_get_transactions_returns_last_page_when_start_version_is_not_specified.json
  api/src/tests/transaction_vector_test.rs
  api/types/Cargo.toml
  api/types/src/move_types.rs
  aptos-move/aptos-aggregator/Cargo.toml
  aptos-move/aptos-gas/Cargo.toml
  aptos-move/aptos-gas/src/gas_meter.rs
  aptos-move/aptos-gas/src/instr.rs
  aptos-move/aptos-gas/src/misc.rs
  aptos-move/aptos-gas/src/transaction.rs
  aptos-move/aptos-module-verifier/Cargo.toml
  aptos-move/aptos-sdk-builder/Cargo.toml
  aptos-move/aptos-sdk-builder/src/common.rs
  aptos-move/aptos-sdk-builder/src/golang.rs
  aptos-move/aptos-sdk-builder/src/rust.rs
  aptos-move/aptos-vm/Cargo.toml
  aptos-move/aptos-vm/src/aptos_vm_impl.rs
  aptos-move/aptos-vm/src/move_vm_ext/vm.rs
  aptos-move/aptos-vm/src/natives.rs
  aptos-move/e2e-move-tests/src/tests/memory_quota.data/clone_vec/Move.toml
  aptos-move/e2e-move-tests/src/tests/memory_quota.data/clone_vec/sources/test.move
  aptos-move/e2e-move-tests/src/tests/memory_quota.data/vec_push_u128/Move.toml
  aptos-move/e2e-move-tests/src/tests/memory_quota.data/vec_push_u128/sources/test.move
  aptos-move/e2e-move-tests/src/tests/memory_quota.rs
  aptos-move/e2e-move-tests/src/tests/mod.rs
  aptos-move/e2e-move-tests/src/tests/string_args.rs
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__create_account__create_account.exp
  aptos-move/e2e-tests/src/executor.rs
  aptos-move/e2e-testsuite/src/tests/scripts.rs
  aptos-move/e2e-testsuite/src/tests/verify_txn.rs
  aptos-move/framework/Cargo.toml
  aptos-move/framework/cached-packages/Cargo.toml
  aptos-move/framework/tests/move_unit_test.rs
  aptos-move/gas-algebra-ext/Cargo.toml
  aptos-move/move-deps/Cargo.toml
  aptos-move/move-examples/tests/move_unit_tests.rs
  aptos-move/package-builder/Cargo.toml
  aptos-move/vm-genesis/Cargo.toml
  aptos-move/vm-genesis/src/lib.rs
  aptos-move/writeset-transaction-generator/src/writeset_builder.rs
  consensus/src/liveness/leader_reputation_test.rs
  crates/aptos-rest-client/Cargo.toml
  crates/aptos-rosetta/src/common.rs
  crates/aptos-rosetta/src/construction.rs
  crates/aptos/src/move_tool/aptos_debug_natives.rs
  developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md
  ecosystem/sf-indexer/firehose-stream/Cargo.toml
  execution/executor/Cargo.toml
  execution/executor/tests/db_bootstrapper_test.rs
  storage/aptosdb/Cargo.toml
  storage/aptosdb/src/event_store/test.rs
  storage/indexer/Cargo.toml
  storage/indexer/src/lib.rs
  storage/storage-interface/Cargo.toml
  types/Cargo.toml
  types/src/contract_event.rs
  types/src/utility_coin.rs
Labels: CICD:run-e2e-tests

#4624 [indexer] add ANS lookup table
  config/src/config/indexer_config.rs
  config/src/config/mod.rs
  crates/indexer/migrations/2022-10-02-011020_ans_lookup_table/down.sql
  crates/indexer/migrations/2022-10-02-011020_ans_lookup_table/up.sql
  crates/indexer/src/models/token_models/ans_lookup.rs
  crates/indexer/src/models/token_models/mod.rs
  crates/indexer/src/processors/token_processor.rs
  crates/indexer/src/runtime.rs
  crates/indexer/src/schema.rs
Labels: CICD:build-images

#4787 [move] fix resource account address derivation
  aptos-move/e2e-move-tests/src/tests/code_publishing.rs
  aptos-move/framework/aptos-framework/sources/account.move
  types/src/account_address.rs
  types/src/transaction/authenticator.rs
Labels: CICD:build-images

#4772 [gha] Add token to checkout repo for forge
  .github/workflows/docker-build-test.yaml
Labels: CICD:run-e2e-tests

#4803 [gas] do not release memory for table natives
  aptos-move/aptos-gas/src/gas_meter.rs
  aptos-move/e2e-move-tests/src/tests/memory_quota.data/table_and_vec/Move.toml
  aptos-move/e2e-move-tests/src/tests/memory_quota.data/table_and_vec/sources/test.move
  aptos-move/e2e-move-tests/src/tests/memory_quota.rs
Labels: CICD:run-e2e-tests

#4705 Add Aptos Names
  CODEOWNERS
  aptos-move/e2e-move-tests/src/tests/framework_compatibility.rs
  aptos-move/e2e-move-tests/src/tests/mod.rs
  aptos-move/e2e-move-tests/src/tests/names.rs
  aptos-move/framework/aptos-names/Move.toml
  aptos-move/framework/aptos-names/sources/config.move
  aptos-move/framework/aptos-names/sources/domain_e2e_tests.move
  aptos-move/framework/aptos-names/sources/domains.move
  aptos-move/framework/aptos-names/sources/price_model.move
  aptos-move/framework/aptos-names/sources/readme.md
  aptos-move/framework/aptos-names/sources/subdomain_e2e_tests.move
  aptos-move/framework/aptos-names/sources/test_helper.move
  aptos-move/framework/aptos-names/sources/test_utils.move
  aptos-move/framework/aptos-names/sources/time_helper.move
  aptos-move/framework/aptos-names/sources/token_helper.move
  aptos-move/framework/aptos-names/sources/utf8_utils.move
  aptos-move/framework/cached-packages/build.rs
  aptos-move/framework/cached-packages/src/aptos_names_sdk_builder.rs
  aptos-move/framework/cached-packages/src/lib.rs
  aptos-move/framework/src/aptos.rs
  aptos-move/framework/src/release_bundle.rs
  aptos-move/framework/tests/move_prover_tests.rs
Labels: CICD:run-e2e-tests

#4809 feature gate change set size checks
  Cargo.lock
  aptos-move/aptos-aggregator/src/transaction.rs
  aptos-move/aptos-gas/src/gas_meter.rs
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/aptos_vm_impl.rs
  aptos-move/aptos-vm/src/move_vm_ext/session.rs
  aptos-move/e2e-tests/src/executor.rs
  aptos-move/vm-genesis/src/lib.rs
  aptos-move/writeset-transaction-generator/src/writeset_builder.rs
  config/src/config/execution_config.rs
  execution/executor/Cargo.toml
  execution/executor/src/mock_vm/mod.rs
  execution/executor/tests/db_bootstrapper_test.rs
  state-sync/inter-component/mempool-notifications/src/lib.rs
  types/src/proptest_types.rs
  types/src/transaction/change_set.rs
Labels: CICD:run-e2e-tests

#4579 [Indexer] add coin indexing
  crates/indexer/migrations/2022-10-04-073529_add_coin_tables/down.sql
  crates/indexer/migrations/2022-10-04-073529_add_coin_tables/up.sql
  crates/indexer/src/indexer/tailer.rs
  crates/indexer/src/models/block_metadata_transactions.rs
  crates/indexer/src/models/coin_models/coin_activities.rs
  crates/indexer/src/models/coin_models/coin_balances.rs
  crates/indexer/src/models/coin_models/coin_infos.rs
  crates/indexer/src/models/coin_models/coin_utils.rs
  crates/indexer/src/models/coin_models/mod.rs
  crates/indexer/src/models/events.rs
  crates/indexer/src/models/mod.rs
  crates/indexer/src/models/move_modules.rs
  crates/indexer/src/models/move_resources.rs
  crates/indexer/src/models/move_tables.rs
  crates/indexer/src/models/signatures.rs
  crates/indexer/src/models/token_models/ans_lookup.rs
  crates/indexer/src/models/token_models/collection_datas.rs
  crates/indexer/src/models/token_models/token_activities.rs
  crates/indexer/src/models/token_models/token_claims.rs
  crates/indexer/src/models/token_models/token_datas.rs
  crates/indexer/src/models/token_models/token_ownerships.rs
  crates/indexer/src/models/token_models/token_utils.rs
  crates/indexer/src/models/token_models/tokens.rs
  crates/indexer/src/models/transactions.rs
  crates/indexer/src/models/user_transactions.rs
  crates/indexer/src/models/write_set_changes.rs
  crates/indexer/src/processors/coin_processor.rs
  crates/indexer/src/processors/default_processor.rs
  crates/indexer/src/processors/mod.rs
  crates/indexer/src/processors/token_processor.rs
  crates/indexer/src/runtime.rs
  crates/indexer/src/schema.rs
  testsuite/smoke-test/src/indexer.rs
Labels: CICD:build-images

#4821 [framework] enable all outstanding feature flags in genesis
  aptos-move/e2e-move-tests/src/harness.rs
  aptos-move/e2e-move-tests/src/tests/code_publishing.rs
  aptos-move/vm-genesis/src/lib.rs
Labels: CICD:run-e2e-tests

#4767 [bcs] Update bcs for https://github.com/aptos-labs/bcs/pull/2
  Cargo.lock
  api/Cargo.toml
  api/types/Cargo.toml
  aptos-move/aptos-aggregator/Cargo.toml
  aptos-move/aptos-gas/Cargo.toml
  aptos-move/aptos-sdk-builder/Cargo.toml
  aptos-move/aptos-sdk-builder/tests/generation.rs
  aptos-move/aptos-transactional-test-harness/Cargo.toml
  aptos-move/aptos-vm/Cargo.toml
  aptos-move/e2e-move-tests/Cargo.toml
  aptos-move/e2e-tests/Cargo.toml
  aptos-move/e2e-testsuite/Cargo.toml
  aptos-move/framework/Cargo.toml
  aptos-move/framework/cached-packages/Cargo.toml
  aptos-move/mvhashmap/Cargo.toml
  aptos-move/parallel-executor/Cargo.toml
  aptos-move/vm-genesis/Cargo.toml
  aptos-move/writeset-transaction-generator/Cargo.toml
  aptos-node/Cargo.toml
  config/Cargo.toml
  consensus/Cargo.toml
  consensus/consensus-types/Cargo.toml
  crates/aptos-bitvec/Cargo.toml
  crates/aptos-compression/Cargo.toml
  crates/aptos-crypto/Cargo.toml
  crates/aptos-faucet/Cargo.toml
  crates/aptos-genesis/Cargo.toml
  crates/aptos-rest-client/Cargo.toml
  crates/aptos-rosetta/Cargo.toml
  crates/aptos-telemetry-service/Cargo.toml
  crates/aptos-warp-webserver/Cargo.toml
  crates/aptos/Cargo.toml
  execution/db-bootstrapper/Cargo.toml
  execution/executor-types/Cargo.toml
  execution/executor/Cargo.toml
  mempool/Cargo.toml
  network/Cargo.toml
  network/builder/Cargo.toml
  network/discovery/Cargo.toml
  network/peer-monitoring-service/server/Cargo.toml
  sdk/Cargo.toml
  secure/storage/Cargo.toml
  state-sync/aptos-data-client/Cargo.toml
  state-sync/inter-component/event-notifications/Cargo.toml
  state-sync/state-sync-v2/state-sync-driver/Cargo.toml
  state-sync/storage-service/server/Cargo.toml
  state-sync/storage-service/types/Cargo.toml
  storage/aptosdb/Cargo.toml
  storage/backup/backup-cli/Cargo.toml
  storage/backup/backup-service/Cargo.toml
  storage/indexer/Cargo.toml
  storage/jellyfish-merkle/Cargo.toml
  storage/state-view/Cargo.toml
  storage/storage-interface/Cargo.toml
  testsuite/aptos-fuzzer/Cargo.toml
  testsuite/generate-format/Cargo.toml
  testsuite/smoke-test/Cargo.toml
  types/Cargo.toml
Labels: CICD:run-e2e-tests

#4838 [Indexer] Add views and indexer status table
  crates/indexer/migrations/2022-10-06-193846_add_indexer_status/down.sql
  crates/indexer/migrations/2022-10-06-193846_add_indexer_status/up.sql
  crates/indexer/src/schema.rs
Labels: CICD:build-images

#4857 [move] Update Move reference for bytecode verifier update.
  api/Cargo.toml
  api/types/Cargo.toml
  aptos-move/aptos-aggregator/Cargo.toml
  aptos-move/aptos-gas/Cargo.toml
  aptos-move/aptos-module-verifier/Cargo.toml
  aptos-move/aptos-sdk-builder/Cargo.toml
  aptos-move/aptos-vm/Cargo.toml
  aptos-move/framework/Cargo.toml
  aptos-move/framework/cached-packages/Cargo.toml
  aptos-move/gas-algebra-ext/Cargo.toml
  aptos-move/move-deps/Cargo.toml
  aptos-move/package-builder/Cargo.toml
  aptos-move/vm-genesis/Cargo.toml
  crates/aptos-rest-client/Cargo.toml
  ecosystem/sf-indexer/firehose-stream/Cargo.toml
  execution/executor/Cargo.toml
  storage/aptosdb/Cargo.toml
  storage/indexer/Cargo.toml
  storage/storage-interface/Cargo.toml
  types/Cargo.toml
Labels: CICD:run-e2e-tests

#4920 [e2e tests] limit concurrency level for faster execution
  aptos-move/e2e-tests/src/executor.rs
Labels: CICD:run-e2e-tests

#4913 [Move] Update commit
  Cargo.lock
  api/Cargo.toml
  api/types/Cargo.toml
  aptos-move/aptos-aggregator/Cargo.toml
  aptos-move/aptos-gas/Cargo.toml
  aptos-move/aptos-module-verifier/Cargo.toml
  aptos-move/aptos-sdk-builder/Cargo.toml
  aptos-move/aptos-vm/Cargo.toml
  aptos-move/framework/Cargo.toml
  aptos-move/framework/cached-packages/Cargo.toml
  aptos-move/gas-algebra-ext/Cargo.toml
  aptos-move/move-deps/Cargo.toml
  aptos-move/package-builder/Cargo.toml
  aptos-move/vm-genesis/Cargo.toml
  crates/aptos-rest-client/Cargo.toml
  ecosystem/sf-indexer/firehose-stream/Cargo.toml
  execution/executor/Cargo.toml
  storage/aptosdb/Cargo.toml
  storage/indexer/Cargo.toml
  storage/storage-interface/Cargo.toml
  types/Cargo.toml
Labels: CICD:run-e2e-tests

#4784 [consensus] Track counters about executed transaction details
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-node/src/lib.rs
  config/src/config/execution_config.rs
  execution/executor/src/components/chunk_output.rs
  execution/executor/src/metrics.rs
Labels: CICD:run-e2e-tests

#4959 [mempool] default_failovers 0 everywhere
  docker/compose/aptos-node/fullnode.yaml
Labels: CICD:run-e2e-tests

#4964 [mempool] update the default broadcast bucket config
  config/src/config/mempool_config.rs
  mempool/src/tests/shared_mempool_test.rs
Labels: CICD:run-e2e-tests

#4649 Adding configurabele TCP buffers and minor hafixes
  config/src/config/network_config.rs
  crates/aptos-network-checker/src/check_endpoint.rs
  network/builder/src/builder.rs
  network/netcore/src/transport/tcp.rs
  network/src/peer_manager/builder.rs
  network/src/transport/mod.rs
Labels: CICD:run-e2e-tests

#4907 [Indexer] Add aptos coin supply
  api/types/src/convert.rs
  api/types/src/transaction.rs
  crates/aptos-faucet/src/main.rs
  crates/indexer/README.md
  crates/indexer/migrations/2022-10-07-231825_add_coin_supply/down.sql
  crates/indexer/migrations/2022-10-07-231825_add_coin_supply/up.sql
  crates/indexer/src/indexer/fetcher.rs
  crates/indexer/src/indexer/tailer.rs
  crates/indexer/src/models/coin_models/coin_activities.rs
  crates/indexer/src/models/coin_models/coin_infos.rs
  crates/indexer/src/models/coin_models/coin_supply.rs
  crates/indexer/src/models/coin_models/coin_utils.rs
  crates/indexer/src/models/coin_models/mod.rs
  crates/indexer/src/models/token_models/token_datas.rs
  crates/indexer/src/models/transactions.rs
  crates/indexer/src/models/user_transactions.rs
  crates/indexer/src/processors/coin_processor.rs
  crates/indexer/src/processors/default_processor.rs
  crates/indexer/src/processors/token_processor.rs
  crates/indexer/src/runtime.rs
  crates/indexer/src/schema.rs
Labels: CICD:build-images

#4978 [move] Update commit hash
  Cargo.lock
  api/Cargo.toml
  api/goldens/aptos_api__tests__transactions_test__test_gas_estimation.json
  api/types/Cargo.toml
  aptos-move/aptos-aggregator/Cargo.toml
  aptos-move/aptos-gas/Cargo.toml
  aptos-move/aptos-module-verifier/Cargo.toml
  aptos-move/aptos-sdk-builder/Cargo.toml
  aptos-move/aptos-vm/Cargo.toml
  aptos-move/framework/Cargo.toml
  aptos-move/framework/cached-packages/Cargo.toml
  aptos-move/gas-algebra-ext/Cargo.toml
  aptos-move/move-deps/Cargo.toml
  aptos-move/package-builder/Cargo.toml
  aptos-move/vm-genesis/Cargo.toml
  crates/aptos-rest-client/Cargo.toml
  ecosystem/sf-indexer/firehose-stream/Cargo.toml
  execution/executor/Cargo.toml
  storage/aptosdb/Cargo.toml
  storage/indexer/Cargo.toml
  storage/storage-interface/Cargo.toml
  types/Cargo.toml
Labels: CICD:run-e2e-tests

#4989 fix and improve docker image release job
  .github/workflows/copy-images-to-dockerhub.yaml
  docker/README.md
  docker/release-images.mjs
  docker/release-images.sh
  package.json
  pnpm-lock.yaml
Labels: CICD:build-images

#4999 [networking] set_reuseaddr before bind, and a logging improvement
  network/netcore/src/transport/tcp.rs
  network/src/peer_manager/transport.rs
Labels: CICD:run-e2e-tests

#5015 [Indexer] fix ans bug
  crates/indexer/src/models/token_models/ans_lookup.rs
  ecosystem/sf-indexer/aptos-sf-indexer/src/models/indexer_states.rs
Labels: CICD:build-images

#5028 remove bad logs
  crates/indexer/src/models/transactions.rs
Labels: CICD:build-images

#4997 [consensus] just fix health counters
  consensus/src/liveness/leader_reputation.rs
Labels: CICD:run-e2e-tests

#5071 [Indexer] Improve processor tracking and error handling
  crates/indexer/migrations/2022-08-08-043603_core_tables/up.sql
  crates/indexer/migrations/2022-10-15-185912_improve_processor_recovery/down.sql
  crates/indexer/migrations/2022-10-15-185912_improve_processor_recovery/up.sql
  crates/indexer/src/indexer/tailer.rs
  crates/indexer/src/models/ledger_info.rs
  crates/indexer/src/models/mod.rs
  crates/indexer/src/models/processor_status.rs
  crates/indexer/src/models/processor_statuses.rs
  crates/indexer/src/runtime.rs
  crates/indexer/src/schema.rs
Labels: CICD:build-images

#5062 [Indexer] Limit token ownership to only tokenstore
  crates/indexer/migrations/2022-08-08-043603_core_tables/up.sql
  crates/indexer/migrations/2022-10-15-185912_improve_processor_recovery/down.sql
  crates/indexer/migrations/2022-10-15-185912_improve_processor_recovery/up.sql
  crates/indexer/src/indexer/tailer.rs
  crates/indexer/src/models/ledger_info.rs
  crates/indexer/src/models/mod.rs
  crates/indexer/src/models/processor_status.rs
  crates/indexer/src/models/processor_statuses.rs
  crates/indexer/src/models/token_models/collection_datas.rs
  crates/indexer/src/models/token_models/token_ownerships.rs
  crates/indexer/src/models/token_models/tokens.rs
  crates/indexer/src/processors/token_processor.rs
  crates/indexer/src/runtime.rs
  crates/indexer/src/schema.rs
Labels: CICD:build-images

#5076 [move] Update commit hash (cherry-pick #5074)
  Cargo.lock
  api/Cargo.toml
  api/types/Cargo.toml
  aptos-move/aptos-aggregator/Cargo.toml
  aptos-move/aptos-gas/Cargo.toml
  aptos-move/aptos-module-verifier/Cargo.toml
  aptos-move/aptos-sdk-builder/Cargo.toml
  aptos-move/aptos-vm/Cargo.toml
  aptos-move/framework/Cargo.toml
  aptos-move/framework/cached-packages/Cargo.toml
  aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
  aptos-move/framework/cached-packages/src/aptos_token_sdk_builder.rs
  aptos-move/gas-algebra-ext/Cargo.toml
  aptos-move/move-deps/Cargo.toml
  aptos-move/package-builder/Cargo.toml
  aptos-move/vm-genesis/Cargo.toml
  crates/aptos-rest-client/Cargo.toml
  ecosystem/sf-indexer/firehose-stream/Cargo.toml
  execution/executor/Cargo.toml
  storage/aptosdb/Cargo.toml
  storage/indexer/Cargo.toml
  storage/storage-interface/Cargo.toml
  types/Cargo.toml
Labels: CICD:run-e2e-tests

#5057 [mempool] add bucket to latency stats
  mempool/src/core_mempool/mempool.rs
  mempool/src/core_mempool/transaction_store.rs
  mempool/src/counters.rs
  mempool/src/tests/core_mempool_test.rs
Labels: CICD:run-e2e-tests

#4953 [mempool] smoke test to confirm failover on default_failovers=0
  testsuite/forge/src/backend/local/mod.rs
  testsuite/smoke-test/src/full_nodes.rs
  testsuite/smoke-test/src/smoke_test_environment.rs
Labels: CICD:run-e2e-tests

#5140 [gha] update base image in compat test
  .github/workflows/docker-build-test.yaml
Labels: CICD:run-e2e-tests

#5138 [Token] update the standard doc
  developer-docs-site/docs/concepts/coin-and-token/aptos-token.md
Labels: CICD:run-e2e-tests

#5143 [Indexer] Refactor fetcher to be able to skip over bad txns easily
  crates/indexer/src/indexer/fetcher.rs
Labels: CICD:build-images

#5161 Fix wait for error message
  crates/aptos-rest-client/src/lib.rs
Labels: CICD:run-e2e-tests

#5176 [State Sync] Small tweaks to configs.
  config/src/config/state_sync_config.rs
Labels: CICD:run-e2e-tests

#5170 standardize address and table handle
  crates/indexer/src/models/block_metadata_transactions.rs
  crates/indexer/src/models/coin_models/coin_activities.rs
  crates/indexer/src/models/coin_models/coin_balances.rs
  crates/indexer/src/models/events.rs
  crates/indexer/src/models/move_modules.rs
  crates/indexer/src/models/move_resources.rs
  crates/indexer/src/models/move_tables.rs
  crates/indexer/src/models/signatures.rs
  crates/indexer/src/models/token_models/ans_lookup.rs
  crates/indexer/src/models/token_models/collection_datas.rs
  crates/indexer/src/models/token_models/token_activities.rs
  crates/indexer/src/models/token_models/token_claims.rs
  crates/indexer/src/models/token_models/token_datas.rs
  crates/indexer/src/models/token_models/token_ownerships.rs
  crates/indexer/src/models/token_models/tokens.rs
  crates/indexer/src/models/user_transactions.rs
  crates/indexer/src/models/write_set_changes.rs
  crates/indexer/src/util.rs
Labels: CICD:build-images

#5208 [move-prover] Refactor prover integration
  Cargo.lock
  Cargo.toml
  aptos-move/framework/Cargo.toml
  aptos-move/framework/src/built_package.rs
  aptos-move/framework/src/lib.rs
  aptos-move/framework/src/prover.rs
  aptos-move/framework/tests/move_prover_tests.rs
  crates/aptos/src/move_tool/mod.rs
Labels: CICD:run-e2e-tests

#5270 [move] Updating move commit with docgen fix for index generation
  Cargo.lock
  Cargo.toml
  aptos-move/framework/aptos-framework/doc/overview.md
  aptos-move/framework/aptos-stdlib/doc/overview.md
  aptos-move/framework/aptos-token/doc/overview.md
Labels: CICD:run-e2e-tests

#5223 [Indexer] Fix collection data
  crates/indexer/src/models/token_models/token_utils.rs
  crates/indexer/src/processors/token_processor.rs
Labels: CICD:build-images

#5215 [Indexer] Staking pool to voter mapping
  crates/indexer/migrations/2022-10-21-055518_stake_to_voter/down.sql
  crates/indexer/migrations/2022-10-21-055518_stake_to_voter/up.sql
  crates/indexer/src/models/mod.rs
  crates/indexer/src/models/stake_models/mod.rs
  crates/indexer/src/models/stake_models/stake_utils.rs
  crates/indexer/src/models/stake_models/staking_pool_voter.rs
  crates/indexer/src/models/token_models/token_utils.rs
  crates/indexer/src/processors/mod.rs
  crates/indexer/src/processors/stake_processor.rs
  crates/indexer/src/processors/token_processor.rs
  crates/indexer/src/runtime.rs
  crates/indexer/src/schema.rs
Labels: CICD:build-images

#5214 [Indexer] Fix timestamp bug and restart from gap
  crates/indexer/migrations/2022-10-21-055518_stake_to_voter/down.sql
  crates/indexer/migrations/2022-10-21-055518_stake_to_voter/up.sql
  crates/indexer/src/indexer/tailer.rs
  crates/indexer/src/models/mod.rs
  crates/indexer/src/models/stake_models/mod.rs
  crates/indexer/src/models/stake_models/stake_utils.rs
  crates/indexer/src/models/stake_models/staking_pool_voter.rs
  crates/indexer/src/models/token_models/token_utils.rs
  crates/indexer/src/processors/coin_processor.rs
  crates/indexer/src/processors/default_processor.rs
  crates/indexer/src/processors/mod.rs
  crates/indexer/src/processors/stake_processor.rs
  crates/indexer/src/processors/token_processor.rs
  crates/indexer/src/runtime.rs
  crates/indexer/src/schema.rs
  crates/indexer/src/util.rs
Labels: CICD:build-images

#5297 [move] Fix artifact generation and test for pure Move development
  Cargo.lock
  Cargo.toml
  aptos-move/framework/Cargo.toml
  aptos-move/framework/artifacts-test/Cargo.toml
  aptos-move/framework/artifacts-test/README.md
  aptos-move/framework/artifacts-test/src/artifact_test.rs
  aptos-move/framework/artifacts-test/src/lib.rs
  aptos-move/framework/cached-packages/Cargo.toml
Labels: CICD:run-e2e-tests

#5374 [move] Print stack trace in unit tests
  crates/aptos/src/move_tool/mod.rs
Labels: CICD:run-e2e-tests
