Repository aptos-labs/aptos-core, pull requests merged in 2022-12, with the labels that each got.

#5685 [api] Add doc comment for git hash in index API
  api/doc/spec.json
  api/doc/spec.yaml
  api/types/src/index.rs
  ecosystem/typescript/sdk/src/generated/models/IndexResponse.ts
  ecosystem/typescript/sdk/src/generated/schemas/$IndexResponse.ts
Labels: CICD:run-e2e-tests

#5490 [forge][try2] Adding latency check for high-gas fee transactions to graceful_overload test
  crates/transaction-emitter-lib/src/emitter/mod.rs
  testsuite/forge-cli/src/main.rs
  testsuite/forge/src/interface/network.rs
  testsuite/forge/src/runner.rs
  testsuite/forge/src/success_criteria.rs
  testsuite/testcases/src/compatibility_test.rs
  testsuite/testcases/src/gas_price_test.rs
  testsuite/testcases/src/lib.rs
  testsuite/testcases/src/partial_nodes_down_test.rs
  testsuite/testcases/src/state_sync_performance.rs
  testsuite/testcases/src/two_traffics_test.rs
  testsuite/testcases/tests/forge-local-performance.rs
Labels: CICD:run-e2e-tests

#5775 [gha] Add composite action for git credentials
  .github/actions/gar-auth/action.yaml
  .github/actions/rust-setup/action.yaml
  .github/workflows/copy-images-to-dockerhub.yaml
  .github/workflows/docker-rust-build.yaml
  .github/workflows/lint-test.yaml
  .github/workflows/sdk-release.yaml
  docker/docker-bake-rust-all.hcl
  docker/docker-bake-rust-all.sh
  docker/rust-all.Dockerfile
Labels: CICD:run-e2e-tests

#5782 [hotfixes] Update testnet branch with the most recent hotfixes
  Cargo.lock
  Cargo.toml
  aptos-move/aptos-vm/src/move_vm_ext/vm.rs
  aptos-move/framework/aptos-framework/doc/aptos_account.md
  aptos-move/framework/aptos-framework/doc/block.md
  aptos-move/framework/aptos-framework/doc/state_storage.md
  aptos-move/framework/aptos-stdlib/doc/type_info.md
  aptos-move/framework/aptos-token/doc/token.md
Labels: CICD:run-e2e-tests

#4591 [Forge] Add working_dir param to support running node on checkpoint dir, so that the existing data on disk is preserved.
  aptos-node/src/lib.rs
  config/src/config/mod.rs
  consensus/src/consensusdb/mod.rs
  consensus/src/lib.rs
  docker/compose/aptos-node/validator.yaml
  state-sync/state-sync-v2/state-sync-driver/src/metadata_storage.rs
  storage/aptosdb/src/lib.rs
  terraform/helm/aptos-node/files/configs/validator-base.yaml
  testsuite/forge/src/backend/local/node.rs
Labels: CICD:build-images

#5801 [State Sync] Add metrics around chunk sizes.
  state-sync/state-sync-v2/state-sync-driver/src/metrics.rs
  state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
Labels: CICD:run-e2e-tests

#5755 terraform k8s separation
  terraform/aptos-node-testnet/addons.tf
  terraform/aptos-node-testnet/main.tf
  terraform/aptos-node-testnet/variables.tf
  terraform/aptos-node/aws/kubernetes.tf
  terraform/aptos-node/aws/variables.tf
  terraform/aptos-node/gcp/kubernetes.tf
  terraform/aptos-node/gcp/variables.tf
Labels: CICD:run-e2e-tests

#5814 [State Sync] Add metrics for fast syncing chunk sizes.
  state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
Labels: CICD:run-e2e-tests

#5464 [quorum store] payload_manager
  Cargo.lock
  consensus/Cargo.toml
  consensus/consensus-types/Cargo.toml
  consensus/consensus-types/src/block.rs
  consensus/consensus-types/src/block_data.rs
  consensus/consensus-types/src/block_test.rs
  consensus/consensus-types/src/block_test_utils.rs
  consensus/consensus-types/src/common.rs
  consensus/consensus-types/src/executed_block.rs
  consensus/consensus-types/src/lib.rs
  consensus/consensus-types/src/proof_of_store.rs
  consensus/consensus-types/src/proposal_msg.rs
  consensus/consensus-types/src/request_response.rs
  consensus/safety-rules/src/test_utils.rs
  consensus/safety-rules/src/tests/suite.rs
  consensus/src/block_storage/block_store.rs
  consensus/src/block_storage/block_store_test.rs
  consensus/src/commit_notifier.rs
  consensus/src/consensus_provider.rs
  consensus/src/epoch_manager.rs
  consensus/src/experimental/ordering_state_computer.rs
  consensus/src/experimental/tests/buffer_manager_tests.rs
  consensus/src/experimental/tests/execution_phase_tests.rs
  consensus/src/experimental/tests/test_utils.rs
  consensus/src/lib.rs
  consensus/src/liveness/proposal_generator.rs
  consensus/src/liveness/proposal_generator_test.rs
  consensus/src/liveness/unequivocal_proposer_election_test.rs
  consensus/src/network_tests.rs
  consensus/src/payload_client.rs
  consensus/src/payload_manager.rs
  consensus/src/quorum_store/batch_reader.rs
  consensus/src/quorum_store/direct_mempool_quorum_store.rs
  consensus/src/quorum_store/mod.rs
  consensus/src/quorum_store/tests/direct_mempool_quorum_store_test.rs
  consensus/src/round_manager.rs
  consensus/src/round_manager_fuzzing.rs
  consensus/src/round_manager_test.rs
  consensus/src/state_computer.rs
  consensus/src/state_replication.rs
  consensus/src/test_utils/mock_payload_manager.rs
  consensus/src/test_utils/mock_state_computer.rs
  consensus/src/test_utils/mod.rs
  consensus/src/twins/twins_node.rs
  consensus/src/txn_notifier.rs
  crates/aptos-infallible/src/mutex.rs
  execution/executor-types/src/error.rs
  testsuite/generate-format/tests/staged/consensus.yaml
Labels: CICD:run-e2e-tests

#5825 [Cargo] Update lock file.
  Cargo.lock
Labels: CICD:run-e2e-tests

#5800 [test helper] add function to enable initializing and minting of aptos coin with genesis
  aptos-move/framework/aptos-framework/sources/aptos_coin.move
Labels: CICD:run-e2e-tests

#5856 [Build scripts] Fix some build scripts after crate renames.
  docker/build-rust-all.sh
  docker/rust-all.Dockerfile
  execution/db-bootstrapper/src/bin/aptos-db-bootstrapper.rs
  testsuite/smoke-test/src/genesis.rs
  types/src/transaction/mod.rs
Labels: CICD:run-e2e-tests

#5855 [move-examples] cleanup testing
  aptos-move/move-examples/marketplace/sources/marketplace_auction_example.move
  aptos-move/move-examples/marketplace/sources/marketplace_bid_utils.move
  aptos-move/move-examples/marketplace/sources/marketplace_listing_utils.move
  aptos-move/move-examples/tests/move_unit_tests.rs
Labels: CICD:run-e2e-tests

#4967 Redistributing fees
  aptos-move/e2e-move-tests/src/tests/code_publishing.data/pack_stdlib/sources/configs/features.move
  aptos-move/framework/aptos-framework/doc/block.md
  aptos-move/framework/aptos-framework/doc/coin.md
  aptos-move/framework/aptos-framework/doc/fee_distribution.md
  aptos-move/framework/aptos-framework/doc/reconfiguration.md
  aptos-move/framework/aptos-framework/doc/stake.md
  aptos-move/framework/aptos-framework/doc/transaction_fee.md
  aptos-move/framework/aptos-framework/doc/transaction_validation.md
  aptos-move/framework/aptos-framework/sources/block.move
  aptos-move/framework/aptos-framework/sources/coin.move
  aptos-move/framework/aptos-framework/sources/reconfiguration.move
  aptos-move/framework/aptos-framework/sources/stake.move
  aptos-move/framework/aptos-framework/sources/transaction_fee.move
  aptos-move/framework/aptos-framework/sources/transaction_validation.move
  aptos-move/framework/move-stdlib/doc/features.md
  aptos-move/framework/move-stdlib/sources/configs/features.move
Labels: CICD:run-e2e-tests

#5771 [Spec] Added specs for module gas_schedule & aptos_coin & chain_id & chain_status.
  aptos-move/framework/aptos-framework/doc/aptos_coin.md
  aptos-move/framework/aptos-framework/doc/chain_id.md
  aptos-move/framework/aptos-framework/doc/chain_status.md
  aptos-move/framework/aptos-framework/doc/gas_schedule.md
  aptos-move/framework/aptos-framework/doc/util.md
  aptos-move/framework/aptos-framework/sources/aptos_coin.spec.move
  aptos-move/framework/aptos-framework/sources/chain_id.spec.move
  aptos-move/framework/aptos-framework/sources/chain_status.spec.move
  aptos-move/framework/aptos-framework/sources/configs/gas_schedule.spec.move
  aptos-move/framework/aptos-framework/sources/util.spec.move
Labels: move-prover

#5875 [language] Compile time and runtime checking of view (and entry) functions
  Cargo.lock
  Cargo.toml
  api/goldens/aptos_api__tests__state_test__test_get_account_module.json
  api/goldens/aptos_api__tests__view_function__test_simple_view_invalid.json
  api/src/tests/view_function.rs
  aptos-move/aptos-module-verifier/Cargo.toml
  aptos-move/aptos-module-verifier/src/lib.rs
  aptos-move/aptos-vm/Cargo.toml
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/aptos_vm_impl.rs
  aptos-move/aptos-vm/src/lib.rs
  aptos-move/aptos-vm/src/verifier/mod.rs
  aptos-move/aptos-vm/src/verifier/module_init.rs
  aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs
  aptos-move/aptos-vm/src/verifier/view_function.rs
  aptos-move/framework/Cargo.toml
  aptos-move/framework/aptos-framework/sources/coin.move
  aptos-move/framework/src/built_package.rs
  aptos-move/framework/src/error_map.rs
  aptos-move/framework/src/extended_checks.rs
  aptos-move/framework/src/lib.rs
  aptos-move/framework/src/module_metadata.rs
  crates/aptos/Cargo.toml
  crates/aptos/src/move_tool/mod.rs
Labels: CICD:run-e2e-tests

#5888 [validator-test] binding docker to specific bcc commit
  docker/rust-all.Dockerfile
Labels: CICD:build-images, CICD:run-e2e-tests

#5400 [quorum store] new onchain config for turning on quorum store and turning off mempool broadcast
  aptos-node/src/lib.rs
  config/src/config/consensus_config.rs
  config/src/config/mempool_config.rs
  consensus/src/epoch_manager.rs
  mempool/src/shared_mempool/coordinator.rs
  mempool/src/shared_mempool/tasks.rs
  mempool/src/shared_mempool/types.rs
  testsuite/smoke-test/src/aptos_cli/validator.rs
  types/src/on_chain_config/consensus_config.rs
Labels: CICD:run-e2e-tests

#5896 [move-vm] Generalize metadata for attribute parameters
  aptos-move/aptos-vm/src/verifier/view_function.rs
  aptos-move/framework/src/extended_checks.rs
  aptos-move/framework/src/module_metadata.rs
Labels: CICD:run-e2e-tests

#5866 [State sync] Add client-side of new state syncing mode.
  aptos-node/src/lib.rs
  config/src/config/state_sync_config.rs
  state-sync/state-sync-v2/data-streaming-service/src/data_notification.rs
  state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs
  state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs
  state-sync/state-sync-v2/data-streaming-service/src/streaming_client.rs
  state-sync/state-sync-v2/data-streaming-service/src/tests/data_stream.rs
  state-sync/state-sync-v2/data-streaming-service/src/tests/utils.rs
  state-sync/state-sync-v2/state-sync-driver/Cargo.toml
  state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
  state-sync/state-sync-v2/state-sync-driver/src/continuous_syncer.rs
  state-sync/state-sync-v2/state-sync-driver/src/driver.rs
  state-sync/state-sync-v2/state-sync-driver/src/driver_factory.rs
  state-sync/state-sync-v2/state-sync-driver/src/metrics.rs
  state-sync/state-sync-v2/state-sync-driver/src/tests/bootstrapper.rs
  state-sync/state-sync-v2/state-sync-driver/src/tests/continuous_syncer.rs
  state-sync/state-sync-v2/state-sync-driver/src/tests/driver.rs
  state-sync/state-sync-v2/state-sync-driver/src/tests/driver_factory.rs
  state-sync/state-sync-v2/state-sync-driver/src/tests/mocks.rs
  state-sync/state-sync-v2/state-sync-driver/src/utils.rs
  state-sync/storage-service/server/src/tests.rs
  testsuite/smoke-test/src/state_sync.rs
Labels: CICD:run-e2e-tests

#5907 [State Sync] Bump fallback time from 2 minutes to 3 minutes.
  config/src/config/state_sync_config.rs
Labels: CICD:run-e2e-tests

#5915 [Parallel Execution] Counter for dependency waits
  aptos-move/block-executor/src/counters.rs
  aptos-move/block-executor/src/executor.rs
Labels: CICD:run-e2e-tests

#5731 [Executor] Unify views used for block execution
  Cargo.lock
  api/src/context.rs
  api/src/state.rs
  aptos-move/aptos-aggregator/src/aggregator_extension.rs
  aptos-move/aptos-aggregator/src/delta_change_set.rs
  aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs
  aptos-move/aptos-validator-interface/src/lib.rs
  aptos-move/aptos-vm/src/adapter_common.rs
  aptos-move/aptos-vm/src/aptos_vm_impl.rs
  aptos-move/aptos-vm/src/block_executor/mod.rs
  aptos-move/aptos-vm/src/block_executor/storage_wrapper.rs
  aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs
  aptos-move/aptos-vm/src/data_cache.rs
  aptos-move/aptos-vm/src/delta_state_view.rs
  aptos-move/block-executor/Cargo.toml
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/lib.rs
  aptos-move/block-executor/src/output_delta_resolver.rs
  aptos-move/block-executor/src/proptest_types/bencher.rs
  aptos-move/block-executor/src/proptest_types/tests.rs
  aptos-move/block-executor/src/proptest_types/types.rs
  aptos-move/block-executor/src/task.rs
  aptos-move/block-executor/src/txn_last_input_output.rs
  aptos-move/block-executor/src/unit_tests/mod.rs
  aptos-move/block-executor/src/view.rs
  aptos-move/e2e-tests/src/data_store.rs
  aptos-move/e2e-tests/src/executor.rs
  aptos-move/e2e-testsuite/src/tests/failed_transaction_tests.rs
  aptos-move/vm-genesis/src/genesis_context.rs
  aptos-move/vm-genesis/src/lib.rs
  aptos-move/writeset-transaction-generator/src/writeset_builder.rs
  execution/executor/src/db_bootstrapper.rs
  execution/executor/src/mock_vm/mock_vm_test.rs
  storage/state-view/src/lib.rs
  storage/storage-interface/src/cached_state_view.rs
  storage/storage-interface/src/state_view.rs
Labels: CICD:run-e2e-tests

#5779 [Quorum Store] networking integration
  Cargo.lock
  consensus/Cargo.toml
  consensus/consensus-types/src/proof_of_store.rs
  consensus/src/counters.rs
  consensus/src/epoch_manager.rs
  consensus/src/experimental/tests/buffer_manager_tests.rs
  consensus/src/network.rs
  consensus/src/network_interface.rs
  consensus/src/quorum_store/mod.rs
  consensus/src/quorum_store/types.rs
  consensus/src/round_manager.rs
  testsuite/generate-format/tests/staged/consensus.yaml
Labels: CICD:run-e2e-tests

#5892 [Execution/Commit] Tiny optimizations.
  execution/executor-types/src/in_memory_state_calculator.rs
  execution/executor/src/block_executor.rs
  execution/executor/src/components/apply_chunk_output.rs
  execution/executor/src/metrics.rs
  storage/aptosdb/src/event_store/mod.rs
  storage/aptosdb/src/event_store/test.rs
  storage/aptosdb/src/ledger_store/ledger_info_test_utils.rs
  storage/aptosdb/src/ledger_store/mod.rs
  storage/aptosdb/src/ledger_store/transaction_info_test.rs
  storage/aptosdb/src/lib.rs
  storage/aptosdb/src/pruner/event_store/test.rs
  storage/aptosdb/src/pruner/state_store/test.rs
  storage/aptosdb/src/pruner/transaction_store/test.rs
  storage/aptosdb/src/state_store/mod.rs
  storage/aptosdb/src/state_store/state_store_test.rs
  storage/aptosdb/src/test_helper.rs
  storage/aptosdb/src/transaction_store/mod.rs
  storage/aptosdb/src/transaction_store/test.rs
Labels: CICD:run-e2e-tests

#5838 concurrency
  Cargo.lock
  aptos-move/aptos-vm/src/block_executor/mod.rs
  aptos-move/block-executor/src/counters.rs
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/output_delta_resolver.rs
  aptos-move/block-executor/src/proptest_types/types.rs
  aptos-move/block-executor/src/task.rs
  aptos-move/block-executor/src/unit_tests/mod.rs
  aptos-move/block-executor/src/view.rs
  aptos-move/mvhashmap/Cargo.toml
  aptos-move/mvhashmap/src/lib.rs
  aptos-move/mvhashmap/src/unit_tests/proptest_types.rs
  config/src/config/consensus_config.rs
  config/src/config/execution_config.rs
  consensus/src/liveness/proposal_generator.rs
  execution/executor/src/block_executor.rs
  storage/storage-interface/src/cached_state_view.rs
  testsuite/forge-cli/src/main.rs
  testsuite/forge.py
  testsuite/forge/src/runner.rs
  types/src/access_path.rs
Labels: CICD:run-e2e-tests

#5937 Update txn emitter to produce p2p txns with less confliction.
  consensus/src/liveness/proposal_generator.rs
  crates/transaction-emitter-lib/src/emitter/account_minter.rs
  crates/transaction-emitter-lib/src/emitter/mod.rs
  crates/transaction-emitter-lib/src/transaction_generator/p2p_transaction_generator.rs
  testsuite/forge/src/runner.rs
Labels: CICD:build-images, CICD:run-e2e-tests

#5971 [State Sync] Add a config flag around auto-bootstrapping.
  aptos-node/src/lib.rs
  config/src/config/state_sync_config.rs
  state-sync/state-sync-v2/state-sync-driver/src/driver.rs
  state-sync/state-sync-v2/state-sync-driver/src/tests/driver.rs
  testsuite/forge/src/backend/local/swarm.rs
  testsuite/smoke-test/src/consensus/consensus_fault_tolerance.rs
Labels: CICD:run-e2e-tests

#5981 [State Sync] Remove unnecessary panics and expects.
  config/src/config/state_sync_config.rs
  state-sync/inter-component/event-notifications/src/lib.rs
  state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs
  state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs
  state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs
  state-sync/state-sync-v2/state-sync-driver/src/bootstrapper.rs
  state-sync/state-sync-v2/state-sync-driver/src/continuous_syncer.rs
  state-sync/state-sync-v2/state-sync-driver/src/driver.rs
  state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs
  state-sync/state-sync-v2/state-sync-driver/src/utils.rs
Labels: CICD:run-e2e-tests

#5985 [Gas] Correct the gas schedule version for a recently added native function
  aptos-move/aptos-gas/src/aptos_framework.rs
  aptos-move/aptos-gas/src/gas_meter.rs
Labels: CICD:run-e2e-tests

#5982 [dockerfile] Improve validator-testing image build speed
  docker/rust-all.Dockerfile
Labels: CICD:run-e2e-tests

#6022 [Network] Avoid two calls to poll_write for each network frame
  network/src/noise/stream.rs
Labels: CICD:run-e2e-tests
