Repository aptos-labs/aptos-core, pull requests merged in 2022-04, with the labels that each got.

#579 [move] Upgrade move to 6a80792ecbf16d74bf1d57e48a576377f0879646
  Cargo.lock
  api/Cargo.toml
  api/types/Cargo.toml
  api/types/src/address.rs
  aptos-move/af-cli/Cargo.toml
  aptos-move/aptos-resource-viewer/Cargo.toml
  aptos-move/aptos-transaction-benchmarks/Cargo.toml
  aptos-move/aptos-transactional-test-harness/Cargo.toml
  aptos-move/aptos-validator-interface/Cargo.toml
  aptos-move/aptos-vm/Cargo.toml
  aptos-move/e2e-tests-replay/Cargo.toml
  aptos-move/e2e-tests/Cargo.toml
  aptos-move/e2e-testsuite/Cargo.toml
  aptos-move/framework/Cargo.toml
  aptos-move/framework/cached-packages/Cargo.toml
  aptos-move/genesis-viewer/Cargo.toml
  aptos-move/move-examples/Cargo.toml
  aptos-move/transaction-builder-generator/Cargo.toml
  aptos-move/transaction-replay/Cargo.toml
  aptos-move/vm-genesis/Cargo.toml
  aptos-move/writeset-transaction-generator/Cargo.toml
  config/src/config/test_data/validator_full_node.yaml
  config/src/network_id.rs
  crates/aptos-faucet/src/main.rs
  crates/aptos-rest-client/Cargo.toml
  crates/aptos-workspace-hack/Cargo.toml
  crates/aptos/Cargo.toml
  execution/executor/Cargo.toml
  network/discovery/Cargo.toml
  sdk/Cargo.toml
  sdk/transaction-builder/Cargo.toml
  state-sync/inter-component/consensus-notifications/Cargo.toml
  state-sync/inter-component/event-notifications/Cargo.toml
  state-sync/state-sync-v1/Cargo.toml
  state-sync/storage-service/server/Cargo.toml
  storage/aptosdb/Cargo.toml
  storage/storage-interface/Cargo.toml
  terraform/helm/validator/files/configs/fullnode.yaml
  terraform/helm/validator/files/configs/validator.yaml
  testsuite/aptos-fuzzer/Cargo.toml
  testsuite/generate-format/Cargo.toml
  testsuite/smoke-test/Cargo.toml
  types/Cargo.toml
  vm-validator/Cargo.toml
  x.toml
Labels: bors-high-priority

#590 [aptos-cli] Fund accounts created by the faucet
  crates/aptos/src/account/create.rs
Labels: tooling

#626 [CircleCI] Remove duplicated circleci test
  .circleci/config.yml
  ecosystem/typescript/sdk/src/faucet_client.test.ts
Labels: bors-high-priority

#638 [circleci] killswitch to disable docker-compose tests
  .circleci/config.yml
Labels: bors-high-priority

#640 [ecosystem][indexer] Fix a flakey test
  testsuite/smoke-test/src/indexer.rs
Labels: bors-high-priority

#636 Clarifying documentation build steps
  developer-docs-site/README.md
Labels: bors-squash
