Repository aptos-labs/aptos-core, pull requests merged in 2022-11, with the labels that each got.

#5391 [Indexer] Make indexer snappy again
  crates/indexer/src/indexer/fetcher.rs
  crates/indexer/src/indexer/tailer.rs
  crates/indexer/src/runtime.rs
Labels: CICD:build-images

#5389 cicd: release indexer fullnode image to dockerhub
  docker/release-images.mjs
Labels: CICD:build-images

#5338 [Indexer] Improve indexer restart
  crates/indexer/README.md
  crates/indexer/migrations/2022-10-30-053525_add_vote_data/down.sql
  crates/indexer/migrations/2022-10-30-053525_add_vote_data/up.sql
  crates/indexer/src/indexer/fetcher.rs
  crates/indexer/src/indexer/tailer.rs
  crates/indexer/src/models/stake_models/mod.rs
  crates/indexer/src/models/stake_models/proposal_votes.rs
  crates/indexer/src/models/stake_models/stake_utils.rs
  crates/indexer/src/models/token_models/ans_lookup.rs
  crates/indexer/src/processors/stake_processor.rs
  crates/indexer/src/processors/token_processor.rs
  crates/indexer/src/runtime.rs
  crates/indexer/src/schema.rs
Labels: CICD:build-images

#4253 [consensus] Improve seed for leader election
  consensus/src/epoch_manager.rs
  consensus/src/liveness/leader_reputation.rs
  consensus/src/liveness/leader_reputation_test.rs
  types/src/on_chain_config/consensus_config.rs
Labels: CICD:run-e2e-tests

#4973 [consensus] Fix voting history for leader reputation
  consensus/src/epoch_manager.rs
  consensus/src/liveness/leader_reputation.rs
  consensus/src/liveness/leader_reputation_test.rs
  types/src/on_chain_config/consensus_config.rs
Labels: CICD:run-e2e-tests

#5254 Use jemalloc for the forge CLI
  Cargo.lock
  testsuite/forge-cli/Cargo.toml
  testsuite/forge-cli/src/main.rs
Labels: CICD:run-e2e-tests

#5443 [TS][SDK] Use pnpm instead of yarn
  .github/workflows/sdk-release.yaml
  developer-docs-site/docs/guides/local-testnet-dev-flow.md
  developer-docs-site/docs/sdks/ts-sdk/typescript-sdk.md
  developer-docs-site/docs/tutorials/first-coin.md
  developer-docs-site/docs/tutorials/first-transaction.md
  developer-docs-site/docs/tutorials/index.md
  developer-docs-site/docs/tutorials/your-first-nft.md
  ecosystem/typescript/sdk/.gitignore
  ecosystem/typescript/sdk/CONTRIBUTING.md
  ecosystem/typescript/sdk/README.md
  ecosystem/typescript/sdk/checked_publish.sh
  ecosystem/typescript/sdk/examples/javascript/pnpm-lock.yaml
  ecosystem/typescript/sdk/examples/javascript/yarn.lock
  ecosystem/typescript/sdk/examples/typescript-esm/package.json
  ecosystem/typescript/sdk/examples/typescript-esm/yarn.lock
  ecosystem/typescript/sdk/examples/typescript/pnpm-lock.yaml
  ecosystem/typescript/sdk/examples/typescript/yarn.lock
  ecosystem/typescript/sdk/examples/typescript/your_coin.ts
  ecosystem/typescript/sdk/package.json
  ecosystem/typescript/sdk/pnpm-lock.yaml
  ecosystem/typescript/sdk/yarn.lock
  scripts/dev_setup.sh
Labels: CICD:build-images, CICD:run-e2e-tests, prio:high

#5119 [typescript-sdk] support multisig transaction simulation
  ecosystem/typescript/sdk/src/aptos_client.test.ts
  ecosystem/typescript/sdk/src/aptos_client.ts
Labels: CICD:run-e2e-tests

#5120 export aptos_types
  ecosystem/typescript/sdk/src/index.ts
Labels: CICD:run-e2e-tests

#5283 [gha] update compat image to testnet prefix
  .github/workflows/docker-build-test.yaml
Labels: CICD:run-e2e-tests

#5466 [move] Update Move commit hash
  Cargo.lock
  Cargo.toml
  aptos-move/aptos-gas/src/move_stdlib.rs
  aptos-move/framework/tests/move_unit_test.rs
  aptos-move/move-examples/tests/move_unit_tests.rs
  crates/aptos/src/move_tool/mod.rs
Labels: CICD:run-e2e-tests

#5452 [forge] refactor and helm values config
  terraform/aptos-node-testnet/forge.tf
  terraform/aptos-node-testnet/variables.tf
  terraform/helm/monitoring/values.yaml
  testsuite/fixtures/forge-default-helm-values-after.fixture
  testsuite/fixtures/forge-default-helm-values-before.fixture
  testsuite/fixtures/forge-default-helm-values-preview.fixture
  testsuite/forge.py
  testsuite/forge_test.py
  testsuite/forge_wrapper_core/filesystem.py
  testsuite/forge_wrapper_core/git.py
  testsuite/forge_wrapper_core/process.py
  testsuite/forge_wrapper_core/shell.py
  testsuite/forge_wrapper_core/time.py
Labels: CICD:run-e2e-tests

#5564 [move] Update move commit hash
  Cargo.lock
  Cargo.toml
  aptos-move/aptos-vm/src/move_vm_ext/vm.rs
Labels: CICD:run-e2e-tests

#4834 [consensus] Add gracefull backoff based on chain health
  config/src/config/consensus_config.rs
  consensus/src/counters.rs
  consensus/src/epoch_manager.rs
  consensus/src/liveness/cached_proposer_election.rs
  consensus/src/liveness/leader_reputation.rs
  consensus/src/liveness/leader_reputation_test.rs
  consensus/src/liveness/proposal_generator.rs
  consensus/src/liveness/proposal_generator_test.rs
  consensus/src/liveness/proposer_election.rs
  consensus/src/liveness/unequivocal_proposer_election.rs
  consensus/src/round_manager_fuzzing.rs
  consensus/src/round_manager_test.rs
Labels: CICD:run-e2e-tests

#5571 fix(indexer): `collection_data_id_hash` inconsistent in different token tables
  crates/indexer/src/models/token_models/token_utils.rs
Labels: CICD:build-images

#5584 [Forge] Add simple test for fast sync throughput.
  .github/workflows/continuous-e2e-state-sync-perf-fullnode-fast-sync-test.yaml
  crates/transaction-emitter-lib/src/emitter/account_minter.rs
  crates/transaction-emitter-lib/src/emitter/mod.rs
  crates/transaction-emitter-lib/src/wrappers.rs
  testsuite/forge-cli/src/main.rs
  testsuite/forge/src/interface/swarm.rs
  testsuite/testcases/src/state_sync_performance.rs
Labels: CICD:run-e2e-tests

#5604 [Forge] Fix grafana dashboard link
  testsuite/forge.py
Labels: CICD:run-e2e-tests

#5657 [Cargo] Move crates to workspace dependencies.
  Cargo.lock
  Cargo.toml
  aptos-move/aptos-aggregator/Cargo.toml
  aptos-move/aptos-debugger/Cargo.toml
  aptos-move/aptos-gas/Cargo.toml
  aptos-move/aptos-release-builder/Cargo.toml
  aptos-move/aptos-resource-viewer/Cargo.toml
  aptos-move/aptos-sdk-builder/Cargo.toml
  aptos-move/aptos-transaction-benchmarks/Cargo.toml
  aptos-move/aptos-transactional-test-harness/Cargo.toml
  aptos-move/aptos-validator-interface/Cargo.toml
  aptos-move/aptos-vm/Cargo.toml
  aptos-move/e2e-move-tests/Cargo.toml
  aptos-move/e2e-tests/Cargo.toml
  aptos-move/e2e-testsuite/Cargo.toml
  aptos-move/framework/Cargo.toml
  aptos-move/framework/artifacts-test/Cargo.toml
  aptos-move/framework/cached-packages/Cargo.toml
  aptos-move/move-examples/Cargo.toml
  aptos-move/mvhashmap/Cargo.toml
  aptos-move/package-builder/Cargo.toml
  aptos-move/parallel-executor/Cargo.toml
  aptos-move/vm-genesis/Cargo.toml
  aptos-move/writeset-transaction-generator/Cargo.toml
  scripts/find-packages-with-undeclared-feature-dependencies.sh
  secure/net/Cargo.toml
  secure/storage/Cargo.toml
  secure/storage/github/Cargo.toml
  secure/storage/vault/Cargo.toml
  state-sync/state-sync-v2/state-sync-driver/Cargo.toml
  storage/accumulator/Cargo.toml
  storage/aptosdb/Cargo.toml
  storage/backup/backup-cli/Cargo.toml
  storage/backup/backup-service/Cargo.toml
  storage/indexer/Cargo.toml
  storage/jellyfish-merkle/Cargo.toml
  storage/rocksdb-options/Cargo.toml
  storage/schemadb/Cargo.toml
  storage/scratchpad/Cargo.toml
  storage/state-view/Cargo.toml
  storage/storage-interface/Cargo.toml
  testsuite/aptos-fuzzer/Cargo.toml
  testsuite/aptos-fuzzer/fuzz/Cargo.toml
  testsuite/dos/http_test/Cargo.toml
  testsuite/dos/listener/Cargo.toml
  testsuite/dos/sender/Cargo.toml
  testsuite/forge-cli/Cargo.toml
  testsuite/forge/Cargo.toml
  testsuite/generate-format/Cargo.toml
  testsuite/smoke-test/Cargo.toml
  testsuite/testcases/Cargo.toml
  types/Cargo.toml
  vm-validator/Cargo.toml
Labels: CICD:run-e2e-tests

#5667 [Cargo] Migrate workspace dependencies.
  Cargo.lock
  Cargo.toml
  crates/aptos-bitvec/Cargo.toml
  crates/aptos-build-info/Cargo.toml
  crates/aptos-compression/Cargo.toml
  crates/aptos-crypto-derive/Cargo.toml
  crates/aptos-crypto/Cargo.toml
  crates/aptos-faucet-cli/Cargo.toml
  crates/aptos-faucet/Cargo.toml
  crates/aptos-genesis/Cargo.toml
  crates/aptos-keygen/Cargo.toml
  crates/aptos-log-derive/Cargo.toml
  crates/aptos-logger/Cargo.toml
  crates/aptos-metrics-core/Cargo.toml
  crates/aptos-network-checker/Cargo.toml
  crates/aptos-openapi/Cargo.toml
  crates/aptos-proptest-helpers/Cargo.toml
  crates/aptos-push-metrics/Cargo.toml
  crates/aptos-rate-limiter/Cargo.toml
  crates/aptos-rest-client/Cargo.toml
  crates/aptos-retrier/Cargo.toml
  crates/aptos-rosetta-cli/Cargo.toml
  crates/aptos-rosetta/Cargo.toml
  crates/aptos-telemetry-service/Cargo.toml
  crates/aptos-telemetry/Cargo.toml
  crates/aptos-temppath/Cargo.toml
  crates/aptos-time-service/Cargo.toml
  crates/aptos-warp-webserver/Cargo.toml
  crates/aptos/Cargo.toml
  crates/bounded-executor/Cargo.toml
  crates/channel/Cargo.toml
  crates/crash-handler/Cargo.toml
  crates/fallible/Cargo.toml
  crates/indexer/Cargo.toml
  crates/inspection-service/Cargo.toml
  crates/node-resource-metrics/Cargo.toml
  crates/num-variants/Cargo.toml
  crates/proxy/Cargo.toml
  crates/short-hex-str/Cargo.toml
  crates/transaction-emitter-lib/Cargo.toml
  crates/transaction-emitter/Cargo.toml
Labels: CICD:run-e2e-tests

#5576 [forge] Add three_region_simulation_with_different_node_speed
  .github/workflows/continuous-e2e-network-latency-with-different-node-speed-test.yaml
  aptos-move/aptos-vm/src/aptos_vm.rs
  testsuite/forge-cli/src/main.rs
  testsuite/testcases/src/three_region_simulation_test.rs
Labels: CICD:run-e2e-tests

#5683 [leader election] Improve leader election for first 20 rounds
  consensus/src/epoch_manager.rs
  consensus/src/liveness/cached_proposer_election.rs
  consensus/src/liveness/cached_proposer_election_test.rs
Labels: CICD:run-e2e-tests

#5699 [Smoke Tests] Ignore flaky tests.
  testsuite/smoke-test/src/state_sync.rs
Labels: CICD:run-e2e-tests

#4683 [Executor] Merge sequential & parallel execution flow
  CODEOWNERS
  Cargo.lock
  Cargo.toml
  aptos-move/aptos-aggregator/src/transaction.rs
  aptos-move/aptos-transaction-benchmarks/src/transactions.rs
  aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs
  aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/call_function.exp
  aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/execute_script.exp
  aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/publish_module.exp
  aptos-move/aptos-transactional-test-harness/tests/aptos_test_harness/write_set_too_large.exp
  aptos-move/aptos-vm/Cargo.toml
  aptos-move/aptos-vm/src/adapter_common.rs
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/block_executor/mod.rs
  aptos-move/aptos-vm/src/block_executor/storage_wrapper.rs
  aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs
  aptos-move/aptos-vm/src/data_cache.rs
  aptos-move/aptos-vm/src/lib.rs
  aptos-move/aptos-vm/src/parallel_executor/mod.rs
  aptos-move/aptos-vm/src/parallel_executor/vm_wrapper.rs
  aptos-move/block-executor/Cargo.toml
  aptos-move/block-executor/benches/scheduler_benches.rs
  aptos-move/block-executor/src/counters.rs
  aptos-move/block-executor/src/errors.rs
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/lib.rs
  aptos-move/block-executor/src/output_delta_resolver.rs
  aptos-move/block-executor/src/proptest_types/bencher.rs
  aptos-move/block-executor/src/proptest_types/mod.rs
  aptos-move/block-executor/src/proptest_types/tests.rs
  aptos-move/block-executor/src/proptest_types/types.rs
  aptos-move/block-executor/src/scheduler.rs
  aptos-move/block-executor/src/task.rs
  aptos-move/block-executor/src/txn_last_input_output.rs
  aptos-move/block-executor/src/unit_tests/mod.rs
  aptos-move/e2e-move-tests/Cargo.toml
  aptos-move/e2e-tests/src/executor.rs
  aptos-move/e2e-testsuite/Cargo.toml
Labels: CICD:run-e2e-tests

#5726 [move] Multiple fixes
  Cargo.lock
  Cargo.toml
  aptos-move/aptos-vm/src/move_vm_ext/vm.rs
  aptos-move/e2e-move-tests/src/tests/mod.rs
  aptos-move/e2e-move-tests/src/tests/type_too_large.data/type_too_large/Move.toml
  aptos-move/e2e-move-tests/src/tests/type_too_large.data/type_too_large/sources/test.move
  aptos-move/e2e-move-tests/src/tests/type_too_large.rs
  aptos-move/framework/aptos-stdlib/doc/type_info.md
  aptos-move/framework/aptos-token/doc/token.md
  consensus/src/liveness/proposal_generator.rs
  crates/aptos-crypto/src/multi_ed25519.rs
Labels: CICD:run-e2e-tests

#5600 Fix functions for getting all resources / modules on an account by using pagination
  .github/workflows/sdk-release.yaml
  Cargo.lock
  api/types/src/headers.rs
  crates/aptos-rest-client/Cargo.toml
  crates/aptos-rest-client/examples/README.md
  crates/aptos-rest-client/examples/account/main.rs
  crates/aptos-rest-client/src/lib.rs
  crates/aptos-rest-client/src/state.rs
Labels: CICD:build-images, CICD:run-e2e-tests, CICD:run-coverage

#5711 [aptos-transaction-benchmark] Fix benchmark regression
  Cargo.lock
  aptos-move/aptos-transaction-benchmarks/Cargo.toml
Labels: CICD:run-e2e-tests
