Repository aptos-labs/aptos-core, pull requests merged in 2022-06, with the labels that each got.

#1309 Revert "[forge] remove direct eks cluster scaling"
  scripts/fgi/kube.py
  testsuite/forge-cli/src/main.rs
  testsuite/forge/src/backend/k8s/cluster_helper.rs
  testsuite/forge/src/backend/k8s/mod.rs
  testsuite/forge/src/backend/k8s/swarm.rs
Labels: CICD:build-images

#1333 Revert "[Telemetry] Update system metrics."
  Cargo.lock
  aptos-node/src/lib.rs
  crates/aptos-metrics/Cargo.toml
  crates/aptos-metrics/build.rs
  crates/aptos-metrics/src/json_metrics.rs
  crates/aptos-metrics/src/lib.rs
  crates/aptos-metrics/src/metric_server.rs
  crates/aptos-metrics/src/system_information.rs
  crates/aptos-metrics/src/system_metrics.rs
  crates/aptos-telemetry/Cargo.toml
  crates/aptos-telemetry/src/constants.rs
  crates/aptos-telemetry/src/lib.rs
  crates/aptos-workspace-hack/Cargo.toml
  crates/debug-interface/src/node_debug_service.rs
Labels: bors-high-priority

#1504 Add test-only sequence number mocking, tests
  aptos-move/framework/aptos-framework/sources/Account.move
Labels: bors-squash

#1547 cicd: improve build-image/e2e-test triggering logic
  .github/workflows/build-images.yaml
Labels: CICD:build-images

#1574 [testnet] Fix minor bug in forge terraform
  terraform/aptos-node-testnet/outputs.tf
Labels: CICD:build-images

#1596 [testnet] Install the perf metapackage for debian based distro
  docker/rust-all.Dockerfile
Labels: CICD:build-images

#1636 [testnet] In privileged mode, log in as root
  terraform/helm/aptos-node/templates/validator.yaml
Labels: CICD:build-images

#1617 cicd: env for sdk-integration-test
  .github/workflows/sdk-integration-test.yaml
Labels: CICD:run-e2e-tests

#1665 [wallet]: fix signAndSubmitTransaction
  ecosystem/web-wallet/src/scripts/background.js
Labels: bug

#1566 [tf/helm][forge] get forge to run on aptos-node
  Cargo.lock
  crates/aptos-workspace-hack/Cargo.toml
  scripts/fgi/kube.py
  terraform/aptos-node-testnet/main.tf
  terraform/aptos-node-testnet/variables.tf
  terraform/aptos-node/aws/kubernetes.tf
  terraform/aptos-node/aws/variables.tf
  terraform/helm/forge/files/cleanup_forge.sh
  terraform/helm/forge/files/init_forge.sh
  terraform/helm/forge/templates/forge.yaml
  testsuite/forge/src/backend/k8s/cluster_helper.rs
  testsuite/forge/src/backend/k8s/mod.rs
  testsuite/forge/src/backend/k8s/swarm.rs
Labels: CICD:build-images
