Repository aptos-labs/aptos-core, pull requests merged in 2023-03, with the labels that each got.

#6719 [Forge][Quorum Store] On Chain Enable Quorum Store Test
  crates/aptos/src/test/mod.rs
  testsuite/forge-cli/src/main.rs
  testsuite/testcases/src/lib.rs
  testsuite/testcases/src/quorum_store_onchain_enable_test.rs
Labels: CICD:run-e2e-tests

#6815 [forge] fix total txns gas overflow
  crates/transaction-emitter-lib/src/emitter/account_minter.rs
  testsuite/forge-cli/src/main.rs
Labels: CICD:run-e2e-tests

#6818 [Quorum Store] fix expired proof metric
  consensus/src/quorum_store/utils.rs
Labels: CICD:run-e2e-tests

#6823 Move smart vector/table to framework
  aptos-move/e2e-move-tests/src/harness.rs
  aptos-move/e2e-move-tests/src/tests/gas.rs
  aptos-move/e2e-move-tests/src/tests/mod.rs
  aptos-move/e2e-move-tests/src/tests/smart_data_structures.data/Move.toml
  aptos-move/e2e-move-tests/src/tests/smart_data_structures.data/sources/test.move
  aptos-move/e2e-move-tests/src/tests/smart_data_structures.rs
  aptos-move/framework/aptos-stdlib/doc/big_vector.md
  aptos-move/framework/aptos-stdlib/doc/overview.md
  aptos-move/framework/aptos-stdlib/doc/smart_table.md
  aptos-move/framework/aptos-stdlib/doc/smart_vector.md
  aptos-move/framework/aptos-stdlib/sources/data_structures/big_vector.move
  aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.move
  aptos-move/framework/aptos-stdlib/sources/data_structures/smart_vector.move
Labels: documentation, release-notes

#6745 Add update StateValue and WriteOp to support metadata tracking
  api/types/src/convert.rs
  aptos-move/aptos-aggregator/src/aggregator_extension.rs
  aptos-move/aptos-aggregator/src/delta_change_set.rs
  aptos-move/aptos-aggregator/src/transaction.rs
  aptos-move/aptos-gas/src/transaction/mod.rs
  aptos-move/aptos-gas/src/transaction/storage.rs
  aptos-move/aptos-validator-interface/src/lib.rs
  aptos-move/aptos-validator-interface/src/rest_interface.rs
  aptos-move/aptos-vm/src/delta_state_view.rs
  aptos-move/block-executor/src/proptest_types/types.rs
  aptos-move/block-executor/src/view.rs
  aptos-move/e2e-tests/src/data_store.rs
  aptos-move/mvhashmap/src/unit_tests/mod.rs
  aptos-move/mvhashmap/src/unit_tests/proptest_types.rs
  aptos-move/vm-genesis/src/genesis_context.rs
  crates/aptos-rosetta/src/types/objects.rs
  execution/executor-types/src/in_memory_state_calculator.rs
  state-sync/storage-service/server/src/tests.rs
  storage/aptosdb/src/fake_aptosdb.rs
  storage/indexer/src/lib.rs
  storage/scratchpad/benches/sparse_merkle.rs
  testsuite/generate-format/tests/staged/api.yaml
  testsuite/generate-format/tests/staged/aptos.yaml
  testsuite/generate-format/tests/staged/consensus.yaml
  types/src/proptest_types.rs
  types/src/state_store/state_value.rs
  types/src/write_set.rs
Labels: CICD:run-e2e-tests

#6864 [Spec] Fix the broken spec with a mock-up spec
  aptos-move/framework/aptos-stdlib/doc/smart_table.md
  aptos-move/framework/aptos-stdlib/doc/smart_vector.md
  aptos-move/framework/aptos-stdlib/sources/data_structures/smart_table.spec.move
  aptos-move/framework/aptos-stdlib/sources/data_structures/smart_vector.spec.move
Labels: CICD:run-prover-test

#6777 [Prover] Natively modeled `object::exists_at`
  Cargo.lock
  Cargo.toml
  aptos-move/framework/aptos-framework/doc/object.md
  aptos-move/framework/aptos-framework/sources/object.spec.move
  aptos-move/framework/src/aptos-natives.bpl
  aptos-move/framework/src/prover.rs
  crates/aptos/src/move_tool/aptos-natives.bpl
Labels: CICD:run-prover-test

#6711 Indexer grpc refactor cache performance
  ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/worker.rs
  ecosystem/indexer-grpc/indexer-grpc-utils/src/cache_operator.rs
  ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator.rs
Labels: CICD:build-images

#6841 [Dockerfile][Experimental] Remove cargo-chef
  docker/experimental/builder.Dockerfile
  docker/experimental/debian-base.Dockerfile
  docker/experimental/docker-bake-rust-all.hcl
Labels: CICD:experimental-build

#6889 [Quorum Store] Implement end_epoch to clear state_computer between epoch end and start
  consensus/src/epoch_manager.rs
  consensus/src/experimental/ordering_state_computer.rs
  consensus/src/quorum_store/batch_reader.rs
  consensus/src/state_computer.rs
  consensus/src/state_replication.rs
  consensus/src/test_utils/mock_state_computer.rs
Labels: CICD:run-e2e-tests

#6770 [Network] Add client side of the peer monitoring service.
  Cargo.lock
  aptos-node/Cargo.toml
  aptos-node/src/services.rs
  config/src/config/network_config.rs
  config/src/network_id.rs
  crates/aptos-id-generator/src/lib.rs
  network/peer-monitoring-service/client/Cargo.toml
  network/peer-monitoring-service/client/src/error.rs
  network/peer-monitoring-service/client/src/lib.rs
  network/peer-monitoring-service/client/src/logging.rs
  network/peer-monitoring-service/client/src/metrics.rs
  network/peer-monitoring-service/client/src/network.rs
  network/peer-monitoring-service/client/src/peer_states/key_value.rs
  network/peer-monitoring-service/client/src/peer_states/latency_info.rs
  network/peer-monitoring-service/client/src/peer_states/mod.rs
  network/peer-monitoring-service/client/src/peer_states/network_info.rs
  network/peer-monitoring-service/client/src/peer_states/peer_state.rs
  network/peer-monitoring-service/client/src/peer_states/request_tracker.rs
  network/peer-monitoring-service/server/src/lib.rs
  network/peer-monitoring-service/types/src/lib.rs
  network/src/application/metadata.rs
  network/src/application/storage.rs
  network/src/application/tests.rs
  state-sync/aptos-data-client/src/aptosnet/state.rs
  state-sync/storage-service/client/src/lib.rs
  testsuite/smoke-test/src/network.rs
  testsuite/smoke-test/src/state_sync.rs
Labels: CICD:run-e2e-tests

#6518 [BlockSTM] Sender aware transaction shuffling
  consensus/Cargo.toml
  consensus/src/counters.rs
  consensus/src/epoch_manager.rs
  consensus/src/experimental/ordering_state_computer.rs
  consensus/src/lib.rs
  consensus/src/sender_aware_shuffler.rs
  consensus/src/state_computer.rs
  consensus/src/state_replication.rs
  consensus/src/test_utils/mock_state_computer.rs
  consensus/src/transaction_shuffler.rs
  execution/executor/src/components/chunk_output.rs
  types/src/on_chain_config/execution_config.rs
  types/src/on_chain_config/mod.rs
Labels: CICD:run-e2e-tests

#6073 Add CI for running Aptos CLI test suite
  .github/workflows/cli-e2e-tests.yaml
  .github/workflows/docker-build-test.yaml
  .github/workflows/sdk-release.yaml
  crates/aptos/e2e/cases/init.py
  crates/aptos/e2e/cases/shared.py
  crates/aptos/e2e/common.py
  crates/aptos/e2e/local_testnet.py
  crates/aptos/e2e/main.py
  crates/aptos/e2e/test_helpers.py
Labels: CICD:build-images, CICD:run-e2e-tests

#6957 [indexer grpc] Move the WriteResource data one-level down.
  ecosystem/indexer-grpc/indexer-grpc-fullnode/src/convert.rs
Labels: CICD:build-images

#6930 [Dockerfile][Experimental] Upgrade rust version
  docker/experimental/docker-bake-rust-all.hcl
Labels: CICD:experimental-build

#6979 [Dockerfile][Experimental][Bugfix] Upgrade rust version
  docker/experimental/docker-bake-rust-all.hcl
Labels: CICD:experimental-build

#6978 [Quorum Store] Use a single quorum_store_db instance across epochs
  consensus/src/consensus_provider.rs
  consensus/src/epoch_manager.rs
  consensus/src/quorum_store/batch_generator.rs
  consensus/src/quorum_store/batch_store.rs
  consensus/src/quorum_store/quorum_store_builder.rs
  consensus/src/quorum_store/quorum_store_db.rs
  consensus/src/quorum_store/tests/batch_generator_test.rs
  consensus/src/quorum_store/tests/quorum_store_db_test.rs
  consensus/src/twins/twins_node.rs
Labels: CICD:run-e2e-tests

#6946 Improve results capturing, assertions in CLI E2E testing framework
  .github/workflows/cli-e2e-tests.yaml
  crates/aptos/e2e/README.md
  crates/aptos/e2e/cases/account.py
  crates/aptos/e2e/cases/init.py
  crates/aptos/e2e/cases/shared.py
  crates/aptos/e2e/common.py
  crates/aptos/e2e/main.py
  crates/aptos/e2e/poetry.lock
  crates/aptos/e2e/pyproject.toml
  crates/aptos/e2e/test_helpers.py
  crates/aptos/e2e/test_results.py
Labels: CICD:build-images, CICD:run-e2e-tests

#6965 [mempool] eager expiration based on queued transaction age
  config/src/config/mempool_config.rs
  mempool/src/core_mempool/index.rs
  mempool/src/core_mempool/transaction.rs
  mempool/src/core_mempool/transaction_store.rs
  mempool/src/counters.rs
Labels: CICD:run-e2e-tests

#6129 [mempool] Wait until max block size or quorum_store_poll_count is reached
  config/src/config/consensus_config.rs
  consensus/consensus-types/src/request_response.rs
  consensus/src/counters.rs
  consensus/src/epoch_manager.rs
  consensus/src/liveness/proposal_generator.rs
  consensus/src/payload_client.rs
  consensus/src/quorum_store/batch_generator.rs
  consensus/src/quorum_store/direct_mempool_quorum_store.rs
  consensus/src/quorum_store/proof_manager.rs
  consensus/src/quorum_store/tests/batch_generator_test.rs
  consensus/src/quorum_store/tests/direct_mempool_quorum_store_test.rs
  consensus/src/quorum_store/tests/proof_manager_test.rs
  consensus/src/quorum_store/utils.rs
  consensus/src/state_replication.rs
  consensus/src/test_utils/mock_payload_manager.rs
  crates/transaction-emitter-lib/src/emitter/account_minter.rs
  crates/transaction-emitter-lib/src/emitter/mod.rs
  mempool/src/core_mempool/mempool.rs
  mempool/src/shared_mempool/tasks.rs
  mempool/src/shared_mempool/types.rs
  mempool/src/tests/common.rs
  mempool/src/tests/core_mempool_test.rs
  mempool/src/tests/mocks.rs
  mempool/src/tests/multi_node_test.rs
  mempool/src/tests/test_framework.rs
Labels: CICD:run-e2e-tests

#6956 [BlockSTM] Add latency counter for profiling BlockSTM
  aptos-move/block-executor/src/counters.rs
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/scheduler.rs
  execution/executor/src/block_executor.rs
Labels: CICD:run-e2e-tests

#6708 Speculative logging support in Aptos VM
  Cargo.lock
  Cargo.toml
  aptos-move/aptos-vm-logging/Cargo.toml
  aptos-move/aptos-vm-logging/src/counters.rs
  aptos-move/aptos-vm-logging/src/lib.rs
  aptos-move/aptos-vm-logging/src/log_schema.rs
  aptos-move/aptos-vm/Cargo.toml
  aptos-move/aptos-vm/src/adapter_common.rs
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/aptos_vm_impl.rs
  aptos-move/aptos-vm/src/block_executor/mod.rs
  aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs
  aptos-move/aptos-vm/src/counters.rs
  aptos-move/aptos-vm/src/errors.rs
  aptos-move/aptos-vm/src/lib.rs
  aptos-move/block-executor/Cargo.toml
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/proptest_types/types.rs
  aptos-move/block-executor/src/task.rs
  aptos-move/block-executor/src/unit_tests/mod.rs
  aptos-move/block-executor/src/view.rs
  aptos-move/e2e-testsuite/Cargo.toml
  aptos-move/e2e-testsuite/src/tests/failed_transaction_tests.rs
  crates/aptos-speculative-state-helper/src/lib.rs
Labels: CICD:run-e2e-tests

#6785 [quorum store] refactor batch_reader/store and batch requester
  .github/workflows/lint-test.yaml
  consensus/consensus-types/src/proof_of_store.rs
  consensus/src/counters.rs
  consensus/src/epoch_manager.rs
  consensus/src/logging.rs
  consensus/src/network.rs
  consensus/src/network_tests.rs
  consensus/src/payload_manager.rs
  consensus/src/quorum_store/batch_coordinator.rs
  consensus/src/quorum_store/batch_reader.rs
  consensus/src/quorum_store/batch_requester.rs
  consensus/src/quorum_store/batch_store.rs
  consensus/src/quorum_store/counters.rs
  consensus/src/quorum_store/mod.rs
  consensus/src/quorum_store/network_listener.rs
  consensus/src/quorum_store/quorum_store_builder.rs
  consensus/src/quorum_store/quorum_store_coordinator.rs
  consensus/src/quorum_store/quorum_store_db.rs
  consensus/src/quorum_store/tests/batch_reader_test.rs
  consensus/src/quorum_store/tests/batch_requester_test.rs
  consensus/src/quorum_store/tests/batch_store_test.rs
  consensus/src/quorum_store/tests/mod.rs
  consensus/src/quorum_store/tests/proof_coordinator_test.rs
  consensus/src/quorum_store/tests/quorum_store_db_test.rs
  consensus/src/quorum_store/tests/types_test.rs
  consensus/src/quorum_store/types.rs
  consensus/src/round_manager.rs
  consensus/src/test_utils/mock_quorum_store_sender.rs
  consensus/src/twins/basic_twins_test.rs
Labels: CICD:run-e2e-tests, CICD:run-consensus-only-perf-test, CICD:build-consensus-only-image

#6691 [txn emitter] Enable using multiple root-based txn emitter without seq_num issues
  crates/transaction-emitter-lib/src/args.rs
  crates/transaction-emitter-lib/src/emitter/account_minter.rs
  crates/transaction-emitter-lib/src/emitter/mod.rs
  crates/transaction-emitter-lib/src/wrappers.rs
  testsuite/smoke-test/src/txn_emitter.rs
Labels: CICD:build-images

#6969 [Quorum Store] poll mempool at a faster pace to reduce mempool queueing time, except when backpressure
  config/src/config/quorum_store_config.rs
  consensus/src/quorum_store/batch_generator.rs
  consensus/src/quorum_store/counters.rs
  consensus/src/quorum_store/proof_manager.rs
  consensus/src/quorum_store/quorum_store_builder.rs
  consensus/src/quorum_store/tests/proof_manager_test.rs
  consensus/src/quorum_store/utils.rs
Labels: CICD:run-e2e-tests

#6996 [BlockSTM] No eager validation for first execution wave
  aptos-move/block-executor/src/scheduler.rs
  aptos-move/block-executor/src/unit_tests/mod.rs
Labels: CICD:run-e2e-tests

#6792 [Quorum Store][smoketest] non-QS validator in swarm
  consensus/src/epoch_manager.rs
  testsuite/smoke-test/src/consensus/quorum_store_fault_tolerance.rs
Labels: CICD:run-e2e-tests

#7031 [consensus-only] disable consensus-only smoke test in v1.2
  .github/workflows/lint-test.yaml
Labels: CICD:run-e2e-tests

#7033 [Spec] Added the spec for `aptos_std::pool_u64_unbound`
  aptos-move/framework/aptos-framework/doc/delegation_pool.md
  aptos-move/framework/aptos-framework/sources/delegation_pool.spec.move
  aptos-move/framework/aptos-stdlib/doc/pool_u64_unbound.md
  aptos-move/framework/aptos-stdlib/sources/pool_u64_unbound.spec.move
Labels: CICD:run-prover-test

#7018 [Indexer] added nft_points custom contract parsing
  config/src/config/indexer_config.rs
  crates/indexer/migrations/2023-03-08-205402_nft_points/down.sql
  crates/indexer/migrations/2023-03-08-205402_nft_points/up.sql
  crates/indexer/src/models/token_models/mod.rs
  crates/indexer/src/models/token_models/nft_points.rs
  crates/indexer/src/processors/token_processor.rs
  crates/indexer/src/runtime.rs
  crates/indexer/src/schema.rs
Labels: CICD:build-images

#7072 [Consensus] Add monitoring for main loops
  consensus/src/epoch_manager.rs
  consensus/src/experimental/buffer_manager.rs
  consensus/src/network.rs
Labels: CICD:run-e2e-tests

#7071 [consensus] dispatch verify message into executor
  Cargo.lock
  consensus/Cargo.toml
  consensus/src/consensus_provider.rs
  consensus/src/epoch_manager.rs
  consensus/src/experimental/tests/buffer_manager_tests.rs
  consensus/src/network_tests.rs
  consensus/src/round_manager.rs
  consensus/src/twins/twins_node.rs
  crates/channel/src/aptos_channel.rs
Labels: CICD:run-e2e-tests

#7063 [move dependencies] Relax metering during tests
  Cargo.lock
  Cargo.toml
Labels: CICD:run-e2e-tests

#7084 [Config] Add config for API runtime workers.
  Cargo.lock
  api/Cargo.toml
  api/src/runtime.rs
  config/src/config/api_config.rs
Labels: CICD:run-e2e-tests

#7070 [QuorumStore] fix insert/expire issue
  consensus/src/quorum_store/batch_store.rs
  consensus/src/quorum_store/tests/batch_store_test.rs
Labels: CICD:run-e2e-tests

#7058 [Quorum Store] fix backpressure only checking on commits
  config/src/config/quorum_store_config.rs
  consensus/src/epoch_manager.rs
  consensus/src/quorum_store/batch_generator.rs
  consensus/src/quorum_store/proof_manager.rs
  consensus/src/quorum_store/quorum_store_builder.rs
Labels: CICD:run-e2e-tests

#7088 [QS] Add monitoring counters for main loops in quorum store
  consensus/src/quorum_store/batch_generator.rs
  consensus/src/quorum_store/network_listener.rs
  consensus/src/quorum_store/proof_coordinator.rs
  consensus/src/quorum_store/proof_manager.rs
  consensus/src/quorum_store/quorum_store_coordinator.rs
Labels: CICD:run-e2e-tests

#7102 [indexer grpc] fix the re-connection issue and improve the responsiveness of indexing.
  ecosystem/indexer-grpc/indexer-grpc-parser/src/worker.rs
Labels: CICD:build-images

#7069 [move errors] Adapt to new Error variant with message
  Cargo.lock
  Cargo.toml
  aptos-move/aptos-aggregator/src/delta_change_set.rs
  aptos-move/aptos-gas/src/transaction/storage.rs
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/aptos_vm_impl.rs
  aptos-move/aptos-vm/src/errors.rs
  aptos-move/aptos-vm/src/move_vm_ext/session.rs
  aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs
  aptos-move/block-executor/src/view.rs
  aptos-move/e2e-testsuite/src/tests/failed_transaction_tests.rs
  execution/executor/src/mock_vm/mod.rs
  types/src/transaction/multisig.rs
Labels: CICD:run-e2e-tests

#7034 [Block-STM] Scheduler uniform wave treatment & test for number of tasks
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/scheduler.rs
  aptos-move/block-executor/src/unit_tests/mod.rs
Labels: CICD:run-e2e-tests

#7104 Updated the docs to use --network instead of --rest-url
  developer-docs-site/docs/nodes/validator-node/operator/connect-to-aptos-network.md
  developer-docs-site/docs/nodes/validator-node/operator/staking-pool-operations.md
  developer-docs-site/docs/nodes/validator-node/owner/index.md
Labels: documentation

#7109 [indexer parser] Remove obsolete comments and add more logging.
  ecosystem/indexer-grpc/indexer-grpc-parser/src/worker.rs
Labels: CICD:build-images

#7118 Fix faucet build in docker/experimental/build-tools.sh
  docker/experimental/build-tools.sh
  docker/experimental/faucet.Dockerfile
Labels: CICD:experimental-forge, CICD:experimental-build

#7136 [indexer grpc] Actively delete expiring cache entries.
  ecosystem/indexer-grpc/indexer-grpc-utils/src/cache_operator.rs
Labels: CICD:build-images

#7048 [move tutorial] Ports the network agnostic Move tutorial over to Aptos Move
  aptos-move/move-examples/move-tutorial/README.md
  aptos-move/move-examples/move-tutorial/diagrams/move_state.png
  aptos-move/move-examples/move-tutorial/diagrams/solidity_state.png
  aptos-move/move-examples/move-tutorial/step_1/basic_coin/Move.toml
  aptos-move/move-examples/move-tutorial/step_1/basic_coin/sources/first_module.move
  aptos-move/move-examples/move-tutorial/step_2/basic_coin/Move.toml
  aptos-move/move-examples/move-tutorial/step_2/basic_coin/sources/first_module.move
  aptos-move/move-examples/move-tutorial/step_2_sol/basic_coin/Move.toml
  aptos-move/move-examples/move-tutorial/step_2_sol/basic_coin/sources/first_module.move
  aptos-move/move-examples/move-tutorial/step_2_sol/solution_commands
  aptos-move/move-examples/move-tutorial/step_3/basic_coin.move
  aptos-move/move-examples/move-tutorial/step_4/basic_coin/Move.toml
  aptos-move/move-examples/move-tutorial/step_4/basic_coin/sources/basic_coin.move
  aptos-move/move-examples/move-tutorial/step_4_sol/basic_coin/Move.toml
  aptos-move/move-examples/move-tutorial/step_4_sol/basic_coin/sources/basic_coin.move
  aptos-move/move-examples/move-tutorial/step_5/basic_coin/Move.toml
  aptos-move/move-examples/move-tutorial/step_5/basic_coin/sources/basic_coin.move
  aptos-move/move-examples/move-tutorial/step_5_sol/basic_coin/Move.toml
  aptos-move/move-examples/move-tutorial/step_5_sol/basic_coin/sources/basic_coin.move
  aptos-move/move-examples/move-tutorial/step_6/basic_coin/Move.toml
  aptos-move/move-examples/move-tutorial/step_6/basic_coin/sources/basic_coin.move
  aptos-move/move-examples/move-tutorial/step_6/basic_coin/sources/my_odd_coin.move
  aptos-move/move-examples/move-tutorial/step_7/basic_coin/Move.toml
  aptos-move/move-examples/move-tutorial/step_7/basic_coin/sources/basic_coin.move
  aptos-move/move-examples/move-tutorial/step_8/basic_coin/Move.toml
  aptos-move/move-examples/move-tutorial/step_8/basic_coin/sources/basic_coin.move
  aptos-move/move-examples/move-tutorial/step_8_sol/basic_coin/Move.toml
  aptos-move/move-examples/move-tutorial/step_8_sol/basic_coin/sources/basic_coin.move
  aptos-move/move-examples/move-tutorial/test.sh
  crates/aptos/src/move_tool/mod.rs
  crates/aptos/src/test/mod.rs
  developer-docs-site/docs/guides/move-guides/index.md
Labels: CICD:run-e2e-tests

#7165 [Quorum Store] increase default backlog_txn_limit_count
  config/src/config/quorum_store_config.rs
Labels: CICD:run-e2e-tests

#7083 [Config] Add config for API runtime workers.
  Cargo.lock
  api/Cargo.toml
  api/src/runtime.rs
  config/src/config/api_config.rs
Labels: CICD:run-e2e-tests

#7184 [Spec] Fix the broken spec regarding vector and simple_map
  aptos-move/framework/aptos-stdlib/doc/simple_map.md
  aptos-move/framework/aptos-stdlib/sources/simple_map.spec.move
  aptos-move/framework/move-stdlib/doc/vector.md
  aptos-move/framework/move-stdlib/sources/vector.move
Labels: CICD:run-prover-test

#7177 Announce the new PowerShell script and delete the other one to avoid confusion
  developer-docs-site/docs/whats-new-in-docs.md
  scripts/dev_setup.ps1
Labels: documentation

#7169 [Move] Setup copybara for keeping a synchronized copy of Move
  third_party/README.md
  third_party/copy.bara.sky
  third_party/move/language/README.md
Labels: CICD:run-e2e-tests

#7188 [forge][gcp] Fix chaos-mesh daemon config
  terraform/aptos-node-testnet/gcp/addons.tf
Labels: CICD:run-e2e-tests

#7179 [docs] Fix double boxing for checkout commands on getting started
  developer-docs-site/docs/guides/getting-started.md
Labels: documentation

#6344 [Parallel Executor] MVHashMap refactoring to separate data / modules
  Cargo.lock
  aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/output_delta_resolver.rs
  aptos-move/block-executor/src/proptest_types/tests.rs
  aptos-move/block-executor/src/proptest_types/types.rs
  aptos-move/block-executor/src/scheduler.rs
  aptos-move/block-executor/src/task.rs
  aptos-move/block-executor/src/txn_last_input_output.rs
  aptos-move/block-executor/src/unit_tests/mod.rs
  aptos-move/block-executor/src/view.rs
  aptos-move/mvhashmap/Cargo.toml
  aptos-move/mvhashmap/src/lib.rs
  aptos-move/mvhashmap/src/types.rs
  aptos-move/mvhashmap/src/unit_tests/mod.rs
  aptos-move/mvhashmap/src/unit_tests/proptest_types.rs
  aptos-move/mvhashmap/src/versioned_code.rs
  aptos-move/mvhashmap/src/versioned_data.rs
  types/src/executable.rs
  types/src/lib.rs
Labels: CICD:run-e2e-tests

#7194 [Quorum Store] block timestamp-based expiration of batches
  config/src/config/quorum_store_config.rs
  consensus/consensus-types/src/proof_of_store.rs
  consensus/consensus-types/src/request_response.rs
  consensus/src/liveness/proposal_generator.rs
  consensus/src/payload_client.rs
  consensus/src/payload_manager.rs
  consensus/src/quorum_store/batch_coordinator.rs
  consensus/src/quorum_store/batch_generator.rs
  consensus/src/quorum_store/batch_store.rs
  consensus/src/quorum_store/counters.rs
  consensus/src/quorum_store/direct_mempool_quorum_store.rs
  consensus/src/quorum_store/proof_manager.rs
  consensus/src/quorum_store/quorum_store_builder.rs
  consensus/src/quorum_store/quorum_store_coordinator.rs
  consensus/src/quorum_store/tests/batch_store_test.rs
  consensus/src/quorum_store/tests/direct_mempool_quorum_store_test.rs
  consensus/src/quorum_store/tests/proof_coordinator_test.rs
  consensus/src/quorum_store/tests/proof_manager_test.rs
  consensus/src/quorum_store/tests/quorum_store_db_test.rs
  consensus/src/quorum_store/tests/types_test.rs
  consensus/src/quorum_store/types.rs
  consensus/src/quorum_store/utils.rs
  consensus/src/state_computer.rs
  consensus/src/state_replication.rs
  consensus/src/test_utils/mock_payload_manager.rs
  testsuite/generate-format/tests/staged/consensus.yaml
Labels: CICD:run-e2e-tests

#7175 [cherry-pick] PR 7194: [Quorum Store] block timestamp-based expiration of batches
  config/src/config/quorum_store_config.rs
  consensus/consensus-types/src/proof_of_store.rs
  consensus/consensus-types/src/request_response.rs
  consensus/src/liveness/proposal_generator.rs
  consensus/src/payload_client.rs
  consensus/src/payload_manager.rs
  consensus/src/quorum_store/batch_coordinator.rs
  consensus/src/quorum_store/batch_generator.rs
  consensus/src/quorum_store/batch_store.rs
  consensus/src/quorum_store/counters.rs
  consensus/src/quorum_store/direct_mempool_quorum_store.rs
  consensus/src/quorum_store/proof_manager.rs
  consensus/src/quorum_store/quorum_store_builder.rs
  consensus/src/quorum_store/quorum_store_coordinator.rs
  consensus/src/quorum_store/tests/batch_store_test.rs
  consensus/src/quorum_store/tests/direct_mempool_quorum_store_test.rs
  consensus/src/quorum_store/tests/proof_coordinator_test.rs
  consensus/src/quorum_store/tests/proof_manager_test.rs
  consensus/src/quorum_store/tests/quorum_store_db_test.rs
  consensus/src/quorum_store/tests/types_test.rs
  consensus/src/quorum_store/types.rs
  consensus/src/quorum_store/utils.rs
  consensus/src/state_computer.rs
  consensus/src/state_replication.rs
  consensus/src/test_utils/mock_payload_manager.rs
  testsuite/generate-format/tests/staged/consensus.yaml
Labels: CICD:run-e2e-tests

#7238 [Spec] Fixed the broken spec due to a new crypto module
  aptos-move/framework/aptos-stdlib/doc/algebra.md
  aptos-move/framework/aptos-stdlib/sources/cryptography/algebra.spec.move
Labels: CICD:run-prover-test

#7213 more and earlier retries, and better logging in txn emitter
  crates/transaction-emitter-lib/src/emitter/mod.rs
  crates/transaction-emitter-lib/src/emitter/transaction_executor.rs
  crates/transaction-emitter-lib/src/wrappers.rs
Labels: CICD:build-images

#7051 [Spec] Add natives for aggregator and modify specs
  aptos-move/framework/aptos-framework/doc/aggregator.md
  aptos-move/framework/aptos-framework/doc/aggregator_factory.md
  aptos-move/framework/aptos-framework/doc/aptos_governance.md
  aptos-move/framework/aptos-framework/doc/block.md
  aptos-move/framework/aptos-framework/doc/coin.md
  aptos-move/framework/aptos-framework/doc/consensus_config.md
  aptos-move/framework/aptos-framework/doc/gas_schedule.md
  aptos-move/framework/aptos-framework/doc/optional_aggregator.md
  aptos-move/framework/aptos-framework/doc/reconfiguration.md
  aptos-move/framework/aptos-framework/doc/stake.md
  aptos-move/framework/aptos-framework/doc/staking_contract.md
  aptos-move/framework/aptos-framework/doc/transaction_fee.md
  aptos-move/framework/aptos-framework/doc/version.md
  aptos-move/framework/aptos-framework/sources/aggregator/aggregator.spec.move
  aptos-move/framework/aptos-framework/sources/aggregator/aggregator_factory.spec.move
  aptos-move/framework/aptos-framework/sources/aggregator/optional_aggregator.spec.move
  aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
  aptos-move/framework/aptos-framework/sources/block.spec.move
  aptos-move/framework/aptos-framework/sources/coin.move
  aptos-move/framework/aptos-framework/sources/coin.spec.move
  aptos-move/framework/aptos-framework/sources/configs/consensus_config.spec.move
  aptos-move/framework/aptos-framework/sources/configs/gas_schedule.spec.move
  aptos-move/framework/aptos-framework/sources/configs/version.spec.move
  aptos-move/framework/aptos-framework/sources/reconfiguration.spec.move
  aptos-move/framework/aptos-framework/sources/stake.spec.move
  aptos-move/framework/aptos-framework/sources/staking_contract.spec.move
  aptos-move/framework/aptos-framework/sources/transaction_fee.spec.move
  aptos-move/framework/move-stdlib/doc/option.md
  aptos-move/framework/move-stdlib/sources/option.move
  aptos-move/framework/src/aptos-natives.bpl
Labels: CICD:run-prover-test

#7279 [Indexer] Fix string escape in json data for parser only
  ecosystem/indexer-grpc/indexer-grpc-parser/README.md
  ecosystem/indexer-grpc/indexer-grpc-parser/src/models/default_models/transactions.rs
  ecosystem/indexer-grpc/indexer-grpc-parser/src/utils/util.rs
Labels: CICD:build-images

#7273 [API] Expand resource group writeset changes in transactions API
  api/src/context.rs
  api/src/tests/resource_groups.rs
  api/types/src/convert.rs
  api/types/src/lib.rs
  api/types/src/move_types.rs
  aptos-move/aptos-vm/src/natives.rs
Labels: CICD:run-e2e-tests

#7287 Changes from move-language
  third_party/move/documentation/examples/diem-framework/crates/crypto/src/multi_ed25519.rs
  third_party/move/documentation/examples/diem-framework/crates/crypto/src/traits.rs
  third_party/move/documentation/examples/diem-framework/crates/crypto/src/unit_tests/hash_test.rs
  third_party/move/documentation/examples/diem-framework/move-packages/DPN/sources/DiemAccount.move
  third_party/move/documentation/examples/diem-framework/move-packages/core/sources/Account.move
  third_party/move/evm/hardhat-examples/package-lock.json
  third_party/move/evm/hardhat-examples/package.json
  third_party/move/evm/hardhat-examples/test/AsyncEvent.test.js
  third_party/move/move-prover/interpreter/crypto/src/lib.rs
  third_party/move/move-stdlib/docs/fixed_point32.md
  third_party/move/move-stdlib/sources/fixed_point32.move
  third_party/move/tools/move-cli/tests/build_tests/simple_build_with_docs/args.exp
Labels: CICD:run-e2e-tests

#7299 [network] remove rate limiter that based on ip addr
  network/src/protocols/wire/messaging/v1/mod.rs
Labels: CICD:run-e2e-tests

#7300 [Spec] Fix the prover test failure
  aptos-move/framework/aptos-stdlib/doc/fixed_point64.md
  aptos-move/framework/aptos-stdlib/sources/fixed_point64.move
Labels: CICD:run-prover-test

#7236 Raise the visibility of other networks and methods of interaction
  developer-docs-site/docs/guides/get-test-funds.md
  developer-docs-site/docs/guides/local-testnet-dev-flow.md
Labels: documentation

#7290 [Spec] Add spec for transfer_shares and data invariant for Pool in pool_u64_unbound
  aptos-move/framework/aptos-stdlib/doc/pool_u64_unbound.md
  aptos-move/framework/aptos-stdlib/sources/pool_u64_unbound.spec.move
Labels: CICD:run-prover-test

#7225 [Spec] Spec for to_vec_pair and upsert in simple_map
  aptos-move/framework/aptos-stdlib/doc/simple_map.md
  aptos-move/framework/aptos-stdlib/sources/simple_map.spec.move
Labels: CICD:run-prover-test

#6835 [Docs][Tutorials] Update SDKs and your first coin tutorial to use aptos_account::transfer_coins
  developer-docs-site/docs/tutorials/first-coin.md
  ecosystem/python/sdk/aptos_sdk/client.py
  ecosystem/typescript/sdk/examples/typescript/your_coin.ts
  ecosystem/typescript/sdk/src/plugins/coin_client.ts
Labels: release-notes

#7247 Make node config logging a warn
  aptos-node/src/lib.rs
Labels: CICD:run-e2e-tests

#7337 [indexer] change staking contract
  crates/indexer/src/models/stake_models/stake_utils.rs
  ecosystem/indexer-grpc/indexer-grpc-parser/src/models/stake_models/stake_utils.rs
Labels: CICD:build-images

#7144 [Forge] Multi-region simulation test
  .dockerignore
  Cargo.lock
  Cargo.toml
  testsuite/forge-cli/src/main.rs
  testsuite/forge/src/backend/k8s/chaos.rs
  testsuite/forge/src/backend/k8s/chaos/network_bandwidth.yaml
  testsuite/forge/src/backend/k8s/chaos/network_delay.yaml
  testsuite/forge/src/interface/chaos.rs
  testsuite/testcases/Cargo.toml
  testsuite/testcases/src/data/four_region_link_stats.csv
  testsuite/testcases/src/lib.rs
  testsuite/testcases/src/multi_region_simulation_test.rs
  testsuite/testcases/src/network_bandwidth_test.rs
  testsuite/testcases/src/three_region_simulation_test.rs
  testsuite/testcases/src/two_traffics_test.rs
Labels: CICD:run-e2e-tests

#7349 [cherry-pick] consensus improvement for v1.2
  Cargo.lock
  consensus/Cargo.toml
  consensus/src/block_storage/sync_manager.rs
  consensus/src/consensus_provider.rs
  consensus/src/epoch_manager.rs
  consensus/src/experimental/tests/buffer_manager_tests.rs
  consensus/src/network.rs
  consensus/src/network_tests.rs
  consensus/src/round_manager.rs
  consensus/src/twins/twins_node.rs
Labels: CICD:run-e2e-tests

#7348 [Documentation] Update onTaskAdded from E2E Dapp tutorial
  developer-docs-site/docs/tutorials/build-e2e-dapp/6-handle-tasks.md
Labels: documentation

#7358 [Spec] Remove long timeout in specs and add abort to from_vec
  aptos-move/framework/aptos-framework/doc/gas_schedule.md
  aptos-move/framework/aptos-framework/doc/staking_contract.md
  aptos-move/framework/aptos-framework/sources/configs/gas_schedule.spec.move
  aptos-move/framework/aptos-framework/sources/staking_contract.spec.move
  aptos-move/framework/aptos-stdlib/doc/fixed_point64.md
  aptos-move/framework/aptos-stdlib/sources/fixed_point64.move
  aptos-move/framework/move-stdlib/doc/option.md
  aptos-move/framework/move-stdlib/sources/option.move
Labels: CICD:run-prover-test

#7352 [Move prover] Add a boogie implementation for borrow_mut_with_default in the table module
  third_party/move/extensions/move-table-extension/sources/Table.spec.move
  third_party/move/move-model/src/pragmas.rs
  third_party/move/move-prover/boogie-backend/src/lib.rs
  third_party/move/move-prover/boogie-backend/src/prelude/native.bpl
  third_party/move/move-prover/bytecode/src/borrow_analysis.rs
  third_party/move/move-prover/tests/sources/functional/verify_custom_table.exp
  third_party/move/move-prover/tests/sources/functional/verify_custom_table.move
Labels: CICD:run-prover-test

#7369 [Move-prover] Fix a bug on generating code of shift operation for the bv type
  third_party/move/move-prover/boogie-backend/src/bytecode_translator.rs
  third_party/move/move-prover/tests/sources/regression/test_bitvector.move
Labels: CICD:run-prover-test

#7343 [cherry-pick] various improvement for consensus
  Cargo.lock
  consensus/Cargo.toml
  consensus/src/block_storage/block_store_test.rs
  consensus/src/block_storage/sync_manager.rs
  consensus/src/consensus_provider.rs
  consensus/src/epoch_manager.rs
  consensus/src/experimental/tests/buffer_manager_tests.rs
  consensus/src/network.rs
  consensus/src/network_tests.rs
  consensus/src/round_manager.rs
  consensus/src/twins/twins_node.rs
  crates/channel/src/aptos_channel.rs
Labels: CICD:run-e2e-tests

#7384 [preview-cherry-pick of 7383][consensus] Make block retrieval more aggressive
  consensus/consensus-types/src/block_retrieval.rs
  consensus/src/block_storage/sync_manager.rs
  consensus/src/network.rs
Labels: CICD:run-e2e-tests

#7386 [Spec] Add mock specs for fungible contracts
  aptos-move/framework/aptos-framework/doc/fungible_store.md
  aptos-move/framework/aptos-framework/doc/managed_fungible_metadata.md
  aptos-move/framework/aptos-framework/sources/fungible_store.spec.move
  aptos-move/framework/aptos-framework/sources/managed_fungible_metadata.spec.move
Labels: CICD:run-prover-test

#6997 Update specs in directory `aptos-token`
  aptos-move/framework/aptos-token/doc/property_map.md
  aptos-move/framework/aptos-token/doc/token.md
  aptos-move/framework/aptos-token/doc/token_coin_swap.md
  aptos-move/framework/aptos-token/doc/token_event_store.md
  aptos-move/framework/aptos-token/doc/token_transfers.md
  aptos-move/framework/aptos-token/sources/property_map.spec.move
  aptos-move/framework/aptos-token/sources/token.spec.move
  aptos-move/framework/aptos-token/sources/token_coin_swap.spec.move
  aptos-move/framework/aptos-token/sources/token_event_store.spec.move
  aptos-move/framework/aptos-token/sources/token_transfers.spec.move
Labels: CICD:run-prover-test

#7387 [Spec] Add intrinsic spec of borrow_mut_with_default in the table module
  aptos-move/framework/aptos-framework/doc/storage_gas.md
  aptos-move/framework/aptos-framework/sources/storage_gas.spec.move
  aptos-move/framework/aptos-stdlib/doc/table.md
  aptos-move/framework/aptos-stdlib/doc/table_with_length.md
  aptos-move/framework/aptos-stdlib/sources/table.spec.move
  aptos-move/framework/aptos-stdlib/sources/table_with_length.spec.move
Labels: CICD:run-prover-test

#6535 [gas] infrastructure for gas profiling
  Cargo.lock
  Cargo.toml
  aptos-move/aptos-debugger/Cargo.toml
  aptos-move/aptos-debugger/src/lib.rs
  aptos-move/aptos-gas-profiling/Cargo.toml
  aptos-move/aptos-gas-profiling/README.md
  aptos-move/aptos-gas-profiling/src/flamegraph.rs
  aptos-move/aptos-gas-profiling/src/lib.rs
  aptos-move/aptos-gas-profiling/src/log.rs
  aptos-move/aptos-gas-profiling/src/profiler.rs
  aptos-move/aptos-gas/src/gas_meter.rs
  aptos-move/aptos-gas/src/instr.rs
  aptos-move/aptos-gas/src/lib.rs
  aptos-move/aptos-gas/src/transaction/mod.rs
  aptos-move/aptos-gas/src/transaction/storage.rs
  aptos-move/aptos-vm/Cargo.toml
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/e2e-testsuite/src/tests/failed_transaction_tests.rs
  crates/aptos/Cargo.toml
  crates/aptos/src/common/types.rs
  crates/aptos/src/move_tool/mod.rs
Labels: CICD:run-e2e-tests

#7353 [forge] Update base image tag for framework upgrade
  .github/workflows/docker-build-test.yaml
  aptos-move/aptos-release-builder/src/validate.rs
Labels: CICD:run-e2e-tests

#7421 try network configs on previewnet
  config/src/config/network_config.rs
Labels: CICD:run-e2e-tests

#7049 [Dockerfile][Experimental] Caching improvements
  .github/actions/docker-setup/action.yaml
  docker/experimental/build-node.sh
  docker/experimental/build-tools.sh
  docker/experimental/builder.Dockerfile
  docker/experimental/docker-bake-rust-all.hcl
  docker/experimental/docker-bake-rust-all.sh
  docker/experimental/faucet.Dockerfile
  docker/experimental/forge.Dockerfile
  docker/experimental/node-checker.Dockerfile
  docker/experimental/telemetry-service.Dockerfile
  docker/experimental/tools.Dockerfile
Labels: CICD:run-e2e-tests, CICD:experimental-build

#7115 [Spec] update descriptions of TODOs in specs
  aptos-move/framework/aptos-framework/doc/account.md
  aptos-move/framework/aptos-framework/doc/aptos_governance.md
  aptos-move/framework/aptos-framework/doc/coin.md
  aptos-move/framework/aptos-framework/doc/staking_proxy.md
  aptos-move/framework/aptos-framework/sources/account.spec.move
  aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
  aptos-move/framework/aptos-framework/sources/code.spec.move
  aptos-move/framework/aptos-framework/sources/coin.spec.move
  aptos-move/framework/aptos-framework/sources/resource_account.spec.move
  aptos-move/framework/aptos-framework/sources/staking_contract.spec.move
  aptos-move/framework/aptos-framework/sources/staking_proxy.spec.move
  aptos-move/framework/aptos-framework/sources/transaction_fee.spec.move
  aptos-move/framework/aptos-framework/sources/transaction_validation.spec.move
  aptos-move/framework/aptos-framework/sources/vesting.spec.move
Labels: CICD:run-prover-test

#7285 [third_party] Update copybara script and README
  third_party/README.md
  third_party/copy.bara.sky
Labels: CICD:run-e2e-tests

#7296 [Move-prover] Remove ignore annotation from prover tests
  aptos-move/framework/FRAMEWORK-PROVER-GUIDE.md
  aptos-move/framework/tests/move_prover_tests.rs
  aptos-move/move-examples/tests/move_prover_tests.rs
Labels: CICD:run-prover-test

#7466 [TS SDK] Update transferWithOptIn function to use remote abi
  ecosystem/typescript/sdk/src/abis.ts
  ecosystem/typescript/sdk/src/plugins/token_client.ts
  ecosystem/typescript/sdk/src/tests/e2e/indexer.test.ts
  ecosystem/typescript/sdk/src/tests/e2e/provider.test.ts
  ecosystem/typescript/sdk/src/tests/unit/test_helper.test.ts
Labels: sdk

#7492 [docs] Update docs explaining how to use debug statement in Move code
  developer-docs-site/docs/cli-tools/aptos-cli-tool/use-aptos-cli.md
Labels: documentation, team:docs

#7515 [scripts/docker] find latest validator-testing image and push remote
  docker/experimental/docker-bake-rust-all.hcl
  docker/experimental/docker-bake-rust-all.sh
  testsuite/find_latest_image.py
Labels: CICD:build-images

#7407 [aggregator] Aggregator tests clean-up
  Cargo.lock
  aptos-move/aptos-aggregator/Cargo.toml
  aptos-move/aptos-aggregator/src/aggregator_extension.rs
  aptos-move/aptos-aggregator/src/delta_change_set.rs
  aptos-move/e2e-tests/Cargo.toml
  aptos-move/e2e-tests/src/data_store.rs
  aptos-move/framework/src/natives/aggregator_natives/context.rs
Labels: CICD:run-e2e-tests
