Repository aptos-labs/aptos-core, pull requests merged in 2024-12, with the labels that each got.

#15444 trivial: rename ExecutedTrees -> LedgerSummary
  execution/executor/src/block_executor/block_tree/mod.rs
  execution/executor/src/block_executor/block_tree/test.rs
  execution/executor/src/chunk_executor/chunk_commit_queue.rs
  execution/executor/src/db_bootstrapper/mod.rs
  execution/executor/src/tests/mod.rs
  execution/executor/src/workflow/mod.rs
  peer-monitoring-service/server/src/tests.rs
  state-sync/state-sync-driver/src/tests/mocks.rs
  state-sync/storage-service/server/src/tests/mock.rs
  storage/aptosdb/src/db/aptosdb_test.rs
  storage/aptosdb/src/db/fake_aptosdb.rs
  storage/aptosdb/src/db/include/aptosdb_reader.rs
  storage/aptosdb/src/db/mod.rs
  storage/backup/backup-cli/src/utils/test_utils.rs
  storage/db-tool/src/bootstrap.rs
  storage/storage-interface/src/ledger_summary.rs
  storage/storage-interface/src/lib.rs
Labels: CICD:run-e2e-tests

#15443 Updating serialization constant in the API
  api/src/transactions.rs
  api/types/src/move_types.rs
Labels: CICD:run-e2e-tests, v1.24

#15420 Enable Collection Owner feature
  aptos-move/aptos-release-builder/data/collection-owner.yaml
Labels: CICD:run-framework-upgrade-test

#15451 restructure shared state between StateStore and BufferedState
  storage/aptosdb/src/backup/restore_utils.rs
  storage/aptosdb/src/db/include/aptosdb_reader.rs
  storage/aptosdb/src/db/include/aptosdb_writer.rs
  storage/aptosdb/src/state_store/buffered_state.rs
  storage/aptosdb/src/state_store/current_state.rs
  storage/aptosdb/src/state_store/mod.rs
  storage/aptosdb/src/state_store/persisted_state.rs
  storage/aptosdb/src/state_store/state_merkle_batch_committer.rs
  storage/aptosdb/src/state_store/state_snapshot_committer.rs
  storage/scratchpad/src/lib.rs
  storage/scratchpad/src/sparse_merkle/ancestors.rs
  storage/scratchpad/src/sparse_merkle/dropper.rs
  storage/scratchpad/src/sparse_merkle/mod.rs
  types/src/state_store/mod.rs
Labels: CICD:run-e2e-tests

#15425 remove the branch ref to default to github.ref
  .github/workflows/provision-replay-verify-archive-disks.yaml
  .github/workflows/replay-verify-on-archive.yaml
  .github/workflows/workflow-run-replay-verify-archive-storage-provision.yaml
  .github/workflows/workflow-run-replay-verify-on-archive.yaml
  testsuite/replay-verify/main.py
Labels: CICD:build-images

#15446 Script that recalibrates performance benchmarks
  aptos-move/e2e-benchmark/data/calibration_values.tsv
  aptos-move/e2e-benchmark/src/main.rs
  testsuite/forge.py
  testsuite/replay-verify/main.py
  testsuite/single_node_performance.py
  testsuite/single_node_performance_calibration.py
  testsuite/single_node_performance_values.tsv
Labels: CICD:run-execution-performance-test, CICD:run-execution-performance-full-test

#14862 [move-stdlib] Use vector::move_range inside vector, and evaluate performance / calibrate gas
  aptos-move/e2e-benchmark/data/calibration_values.tsv
  aptos-move/e2e-benchmark/src/main.rs
  aptos-move/framework/move-stdlib/doc/features.md
  aptos-move/framework/move-stdlib/doc/vector.md
  aptos-move/framework/move-stdlib/doc/vector_ext.md
  aptos-move/framework/move-stdlib/sources/configs/features.move
  aptos-move/framework/move-stdlib/sources/mem.move
  aptos-move/framework/move-stdlib/sources/vector.move
  aptos-move/framework/move-stdlib/tests/vector_tests.move
  crates/transaction-generator-lib/src/args.rs
  crates/transaction-generator-lib/src/publishing/module_simple.rs
  crates/transaction-generator-lib/src/publishing/raw_module_data.rs
  testsuite/module-publish/src/packages/framework_usecases/sources/vector_example.move
  testsuite/single_node_performance.py
  testsuite/single_node_performance_values.tsv
Labels: CICD:run-execution-performance-test, CICD:run-execution-performance-full-test, CICD:run-framework-upgrade-test

#15501 update schedule and add input checking for replay-verify on archive
  .github/workflows/provision-replay-verify-archive-disks.yaml
  .github/workflows/replay-verify-on-archive.yaml
  .github/workflows/workflow-run-replay-verify-on-archive.yaml
  testsuite/replay-verify/archive_disk_utils.py
  testsuite/replay-verify/main.py
  testsuite/replay-verify/poetry.lock
  testsuite/replay-verify/pyproject.toml
  testsuite/replay-verify/xfs-disk-repair.yaml
Labels: CICD:build-images

#15407 fix flaky test
  storage/aptosdb/src/state_store/state_store_test.rs
Labels: CICD:build-images

#15512 [Inspection Service] Add simple consensus health check endpoint.
  crates/aptos-inspection-service/src/server/index.rs
  crates/aptos-inspection-service/src/server/metrics.rs
  crates/aptos-inspection-service/src/server/mod.rs
  state-sync/state-sync-driver/src/driver.rs
  state-sync/state-sync-driver/src/metrics.rs
Labels: CICD:run-forge-e2e-perf, v1.25

#15525 [Faucet] Support ratelimiting on Firebase JWT
  Cargo.lock
  Cargo.toml
  crates/aptos-faucet/configs/testing_redis.yaml
  crates/aptos-faucet/configs/testing_redis_minter_local.yaml
  crates/aptos-faucet/core/Cargo.toml
  crates/aptos-faucet/core/src/bypasser/auth_token.rs
  crates/aptos-faucet/core/src/checkers/auth_token.rs
  crates/aptos-faucet/core/src/checkers/memory_ratelimit.rs
  crates/aptos-faucet/core/src/checkers/redis_ratelimit.rs
  crates/aptos-faucet/core/src/endpoints/errors.rs
  crates/aptos-faucet/core/src/endpoints/fund.rs
  crates/aptos-faucet/core/src/firebase_jwt.rs
  crates/aptos-faucet/core/src/lib.rs
  crates/aptos-faucet/core/src/server/run.rs
  crates/aptos-faucet/integration-tests/main.py
Labels: CICD:build-images

#15554 Forge: mark pods as non-evictable
  testsuite/forge-test-runner-template.yaml
  testsuite/forge/src/backend/k8s/helm-values/aptos-node-default-values.yaml
Labels: CICD:run-e2e-tests

#15537 [VM][Code cache v2] Some improvements in code cache
  third_party/move/move-vm/runtime/src/loader/modules.rs
  third_party/move/move-vm/runtime/src/loader/script.rs
  third_party/move/move-vm/runtime/src/storage/environment.rs
  third_party/move/move-vm/runtime/src/storage/struct_name_index_map.rs
Labels: CICD:run-execution-performance-test, CICD:run-execution-performance-full-test

#15599 ensure ObjectCore exists before short-circuit
  aptos-move/framework/aptos-framework/doc/object.md
  aptos-move/framework/aptos-framework/sources/object.move
Labels: v1.24

#15591 [forge] Run forge nightly on weekdays
  .github/workflows/forge-stable.yaml
Labels: CICD:run-e2e-tests

#15633 Revert "Bumping up the max transaction execution gas limit for gov proposals"
  aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs
Labels: v1.25

#15638 Lock Rust deps for checking protos
  protos/scripts/install_deps.sh
Labels: CICD:run-e2e-tests

#15640 [Devtools] Disable framework upgrade test
  devtools/aptos-cargo-cli/src/lib.rs
Labels: CICD:run-e2e-tests

#15594 [move] Stateful (de)serialization for function value lookups & delayed fields improvements
  aptos-move/aptos-vm-types/src/module_and_script_storage/state_view_adapter.rs
  aptos-move/aptos-vm-types/src/resolver.rs
  aptos-move/aptos-vm/src/block_executor/mod.rs
  aptos-move/aptos-vm/src/move_vm_ext/session/mod.rs
  aptos-move/block-executor/src/captured_reads.rs
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/limit_processor.rs
  aptos-move/block-executor/src/proptest_types/types.rs
  aptos-move/block-executor/src/task.rs
  aptos-move/block-executor/src/txn_last_input_output.rs
  aptos-move/block-executor/src/types.rs
  aptos-move/block-executor/src/value_exchange.rs
  aptos-move/block-executor/src/view.rs
  aptos-move/framework/move-stdlib/src/natives/bcs.rs
  aptos-move/framework/src/natives/event.rs
  aptos-move/framework/src/natives/util.rs
  aptos-move/framework/table-natives/src/lib.rs
  testsuite/fuzzer/fuzz/fuzz_targets/move/value_deserialize.rs
  third_party/move/extensions/move-table-extension/src/lib.rs
  third_party/move/move-stdlib/src/natives/bcs.rs
  third_party/move/move-vm/integration-tests/src/tests/mod.rs
  third_party/move/move-vm/integration-tests/src/tests/module_storage_tests.rs
  third_party/move/move-vm/runtime/src/data_cache.rs
  third_party/move/move-vm/runtime/src/lib.rs
  third_party/move/move-vm/runtime/src/loader/mod.rs
  third_party/move/move-vm/runtime/src/native_functions.rs
  third_party/move/move-vm/runtime/src/runtime.rs
  third_party/move/move-vm/runtime/src/storage/code_storage.rs
  third_party/move/move-vm/runtime/src/storage/environment.rs
  third_party/move/move-vm/runtime/src/storage/implementations/unsync_code_storage.rs
  third_party/move/move-vm/runtime/src/storage/implementations/unsync_module_storage.rs
  third_party/move/move-vm/runtime/src/storage/loader.rs
  third_party/move/move-vm/runtime/src/storage/module_storage.rs
  third_party/move/move-vm/runtime/src/storage/publishing.rs
  third_party/move/move-vm/types/src/value_serde.rs
  third_party/move/move-vm/types/src/values/serialization_tests.rs
  third_party/move/move-vm/types/src/values/value_prop_tests.rs
  third_party/move/move-vm/types/src/values/values_impl.rs
  third_party/move/testing-infra/transactional-test-runner/src/framework.rs
  third_party/move/tools/move-unit-test/src/extensions.rs
  third_party/move/tools/move-unit-test/src/test_runner.rs
  types/src/transaction/mod.rs
  types/src/transaction/signature_verified_transaction.rs
Labels: CICD:run-e2e-tests

#15540 [CLI] Add `compiler-message-format-json` experiment value to `aptos move compile` and `aptos move lint`
  Cargo.lock
  crates/aptos/src/move_tool/lint.rs
  third_party/move/move-compiler-v2/Cargo.toml
  third_party/move/move-compiler-v2/src/diagnostics/human.rs
  third_party/move/move-compiler-v2/src/diagnostics/json.rs
  third_party/move/move-compiler-v2/src/diagnostics/mod.rs
  third_party/move/move-compiler-v2/src/experiments.rs
  third_party/move/move-compiler-v2/src/lib.rs
  third_party/move/move-compiler-v2/tests/compiler-message-format-json/errors.exp
  third_party/move/move-compiler-v2/tests/compiler-message-format-json/errors.move
  third_party/move/move-compiler-v2/tests/compiler-message-format-json/warnings.exp
  third_party/move/move-compiler-v2/tests/compiler-message-format-json/warnings.move
  third_party/move/move-compiler-v2/tests/testsuite.rs
  third_party/move/move-model/src/model.rs
  third_party/move/testing-infra/transactional-test-runner/src/framework.rs
  third_party/move/tools/move-cli/src/base/test_validation.rs
  third_party/move/tools/move-linter/tests/testsuite.rs
  third_party/move/tools/move-package/src/compilation/compiled_package.rs
Labels: CICD:run-e2e-tests

#15598 Enhancements to replay-verify
  .github/workflows/replay-verify.yaml
  testsuite/replay-verify/README.md
  testsuite/replay-verify/archive_disk_utils.py
  testsuite/replay-verify/main.py
Labels: CICD:build-images
