Repository aptos-labs/aptos-core, pull requests merged in 2024-09, with the labels that each got.

#14482 BufferManager::pending_commit_proofs
  consensus/consensus-types/src/pipeline/commit_decision.rs
  consensus/src/pipeline/buffer_item.rs
  consensus/src/pipeline/buffer_manager.rs
Labels: CICD:run-e2e-tests

#14586 [mempool] improve parking lot eviction
  mempool/src/core_mempool/transaction_store.rs
  mempool/src/counters.rs
  mempool/src/shared_mempool/tasks.rs
  mempool/src/tests/common.rs
  mempool/src/tests/core_mempool_test.rs
  mempool/src/tests/integration_tests.rs
  mempool/src/tests/test_framework.rs
Labels: CICD:run-e2e-tests, v1.19

#13917 [framework] Fungible Asset - Mutable Metadata - Max length checks
  aptos-move/framework/aptos-framework/doc/fungible_asset.md
  aptos-move/framework/aptos-framework/sources/fungible_asset.move
Labels: Stale, move-framework

#14612 [testing] Report unit test results to trunk.io
  .github/actions/rust-unit-tests/action.yaml
  .github/workflows/lint-test.yaml
Labels: CICD:run-all-unit-tests

#14536 [Bugfix] [Compiler-V2] Fix a bug in control flow simplification
  third_party/move/move-compiler-v2/src/pipeline/control_flow_graph_simplifier.rs
  third_party/move/move-compiler-v2/tests/control-flow-simplification/bug-10253.move
  third_party/move/move-compiler-v2/tests/control-flow-simplification/bug-10253.off.exp
  third_party/move/move-compiler-v2/tests/control-flow-simplification/bug-10253.on.exp
  third_party/move/move-compiler-v2/tests/control-flow-simplification/jump-label.move
  third_party/move/move-compiler-v2/tests/control-flow-simplification/jump-label.off.exp
  third_party/move/move-compiler-v2/tests/control-flow-simplification/jump-label.on.exp
  third_party/move/move-compiler-v2/tests/control-flow-simplification/loop.move
  third_party/move/move-compiler-v2/tests/control-flow-simplification/loop.off.exp
  third_party/move/move-compiler-v2/tests/control-flow-simplification/loop.on.exp
  third_party/move/move-compiler-v2/tests/testsuite.rs
Labels: stale-exempt, compiler-v2

#14649 Use internal indexer latest version as latest ledger info
  api/src/accounts.rs
  api/src/context.rs
  api/src/events.rs
  api/src/index.rs
  api/src/transactions.rs
  api/types/src/ledger_info.rs
Labels: CICD:run-e2e-tests

#14637 Sync up QC in order vote message
  consensus/consensus-types/src/wrapped_ledger_info.rs
  consensus/src/counters.rs
  consensus/src/pending_order_votes.rs
  consensus/src/round_manager.rs
Labels: CICD:run-e2e-tests

#14659 Remove an unnecessary clone.
  third_party/move/tools/move-resource-viewer/src/lib.rs
Labels: CICD:build-images

#14570 Cache commit votes received for future rounds in the buffer manager
  config/src/config/consensus_config.rs
  consensus/src/pipeline/buffer_item.rs
  consensus/src/pipeline/buffer_manager.rs
  consensus/src/pipeline/decoupled_execution_utils.rs
  consensus/src/pipeline/execution_client.rs
  consensus/src/pipeline/tests/buffer_manager_tests.rs
Labels: CICD:run-e2e-tests

#14640 Deprecate DelayedQcMsg and simplify the code
  config/src/config/consensus_config.rs
  consensus/consensus-types/src/delayed_qc_msg.rs
  consensus/consensus-types/src/lib.rs
  consensus/src/block_storage/block_store_test.rs
  consensus/src/epoch_manager.rs
  consensus/src/lib.rs
  consensus/src/liveness/round_state.rs
  consensus/src/liveness/round_state_test.rs
  consensus/src/pending_votes.rs
  consensus/src/qc_aggregator.rs
  consensus/src/round_manager.rs
  consensus/src/round_manager_fuzzing.rs
  consensus/src/round_manager_test.rs
Labels: CICD:run-e2e-tests

#14702 Update pin on the Swatinem/rust-cache GH action
  .github/actions/move-prover-setup/action.yaml
  .github/actions/rust-setup/action.yaml
  .github/workflows/windows-build.yaml
Labels: CICD:run-e2e-tests

#14704 [GHA] Update actions/checkout v3 -> v4
  .github/actions/get-latest-docker-image-tag/action.yml
  .github/workflows/aptos-node-release.yaml
  .github/workflows/check-minimum-revision.yaml
  .github/workflows/check-protos.yaml
  .github/workflows/check-sdk-examples.yaml
  .github/workflows/cli-e2e-tests.yaml
  .github/workflows/cli-external-deps.yaml
  .github/workflows/cli-release.yaml
  .github/workflows/codeql-analysis.yaml
  .github/workflows/copy-images-to-dockerhub-nightly.yaml
  .github/workflows/coverage-move-only.yaml
  .github/workflows/coverage.yaml
  .github/workflows/cut-release-branch.yaml
  .github/workflows/docker-build-rosetta.yaml
  .github/workflows/docker-build-test.yaml
  .github/workflows/docker-indexer-grpc-test.yaml
  .github/workflows/faucet-tests-main.yaml
  .github/workflows/faucet-tests-prod.yaml
  .github/workflows/find-packages-with-undeclared-feature-dependencies.yaml
  .github/workflows/forge-pfn.yaml
  .github/workflows/forge-stable.yaml
  .github/workflows/forge-unstable.yaml
  .github/workflows/fullnode-execute-devnet-main.yaml
  .github/workflows/fullnode-execute-devnet-stable.yaml
  .github/workflows/fullnode-fast-mainnet-main.yaml
  .github/workflows/fullnode-fast-mainnet-stable.yaml
  .github/workflows/fullnode-fast-testnet-main.yaml
  .github/workflows/fullnode-fast-testnet-stable.yaml
  .github/workflows/fullnode-intelligent-devnet-main.yaml
  .github/workflows/fullnode-intelligent-mainnet-main.yaml
  .github/workflows/fullnode-intelligent-mainnet-stable.yaml
  .github/workflows/fullnode-intelligent-testnet-main.yaml
  .github/workflows/indexer-grpc-in-memory-cache-benchmark.yaml
  .github/workflows/indexer-grpc-integration-tests.yaml
  .github/workflows/keyless-circuit-daily-test.yaml
  .github/workflows/links.yml
  .github/workflows/move-test-compiler-v2.yaml
  .github/workflows/node-api-compatibility-tests.yaml
  .github/workflows/prover-daily-test.yaml
  .github/workflows/prune-old-workflow-runs.yaml
  .github/workflows/replay-verify.yaml
  .github/workflows/run-fullnode-sync.yaml
  .github/workflows/run-gas-calibration.yaml
  .github/workflows/rust-client-tests.yaml
  .github/workflows/semgrep.yaml
  .github/workflows/test-copy-images-to-dockerhub.yaml
  .github/workflows/ts-sdk-e2e-tests.yaml
  .github/workflows/workflow-run-docker-rust-build.yaml
  .github/workflows/workflow-run-execution-performance.yaml
  .github/workflows/workflow-run-module-verify.yaml
Labels: CICD:run-e2e-tests

#14715 [Fix] Return None instead of error if table info is not available on the node.
  api/types/src/convert.rs
  testsuite/smoke-test/src/indexer.rs
Labels: aptos-release-v1.20

#14721 resolve rust-setup error
  .github/actions/rust-setup/action.yaml
Labels: CICD:test-replay

#14488 [compiler-v2][decompiler] Pulling fat-loop algorithm out of the prover
  third_party/move/move-model/bytecode/Cargo.toml
  third_party/move/move-model/bytecode/src/fat_loop.rs
  third_party/move/move-model/bytecode/src/lib.rs
  third_party/move/move-prover/bytecode-pipeline/src/loop_analysis.rs
Labels: CICD:run-framework-upgrade-test

#14746 [test]
  config/src/config/consensus_observer_config.rs
  consensus/src/consensus_observer/common/metrics.rs
  consensus/src/consensus_observer/network/observer_message.rs
  consensus/src/consensus_observer/observer/consensus_observer.rs
  consensus/src/consensus_observer/observer/payload_store.rs
  consensus/src/consensus_observer/observer/pending_blocks.rs
  consensus/src/epoch_manager.rs
  consensus/src/round_manager.rs
  testsuite/smoke-test/src/consensus_observer.rs
Labels: CICD:run-e2e-tests

#14748 [perf] optimize sort_transactions_with_state_checkpoint
  execution/executor-types/src/parsed_transaction_output.rs
  execution/executor/src/components/apply_chunk_output.rs
  testsuite/single_node_performance.py
Labels: CICD:run-e2e-tests, CICD:run-execution-performance-test, CICD:run-execution-performance-full-test

#14735 [aptos-cli]: update move-tool visibility
  crates/aptos/src/move_tool/mod.rs
Labels: CICD:run-e2e-tests

#14757 [mempool] move the qs callback to be after mempool
  consensus/src/state_computer.rs
Labels: CICD:run-forge-e2e-perf

#14666 [storage] use different metric name for each shard
  storage/aptosdb/src/metrics.rs
  storage/aptosdb/src/rocksdb_property_reporter.rs
Labels: CICD:run-e2e-tests

#14781 [Consensus Observer] Skip expired batches from verification.
  consensus/src/consensus_observer/network/observer_message.rs
Labels: CICD:run-e2e-tests

#14788 [Dev Setup] Pin cargo-machete version
  scripts/dev_setup.sh
  testsuite/smoke-test/Cargo.toml
Labels: CICD:run-e2e-tests
