Repository aptos-labs/aptos-core, pull requests merged in 2024-11, with the labels that each got.

#15143 fix aptos_goverance::CreateProposal event recognition
  Cargo.lock
  aptos-move/aptos-release-builder/Cargo.toml
  aptos-move/aptos-release-builder/src/validate.rs
  crates/aptos/src/governance/mod.rs
  types/src/account_config/events/mod.rs
Labels: CICD:run-e2e-tests, CICD:build-performance-images

#15148 Stop writing down usage at all versions
  storage/aptosdb/src/db/include/aptosdb_writer.rs
  storage/aptosdb/src/db/test_helper.rs
  storage/aptosdb/src/pruner/state_merkle_pruner/test.rs
  storage/aptosdb/src/state_store/mod.rs
  storage/aptosdb/src/state_store/state_store_test.rs
Labels: CICD:run-e2e-tests

#15157 [consensus] record timeout author with reason in metrics
  consensus/src/counters.rs
  consensus/src/round_manager.rs
Labels: v1.23

#15182 Generate new txn for account_transactions processor
  ecosystem/indexer-grpc/indexer-test-transactions/json_transactions/imported_mainnet_txns/423176063_account_transaction_delete.json
  ecosystem/indexer-grpc/indexer-transaction-generator/imported_transactions/imported_transactions.yaml
Labels: CICD:run-e2e-tests

#15159 [forge] increase load of graceful overload
  testsuite/forge-cli/src/suites/realistic_environment.rs
Labels: CICD:build-images, CICD:build-failpoints-images, CICD:build-performance-images

#15226 fix chunk_to_commit.is_reconfig
  execution/executor-types/src/state_compute_result.rs
  storage/aptosdb/src/db/include/aptosdb_testonly.rs
  storage/aptosdb/src/db/include/aptosdb_writer.rs
  types/src/proptest_types.rs
Labels: CICD:run-e2e-tests, v1.23

#15127 Executor benchmark revamps
  api/test-context/src/test_context.rs
  aptos-move/block-executor/src/counters.rs
  aptos-move/block-executor/src/executor.rs
  aptos-move/e2e-benchmark/src/main.rs
  consensus/Cargo.toml
  consensus/src/consensus_provider.rs
  consensus/src/execution_pipeline.rs
  ecosystem/indexer-grpc/indexer-test-transactions/src/lib.rs
  execution/executor-benchmark/src/block_preparation.rs
  execution/executor-benchmark/src/db_generator.rs
  execution/executor-benchmark/src/lib.rs
  execution/executor-benchmark/src/main.rs
  execution/executor-benchmark/src/native/mod.rs
  execution/executor-benchmark/src/native/native_config.rs
  execution/executor-benchmark/src/native_executor.rs
  execution/executor-benchmark/src/pipeline.rs
  execution/executor-benchmark/src/transaction_committer.rs
  execution/executor-benchmark/src/transaction_executor.rs
  execution/executor-test-helpers/src/integration_test_impl.rs
  execution/executor/src/block_executor/mod.rs
  execution/executor/src/fuzzing.rs
  execution/executor/src/metrics.rs
  execution/executor/src/tests/mock_vm/mod.rs
  execution/executor/tests/db_bootstrapper_test.rs
  experimental/execution/ptx-executor/src/lib.rs
  testsuite/single_node_performance.py
Labels: CICD:run-execution-performance-test, CICD:run-execution-performance-full-test

#15137 Merge TransactionBlockExecutor and VMExecutor into VMBlockExecutor
  Cargo.lock
  api/test-context/src/test_context.rs
  aptos-move/aptos-e2e-comparison-testing/src/data_collection.rs
  aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs
  aptos-move/aptos-vm-profiling/src/bins/run_aptos_p2p.rs
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/lib.rs
  aptos-move/aptos-vm/tests/sharded_block_executor.rs
  aptos-node/src/state_sync.rs
  aptos-node/src/storage.rs
  consensus/Cargo.toml
  consensus/src/consensus_provider.rs
  crates/aptos-genesis/src/lib.rs
  crates/aptos-genesis/src/mainnet.rs
  execution/executor-benchmark/src/db_generator.rs
  execution/executor-benchmark/src/ledger_update_stage.rs
  execution/executor-benchmark/src/lib.rs
  execution/executor-benchmark/src/main.rs
  execution/executor-benchmark/src/native_executor.rs
  execution/executor-benchmark/src/pipeline.rs
  execution/executor-benchmark/src/transaction_committer.rs
  execution/executor-benchmark/src/transaction_executor.rs
  execution/executor-service/src/test_utils.rs
  execution/executor-test-helpers/src/integration_test_impl.rs
  execution/executor-test-helpers/src/lib.rs
  execution/executor/src/block_executor/mod.rs
  execution/executor/src/chunk_executor/mod.rs
  execution/executor/src/chunk_executor/transaction_chunk.rs
  execution/executor/src/db_bootstrapper/mod.rs
  execution/executor/src/fuzzing.rs
  execution/executor/src/tests/mock_vm/mock_vm_test.rs
  execution/executor/src/tests/mock_vm/mod.rs
  execution/executor/src/tests/mod.rs
  execution/executor/src/workflow/do_get_execution_output.rs
  execution/executor/tests/db_bootstrapper_test.rs
  experimental/execution/ptx-executor/Cargo.toml
  experimental/execution/ptx-executor/src/lib.rs
  state-sync/inter-component/event-notifications/src/tests.rs
  state-sync/state-sync-driver/src/tests/driver.rs
  state-sync/state-sync-driver/src/tests/driver_factory.rs
  storage/backup/backup-cli/src/backup_types/transaction/restore.rs
  storage/db-tool/src/bootstrap.rs
  storage/db-tool/src/replay_on_archive.rs
  vm-validator/src/unit_tests/vm_validator_test.rs
Labels: CICD:run-execution-performance-test

#14560 [Spec] Prover specification of the function_info module
  aptos-move/framework/aptos-framework/doc/function_info.md
  aptos-move/framework/aptos-framework/sources/function_info.spec.move
Labels: Stale

#15103 Replay Verify scheduler
  storage/backup/backup-cli/src/utils/mod.rs
  storage/db-tool/src/replay_on_archive.rs
  testsuite/replay-verify/README.md
  testsuite/replay-verify/archive_disk_utils.py
  testsuite/replay-verify/main.py
  testsuite/replay-verify/poetry.lock
  testsuite/replay-verify/pyproject.toml
  testsuite/replay-verify/replay-verify-worker-template.yaml
  testsuite/replay-verify/testnet-archive.yaml
  testsuite/replay-verify/xfs-disk-repair.yaml
Labels: CICD:build-performance-images

#15174 [Network] Add metrics for connection operations.
  network/framework/src/application/interface.rs
  network/framework/src/connectivity_manager/mod.rs
  network/framework/src/connectivity_manager/test.rs
  network/framework/src/counters.rs
  network/framework/src/lib.rs
  network/framework/src/peer/mod.rs
  network/framework/src/peer/test.rs
  network/framework/src/peer_manager/mod.rs
  network/framework/src/peer_manager/senders.rs
  network/framework/src/peer_manager/tests.rs
  network/framework/src/peer_manager/types.rs
  network/framework/src/protocols/health_checker/interface.rs
  network/framework/src/protocols/health_checker/mod.rs
  network/framework/src/protocols/health_checker/test.rs
  network/framework/src/protocols/network/mod.rs
Labels: CICD:run-forge-e2e-perf

#15247 [rosetta] Fix staking balances
  crates/aptos-rosetta/src/account.rs
Labels: v1.23

#15065 [indexer grpc] Improve the read consistency for fullnode GRPC.
  ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs
  storage/indexer/src/indexer_reader.rs
  types/src/indexer/indexer_db_reader.rs
Labels: CICD:build-images

#15263 Stop locking BufferedState for read
  Cargo.lock
  storage/aptosdb/Cargo.toml
  storage/aptosdb/src/backup/restore_utils.rs
  storage/aptosdb/src/backup/test.rs
  storage/aptosdb/src/db/aptosdb_test.rs
  storage/aptosdb/src/db/fake_aptosdb.rs
  storage/aptosdb/src/db/include/aptosdb_reader.rs
  storage/aptosdb/src/db/include/aptosdb_testonly.rs
  storage/aptosdb/src/db/include/aptosdb_writer.rs
  storage/aptosdb/src/db/mod.rs
  storage/aptosdb/src/db/test_helper.rs
  storage/aptosdb/src/db_debugger/truncate/mod.rs
  storage/aptosdb/src/ledger_db/ledger_metadata_db.rs
  storage/aptosdb/src/state_store/buffered_state.rs
  storage/aptosdb/src/state_store/mod.rs
  storage/backup/backup-cli/src/utils/test_utils.rs
  storage/storage-interface/src/state_delta.rs
Labels: CICD:run-e2e-tests

#15220 Execution backpressure: reduce target 250 -> 200ms
  config/src/config/consensus_config.rs
Labels: CICD:run-forge-e2e-perf

#15244 increase forge node startup timeout
  testsuite/forge/src/backend/k8s/node.rs
Labels: CICD:run-e2e-tests

#15192 [loader] Global caches for execution
  Cargo.lock
  aptos-move/aptos-debugger/src/aptos_debugger.rs
  aptos-move/aptos-transaction-benchmarks/src/transaction_bench_state.rs
  aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs
  aptos-move/aptos-vm-profiling/src/bins/run_aptos_p2p.rs
  aptos-move/aptos-vm-types/src/module_and_script_storage/state_view_adapter.rs
  aptos-move/aptos-vm/Cargo.toml
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/block_executor/mod.rs
  aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs
  aptos-move/aptos-vm/src/lib.rs
  aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs
  aptos-move/aptos-vm/src/sharded_block_executor/global_executor.rs
  aptos-move/aptos-vm/src/sharded_block_executor/sharded_executor_service.rs
  aptos-move/block-executor/Cargo.toml
  aptos-move/block-executor/src/captured_reads.rs
  aptos-move/block-executor/src/code_cache.rs
  aptos-move/block-executor/src/code_cache_global.rs
  aptos-move/block-executor/src/code_cache_global_manager.rs
  aptos-move/block-executor/src/counters.rs
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/lib.rs
  aptos-move/block-executor/src/proptest_types/bencher.rs
  aptos-move/block-executor/src/proptest_types/tests.rs
  aptos-move/block-executor/src/proptest_types/types.rs
  aptos-move/block-executor/src/task.rs
  aptos-move/block-executor/src/unit_tests/mod.rs
  aptos-move/block-executor/src/view.rs
  aptos-move/e2e-tests/src/executor.rs
  aptos-move/mvhashmap/src/lib.rs
  aptos-move/mvhashmap/src/unsync_map.rs
  execution/executor-benchmark/src/native_executor.rs
  execution/executor/Cargo.toml
  execution/executor/src/block_executor/mod.rs
  execution/executor/src/chunk_executor/mod.rs
  execution/executor/src/chunk_executor/transaction_chunk.rs
  execution/executor/src/db_bootstrapper/mod.rs
  execution/executor/src/fuzzing.rs
  execution/executor/src/tests/mock_vm/mock_vm_test.rs
  execution/executor/src/tests/mock_vm/mod.rs
  execution/executor/src/tests/mod.rs
  execution/executor/src/workflow/do_get_execution_output.rs
  experimental/execution/ptx-executor/src/lib.rs
  third_party/move/move-vm/runtime/src/storage/environment.rs
  third_party/move/move-vm/runtime/src/storage/implementations/unsync_code_storage.rs
  third_party/move/move-vm/runtime/src/storage/implementations/unsync_module_storage.rs
  third_party/move/move-vm/runtime/src/storage/module_storage.rs
  third_party/move/move-vm/types/src/code/cache/module_cache.rs
  third_party/move/move-vm/types/src/code/cache/test_types.rs
  third_party/move/move-vm/types/src/code/cache/types.rs
  third_party/move/move-vm/types/src/code/mod.rs
  types/src/block_executor/config.rs
  types/src/block_executor/execution_state.rs
  types/src/block_executor/mod.rs
  types/src/state_store/mod.rs
Labels: CICD:run-e2e-tests

#14984 [move-stdlib] Implement bcs::constant_serialized_size<T>(): Option<u64>
  Cargo.lock
  aptos-move/aptos-gas-schedule/src/gas_schedule/move_stdlib.rs
  aptos-move/e2e-move-tests/src/tests/transaction_context.data/pack/sources/transaction_context_test.move
  aptos-move/framework/move-stdlib/Cargo.toml
  aptos-move/framework/move-stdlib/doc/bcs.md
  aptos-move/framework/move-stdlib/sources/bcs.move
  aptos-move/framework/move-stdlib/src/natives/bcs.rs
  aptos-move/framework/move-stdlib/tests/bcs_tests.move
  types/src/on_chain_config/aptos_features.rs
Labels: CICD:run-e2e-tests

#15155 [move] Enable V2 loader
  .github/workflows/replay-verify.yaml
  aptos-move/e2e-move-tests/src/tests/code_publishing.rs
  testsuite/single_node_performance.py
  third_party/move/move-vm/runtime/src/config.rs
  types/src/on_chain_config/aptos_features.rs
Labels: CICD:run-e2e-tests

#15120 [cli] Improve span merging in the coverage tool
  third_party/move/tools/move-coverage/src/source_coverage.rs
Labels: CICD:run-e2e-tests

#14568 [BlockSTM] Lazy (potentially iterable) txns input to BlockSTM
  Cargo.lock
  aptos-move/aptos-debugger/src/aptos_debugger.rs
  aptos-move/aptos-e2e-comparison-testing/Cargo.toml
  aptos-move/aptos-e2e-comparison-testing/src/data_collection.rs
  aptos-move/aptos-transaction-benchmarks/src/transaction_bench_state.rs
  aptos-move/aptos-transactional-test-harness/Cargo.toml
  aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs
  aptos-move/aptos-vm-profiling/Cargo.toml
  aptos-move/aptos-vm-profiling/src/bins/run_aptos_p2p.rs
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/block_executor/mod.rs
  aptos-move/aptos-vm/src/lib.rs
  aptos-move/aptos-vm/src/sharded_block_executor/sharded_executor_service.rs
  aptos-move/aptos-vm/tests/sharded_block_executor.rs
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/lib.rs
  aptos-move/block-executor/src/proptest_types/bencher.rs
  aptos-move/block-executor/src/proptest_types/tests.rs
  aptos-move/block-executor/src/txn_provider/blocking_txns_provider.rs
  aptos-move/block-executor/src/txn_provider/default.rs
  aptos-move/block-executor/src/txn_provider/mod.rs
  aptos-move/block-executor/src/unit_tests/mod.rs
  aptos-move/e2e-tests/src/executor.rs
  execution/executor-benchmark/src/native_executor.rs
  execution/executor-service/Cargo.toml
  execution/executor-service/src/test_utils.rs
  execution/executor/Cargo.toml
  execution/executor/src/fuzzing.rs
  execution/executor/src/tests/mock_vm/mock_vm_test.rs
  execution/executor/src/tests/mock_vm/mod.rs
  execution/executor/src/workflow/do_get_execution_output.rs
  experimental/execution/ptx-executor/Cargo.toml
  experimental/execution/ptx-executor/src/lib.rs
  storage/db-tool/Cargo.toml
  storage/db-tool/src/replay_on_archive.rs
Labels: CICD:run-forge-e2e-perf

#15212 [Fuzzing] Add use case aware shuffler fuzzer
  Cargo.lock
  consensus/src/lib.rs
  consensus/src/transaction_shuffler/mod.rs
  consensus/src/transaction_shuffler/use_case_aware/mod.rs
  testsuite/fuzzer/fuzz.sh
  testsuite/fuzzer/fuzz/Cargo.toml
  testsuite/fuzzer/fuzz/fuzz_targets/use_case_aware_shuffler.rs
Labels: CICD:run-e2e-tests

#15228 [docker] use zstd compression and upgrade action
  .github/actions/buildx-setup/action.yml
  docker/builder/docker-bake-rust-all.hcl
Labels: CICD:run-forge-e2e-perf

#15283 panic on state cache miss
  execution/executor/src/types/in_memory_state_calculator_v2.rs
  storage/aptosdb/src/db/test_helper.rs
  storage/aptosdb/src/state_store/mod.rs
Labels: CICD:run-e2e-tests

#15285 [loader-v2] Fixing global cache reads & read-before-write on publish
  aptos-move/aptos-vm-types/src/resolver.rs
  aptos-move/aptos-vm/src/data_cache.rs
  aptos-move/aptos-vm/src/move_vm_ext/resolver.rs
  aptos-move/aptos-vm/src/move_vm_ext/session/view_with_change_set.rs
  aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs
  aptos-move/block-executor/src/captured_reads.rs
  aptos-move/block-executor/src/code_cache.rs
  aptos-move/block-executor/src/view.rs
  aptos-move/e2e-benchmark/src/main.rs
  aptos-move/e2e-move-tests/src/tests/gas.rs
  aptos-move/framework/src/natives/state_storage.rs
  crates/transaction-generator-lib/src/args.rs
  crates/transaction-generator-lib/src/entry_points.rs
  crates/transaction-generator-lib/src/lib.rs
  crates/transaction-generator-lib/src/publishing/module_simple.rs
  crates/transaction-generator-lib/src/publishing/publish_util.rs
  crates/transaction-generator-lib/src/publishing/raw_module_data.rs
  crates/transaction-generator-lib/src/workflow_delegator.rs
  execution/executor-benchmark/src/lib.rs
  testsuite/forge-cli/src/suites/realistic_workloads.rs
  testsuite/module-publish/src/packages/simple/sources/Simple.move
  testsuite/testcases/src/load_vs_perf_benchmark.rs
Labels: CICD:run-e2e-tests, CICD:run-execution-performance-test, CICD:run-execution-performance-full-test

#15303 [docker] use cloudfront debian mirrors for bullseye
  docker/builder/builder.Dockerfile
  docker/builder/debian-base.Dockerfile
  docker/builder/faucet.Dockerfile
  docker/builder/forge.Dockerfile
  docker/builder/indexer-grpc.Dockerfile
  docker/builder/keyless-pepper-service.Dockerfile
  docker/builder/nft-metadata-crawler.Dockerfile
  docker/builder/node-checker.Dockerfile
  docker/builder/telemetry-service.Dockerfile
  docker/builder/tools.Dockerfile
  docker/builder/validator-testing.Dockerfile
  docker/builder/validator.Dockerfile
Labels: CICD:run-e2e-tests

#15311 keyless exebench patch
  crates/transaction-emitter-lib/src/emitter/local_account_generator.rs
  crates/transaction-emitter-lib/src/emitter/mod.rs
  crates/transaction-emitter-lib/src/wrappers.rs
  crates/transaction-emitter/src/diag.rs
  testsuite/smoke-test/src/txn_emitter.rs
  testsuite/testcases/src/lib.rs
Labels: CICD:run-e2e-tests

#15233 exebench for keyless
  aptos-move/vm-genesis/src/lib.rs
  crates/aptos-genesis/src/builder.rs
  crates/aptos-genesis/src/config.rs
  crates/aptos-genesis/src/lib.rs
  crates/aptos-genesis/src/mainnet.rs
  crates/aptos/src/genesis/mod.rs
  crates/transaction-emitter-lib/src/emitter/local_account_generator.rs
  crates/transaction-emitter-lib/src/emitter/mod.rs
  crates/transaction-emitter-lib/src/wrappers.rs
  crates/transaction-emitter/src/diag.rs
  execution/executor-benchmark/src/account_generator.rs
  execution/executor-benchmark/src/db_generator.rs
  execution/executor-benchmark/src/lib.rs
  execution/executor-benchmark/src/main.rs
  execution/executor-benchmark/src/transaction_generator.rs
  sdk/Cargo.toml
  sdk/src/types.rs
  testsuite/smoke-test/src/keyless.rs
  testsuite/smoke-test/src/txn_emitter.rs
  testsuite/testcases/src/lib.rs
  types/src/jwks/patch/mod.rs
  types/src/keyless/bn254_circom.rs
  types/src/keyless/circuit_constants.rs
  types/src/keyless/circuit_testcases.rs
  types/src/keyless/configuration.rs
  types/src/keyless/mod.rs
  types/src/keyless/test_utils.rs
Labels: CICD:run-e2e-tests

#15319 Cherrypick #280 (#282) (#15258)
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/e2e-move-tests/src/tests/mod.rs
  aptos-move/e2e-move-tests/src/tests/upgrade_compatibility.rs
  third_party/move/move-binary-format/src/compatibility.rs
  third_party/move/move-binary-format/src/compatibility_legacy.rs
  third_party/move/testing-infra/transactional-test-runner/src/vm_test_harness.rs
  types/src/on_chain_config/timed_features.rs
Labels: 1.24

#15291 fix flaky test_db_restart
  consensus/src/transaction_shuffler/use_case_aware/mod.rs
  crates/aptos-rest-client/src/lib.rs
  testsuite/forge/src/interface/aptos.rs
  testsuite/smoke-test/src/storage.rs
Labels: CICD:run-e2e-tests

#15320 [Consensus Observer] Add simple sync lag fallback
  config/src/config/consensus_observer_config.rs
  consensus/src/consensus_observer/common/error.rs
  consensus/src/consensus_observer/observer/fallback_manager.rs
Labels: CICD:run-forge-e2e-perf, v1.24

#15316 [loader-v2] Addressing simple loader V2 TODOs
  aptos-move/block-executor/src/code_cache_global_manager.rs
  third_party/move/move-vm/integration-tests/src/tests/bad_storage_tests.rs
  third_party/move/move-vm/runtime/src/loader/mod.rs
  third_party/move/move-vm/runtime/src/storage/loader.rs
  third_party/move/move-vm/transactional-tests/tests/entry_points/script_too_few_type_args_inner.exp
  third_party/move/move-vm/transactional-tests/tests/entry_points/script_too_few_type_args_inner.v2_exp
  third_party/move/move-vm/transactional-tests/tests/entry_points/script_too_many_type_args_inner.exp
  third_party/move/move-vm/transactional-tests/tests/entry_points/script_too_many_type_args_inner.v2_exp
  third_party/move/move-vm/types/src/code/errors.rs
Labels: CICD:run-e2e-tests

#15361 Move payload_manager.notify_commit to after commit
  consensus/src/pipeline/pipeline_builder.rs
  consensus/src/state_computer.rs
Labels: CICD:run-e2e-tests

#15359 [cp 1.23] Move payload_manager.notify_commit() to after commit
  consensus/src/state_computer.rs
Labels: CICD:run-e2e-tests

#15372 revert back backpressure change until execution pool
  config/src/config/consensus_config.rs
Labels: v1.24

#15364 [consensus] sync improvements to help slow nodes sync better
  consensus/src/block_storage/sync_manager.rs
  consensus/src/quorum_store/batch_store.rs
  consensus/src/quorum_store/quorum_store_builder.rs
  consensus/src/quorum_store/tests/batch_store_test.rs
  testsuite/forge-cli/src/suites/realistic_environment.rs
Labels: CICD:run-forge-e2e-perf, v1.23, v1.24

#15152 Various variants of "simplified/dummy" executors
  .github/workflows/workflow-run-execution-performance.yaml
  Cargo.lock
  aptos-move/aptos-aggregator/src/resolver.rs
  aptos-move/aptos-debugger/src/aptos_debugger.rs
  aptos-move/aptos-transaction-benchmarks/src/transaction_bench_state.rs
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/block_executor/mod.rs
  aptos-move/aptos-vm/src/block_executor/vm_wrapper.rs
  aptos-move/aptos-vm/src/lib.rs
  aptos-move/aptos-vm/src/sharded_block_executor/sharded_executor_service.rs
  aptos-move/e2e-tests/src/executor.rs
  execution/executor-benchmark/Cargo.toml
  execution/executor-benchmark/src/db_access.rs
  execution/executor-benchmark/src/db_reliable_submitter.rs
  execution/executor-benchmark/src/lib.rs
  execution/executor-benchmark/src/main.rs
  execution/executor-benchmark/src/native/aptos_vm_uncoordinated.rs
  execution/executor-benchmark/src/native/mod.rs
  execution/executor-benchmark/src/native/native_transaction.rs
  execution/executor-benchmark/src/native/native_vm.rs
  execution/executor-benchmark/src/native/parallel_uncoordinated_block_executor.rs
  execution/executor-benchmark/src/native_executor.rs
  execution/executor-benchmark/src/pipeline.rs
  testsuite/single_node_performance.py
  types/src/account_config/resources/coin_store.rs
  types/src/account_config/resources/core_account.rs
Labels: CICD:run-execution-performance-test, CICD:run-execution-performance-full-test

#15352 Bumping up the max transaction execution gas limit for gov proposals
  aptos-move/aptos-gas-schedule/src/gas_schedule/transaction.rs
Labels: v1.23

#15391 Fix units in timed feature flags
  aptos-move/aptos-vm-environment/src/environment.rs
  crates/aptos/src/node/mod.rs
  types/src/on_chain_config/mod.rs
  types/src/on_chain_config/timed_features.rs
Labels: v1.24

#15272 Add replay verify on archive related workflows
  .github/workflows/provision-replay-verify-archive-disks.yaml
  .github/workflows/replay-verify-on-archive.yaml
  .github/workflows/workflow-run-replay-verify-archive-storage-provision.yaml
  .github/workflows/workflow-run-replay-verify-on-archive.yaml
  storage/db-tool/src/replay_on_archive.rs
  testsuite/replay-verify/__init__.py
  testsuite/replay-verify/archive-pvc-template.yaml
  testsuite/replay-verify/archive-snapshot-template.yaml
  testsuite/replay-verify/archive_disk_utils.py
  testsuite/replay-verify/main.py
  testsuite/replay-verify/poetry.lock
  testsuite/replay-verify/pyproject.toml
  testsuite/replay-verify/replay-verify-worker-template.yaml
  testsuite/replay-verify/testnet-archive.yaml
  testsuite/replay-verify/xfs-disk-repair.yaml
Labels: CICD:build-images, CICD:build-performance-images

#15401 update qs key loading
  Cargo.lock
  consensus/Cargo.toml
  consensus/safety-rules/src/persistent_safety_storage.rs
  consensus/src/consensus_observer/observer/consensus_observer.rs
  consensus/src/epoch_manager.rs
  consensus/src/pipeline/execution_client.rs
  consensus/src/quorum_store/quorum_store_builder.rs
  consensus/src/test_utils/mock_execution_client.rs
Labels: CICD:run-e2e-tests

#15350 Refactoring interpreter and paranoid mode, introducing traits to allo…
  third_party/move/move-vm/runtime/src/debug.rs
  third_party/move/move-vm/runtime/src/frame_type_cache.rs
  third_party/move/move-vm/runtime/src/interpreter.rs
  third_party/move/move-vm/runtime/src/lib.rs
  third_party/move/move-vm/runtime/src/native_functions.rs
  third_party/move/move-vm/runtime/src/runtime_type_checks.rs
  third_party/move/move-vm/runtime/src/tracing.rs
Labels: CICD:run-e2e-tests, CICD:test-replay

#15410 [NFT Metadata Crawler] Fix asset uploader throttler
  ecosystem/nft-metadata-crawler/src/asset_uploader/throttler/mod.rs
Labels: CICD:build-images
