Repository aptos-labs/aptos-core, pull requests merged in 2024-01, with the labels that each got.

#11424 [State Sync] Update the optimistic fetch handler to handle check-to-use race.
  state-sync/storage-service/server/src/optimistic_fetch.rs
  state-sync/storage-service/server/src/tests/optimistic_fetch.rs
Labels: CICD:run-e2e-tests, CICD:run-forge-e2e-perf

#11345 Make pipeline backpressure more aggressive
  config/src/config/consensus_config.rs
  consensus/src/counters.rs
  consensus/src/round_manager.rs
Labels: CICD:run-forge-e2e-perf

#11137 [dep] upgrade serde, serde-reflection and related deps
  Cargo.lock
  Cargo.toml
  api/doc/spec.yaml
  api/src/tests/transaction_vector_test.rs
  aptos-move/e2e-move-tests/src/tests/aggregator.rs
  aptos-move/e2e-move-tests/src/tests/aggregator_v2.rs
  crates/aptos/Cargo.toml
  crates/aptos/src/node/local_testnet/processors.rs
  testsuite/generate-format/src/api.rs
  testsuite/generate-format/src/aptos.rs
  testsuite/generate-format/src/consensus.rs
  testsuite/generate-format/src/move_abi.rs
  third_party/move/tools/move-bytecode-utils/Cargo.toml
Labels: CICD:run-forge-e2e-perf

#11558 update additional vm checks
  config/src/config/execution_config.rs
Labels: CICD:run-e2e-tests

#11523 block limits in release.yaml for 1.9
  aptos-move/aptos-release-builder/data/release.yaml
Labels: CICD:run-e2e-tests

#11372 jwks.move
  aptos-move/framework/aptos-framework/doc/jwks.md
  aptos-move/framework/aptos-framework/doc/overview.md
  aptos-move/framework/aptos-framework/sources/jwks.move
Labels: CICD:run-e2e-tests

#11576 [Quorum Store] fix counters
  consensus/src/quorum_store/proof_coordinator.rs
Labels: CICD:run-e2e-tests

#11578 [cherry-pick] [Quorum Store] fix counters
  consensus/src/quorum_store/proof_coordinator.rs
Labels: CICD:run-e2e-tests

#11470 [indexer grpc] compression support.
  Cargo.lock
  ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/lib.rs
  ecosystem/indexer-grpc/indexer-grpc-cache-worker/src/worker.rs
  ecosystem/indexer-grpc/indexer-grpc-data-service/src/config.rs
  ecosystem/indexer-grpc/indexer-grpc-data-service/src/service.rs
  ecosystem/indexer-grpc/indexer-grpc-file-store/src/lib.rs
  ecosystem/indexer-grpc/indexer-grpc-file-store/src/processor.rs
  ecosystem/indexer-grpc/indexer-grpc-utils/Cargo.toml
  ecosystem/indexer-grpc/indexer-grpc-utils/src/cache_operator.rs
  ecosystem/indexer-grpc/indexer-grpc-utils/src/compression_util.rs
  ecosystem/indexer-grpc/indexer-grpc-utils/src/config.rs
  ecosystem/indexer-grpc/indexer-grpc-utils/src/constants.rs
  ecosystem/indexer-grpc/indexer-grpc-utils/src/counters.rs
  ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator/gcs.rs
  ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator/local.rs
  ecosystem/indexer-grpc/indexer-grpc-utils/src/file_store_operator/mod.rs
  ecosystem/indexer-grpc/indexer-grpc-utils/src/lib.rs
  protos/proto/aptos/indexer/v1/raw_data.proto
  protos/python/aptos_protos/aptos/indexer/v1/raw_data_pb2.py
  protos/python/aptos_protos/aptos/indexer/v1/raw_data_pb2.pyi
  protos/rust/src/pb/aptos.indexer.v1.rs
  protos/rust/src/pb/aptos.indexer.v1.serde.rs
  protos/typescript/src/aptos/indexer/v1/raw_data.ts
Labels: CICD:build-images

#11588 DKG skeleton (continued)
  Cargo.lock
  aptos-move/aptos-release-builder/src/components/feature_flags.rs
  aptos-move/vm-genesis/src/lib.rs
  aptos-node/src/lib.rs
  aptos-node/src/network.rs
  dkg/Cargo.toml
  dkg/src/counters.rs
  dkg/src/dkg_manager/agg_node_producer.rs
  dkg/src/dkg_manager/mod.rs
  dkg/src/epoch_manager.rs
  dkg/src/lib.rs
  dkg/src/network.rs
  dkg/src/network_interface.rs
  dkg/src/types.rs
  types/src/dkg.rs
  types/src/lib.rs
  types/src/on_chain_config/aptos_features.rs
Labels: CICD:run-e2e-tests

#11604 [Cargo] Bump mini-moka to 0.10.3
  Cargo.lock
  Cargo.toml
Labels: CICD:run-e2e-tests

#11533 [move][vm] Use PartialVMError for Move resolvers
  api/src/context.rs
  api/src/tests/converter_test.rs
  api/types/src/convert.rs
  aptos-move/aptos-resource-viewer/src/lib.rs
  aptos-move/aptos-vm/src/data_cache.rs
  aptos-move/aptos-vm/src/move_vm_ext/resolver.rs
  aptos-move/aptos-vm/src/natives.rs
  aptos-move/aptos-vm/src/tests/mock_view.rs
  aptos-move/framework/table-natives/src/lib.rs
  storage/indexer/src/db_v2.rs
  storage/indexer/src/lib.rs
  third_party/move/extensions/async/move-async-vm/src/async_vm.rs
  third_party/move/extensions/async/move-async-vm/tests/testsuite.rs
  third_party/move/extensions/move-table-extension/src/lib.rs
  third_party/move/move-core/types/src/resolver.rs
  third_party/move/move-vm/integration-tests/src/tests/bad_storage_tests.rs
  third_party/move/move-vm/integration-tests/src/tests/mod.rs
  third_party/move/move-vm/integration-tests/src/tests/vm_arguments_tests.rs
  third_party/move/move-vm/runtime/src/data_cache.rs
  third_party/move/move-vm/runtime/src/interpreter.rs
  third_party/move/move-vm/runtime/src/lib.rs
  third_party/move/move-vm/runtime/src/move_vm.rs
  third_party/move/move-vm/runtime/src/unit_tests/mod.rs
  third_party/move/move-vm/test-utils/src/storage.rs
  third_party/move/move-vm/types/src/lib.rs
  third_party/move/testing-infra/test-generation/Cargo.toml
  third_party/move/testing-infra/test-generation/src/lib.rs
  third_party/move/testing-infra/transactional-test-runner/src/tasks.rs
  third_party/move/testing-infra/transactional-test-runner/src/vm_test_harness.rs
  third_party/move/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs
  third_party/move/tools/move-resource-viewer/src/lib.rs
  third_party/move/tools/move-resource-viewer/src/resolver.rs
Labels: CICD:run-e2e-tests

#11590 load dkg sk
  aptos-node/src/lib.rs
  config/src/config/safety_rules_config.rs
  consensus/safety-rules/src/safety_rules_manager.rs
  dkg/src/dkg_manager/mod.rs
  dkg/src/epoch_manager.rs
  dkg/src/lib.rs
Labels: CICD:run-e2e-tests

#11591 dkg trait and transcript aggregation
  Cargo.lock
  dkg/Cargo.toml
  dkg/src/dkg_manager/agg_node_producer.rs
  dkg/src/dkg_manager/agg_trx_producer.rs
  dkg/src/dkg_manager/mod.rs
  dkg/src/dummy_dkg.rs
  dkg/src/epoch_manager.rs
  dkg/src/lib.rs
  dkg/src/transcript_aggregation.rs
  dkg/src/types.rs
  types/src/dkg.rs
Labels: CICD:run-e2e-tests

#11642 JWK consensus all in one
  Cargo.lock
  aptos-move/aptos-release-builder/src/components/feature_flags.rs
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/move_vm_ext/session.rs
  aptos-move/aptos-vm/src/system_module_names.rs
  aptos-move/framework/move-stdlib/doc/features.md
  aptos-move/framework/move-stdlib/sources/configs/features.move
  aptos-move/vm-genesis/src/lib.rs
  aptos-node/src/lib.rs
  aptos-node/src/state_sync.rs
  crates/aptos-jwk-consensus/Cargo.toml
  crates/aptos-jwk-consensus/src/certified_update_producer.rs
  crates/aptos-jwk-consensus/src/counters.rs
  crates/aptos-jwk-consensus/src/epoch_manager.rs
  crates/aptos-jwk-consensus/src/jwk_manager/certified_update_producer.rs
  crates/aptos-jwk-consensus/src/jwk_manager/mod.rs
  crates/aptos-jwk-consensus/src/jwk_manager/tests.rs
  crates/aptos-jwk-consensus/src/jwk_observer.rs
  crates/aptos-jwk-consensus/src/lib.rs
  crates/aptos-jwk-consensus/src/network.rs
  crates/aptos-jwk-consensus/src/network_interface.rs
  crates/aptos-jwk-consensus/src/observation_aggregation/mod.rs
  crates/aptos-jwk-consensus/src/observation_aggregation/tests.rs
  crates/aptos-jwk-consensus/src/signing_key_provider.rs
  crates/aptos-jwk-consensus/src/types.rs
  execution/executor-types/src/lib.rs
  testsuite/forge/src/backend/local/cargo.rs
  testsuite/smoke-test/Cargo.toml
  testsuite/smoke-test/src/jwks/dummy_provider/mod.rs
  testsuite/smoke-test/src/jwks/dummy_provider/request_handler.rs
  testsuite/smoke-test/src/jwks/jwk_consensus_basic.rs
  testsuite/smoke-test/src/jwks/jwk_consensus_per_issuer.rs
  testsuite/smoke-test/src/jwks/jwk_consensus_provider_change_mind.rs
  testsuite/smoke-test/src/jwks/mod.rs
  types/src/contract_event.rs
  types/src/jwks/jwk/mod.rs
  types/src/jwks/jwk/tests.rs
  types/src/jwks/mod.rs
  types/src/jwks/rsa/mod.rs
  types/src/jwks/rsa/tests.rs
  types/src/jwks/unsupported.rs
  types/src/jwks/unsupported/mod.rs
  types/src/jwks/unsupported/tests.rs
  types/src/move_any.rs
  types/src/on_chain_config/aptos_features.rs
  types/src/validator_txn.rs
Labels: CICD:run-e2e-tests

#11593 [move][vm][block-stm] Fix error types for resolvers
  Cargo.lock
  aptos-move/aptos-aggregator/src/delayed_field_extension.rs
  aptos-move/aptos-aggregator/src/delta_change_set.rs
  aptos-move/aptos-aggregator/src/resolver.rs
  aptos-move/aptos-aggregator/src/tests/types.rs
  aptos-move/aptos-vm-types/src/change_set.rs
  aptos-move/aptos-vm-types/src/resolver.rs
  aptos-move/aptos-vm-types/src/resource_group_adapter.rs
  aptos-move/aptos-vm-types/src/tests/test_change_set.rs
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/data_cache.rs
  aptos-move/aptos-vm/src/errors.rs
  aptos-move/aptos-vm/src/move_vm_ext/mod.rs
  aptos-move/aptos-vm/src/move_vm_ext/resolver.rs
  aptos-move/aptos-vm/src/move_vm_ext/respawned_session.rs
  aptos-move/aptos-vm/src/move_vm_ext/session.rs
  aptos-move/aptos-vm/src/move_vm_ext/write_op_converter.rs
  aptos-move/aptos-vm/src/natives.rs
  aptos-move/aptos-vm/src/system_module_names.rs
  aptos-move/block-executor/src/captured_reads.rs
  aptos-move/block-executor/src/view.rs
  aptos-move/e2e-move-tests/src/tests/access_path_test.rs
  aptos-move/mvhashmap/Cargo.toml
  aptos-move/mvhashmap/src/types.rs
  aptos-move/mvhashmap/src/unsync_map.rs
  aptos-move/mvhashmap/src/versioned_group_data.rs
  third_party/move/move-binary-format/src/errors.rs
  third_party/move/move-vm/runtime/src/runtime.rs
  types/src/access_path.rs
Labels: CICD:run-e2e-tests

#10532 [event v2] double emitting in account, coin, fungible asset and object and migrate move-examples
  aptos-move/framework/aptos-framework/doc/account.md
  aptos-move/framework/aptos-framework/doc/aptos_account.md
  aptos-move/framework/aptos-framework/doc/coin.md
  aptos-move/framework/aptos-framework/doc/fungible_asset.md
  aptos-move/framework/aptos-framework/doc/object.md
  aptos-move/framework/aptos-framework/sources/account.move
  aptos-move/framework/aptos-framework/sources/aptos_account.move
  aptos-move/framework/aptos-framework/sources/coin.move
  aptos-move/framework/aptos-framework/sources/fungible_asset.move
  aptos-move/framework/aptos-framework/sources/object.move
  crates/aptos-rosetta/src/types/objects.rs
  crates/indexer/src/models/transactions.rs
  execution/executor-test-helpers/src/integration_test_impl.rs
Labels: CICD:run-e2e-tests

#11659 vtxn pool as a queue
  Cargo.lock
  aptos-node/src/lib.rs
  aptos-node/src/services.rs
  consensus/src/consensus_provider.rs
  consensus/src/epoch_manager.rs
  consensus/src/payload_client/mixed.rs
  consensus/src/payload_client/validator.rs
  consensus/src/twins/twins_node.rs
  crates/aptos-jwk-consensus/src/lib.rs
  crates/validator-transaction-pool/Cargo.toml
  crates/validator-transaction-pool/src/lib.rs
  crates/validator-transaction-pool/src/tests.rs
  dkg/src/dkg_manager/mod.rs
  dkg/src/epoch_manager.rs
  dkg/src/lib.rs
  types/src/validator_txn.rs
Labels: CICD:run-e2e-tests, DKG, JWK

#11678 Fuzzer Build Revamp
  testsuite/fuzzer/.cargo/config.toml
  testsuite/fuzzer/README.md
  testsuite/fuzzer/fuzz.sh
  testsuite/fuzzer/google-oss-fuzz/build.sh
  testsuite/fuzzer/google-oss-fuzz/project.yaml
  testsuite/fuzzer/repro.sh
  testsuite/fuzzer/test-fuzzers.sh
Labels: tooling

#11675 Sort move-model (and move-compiler-v2) diagnostics by location
  third_party/move/evm/move-to-yul/tests/TestABINativeError.exp
  third_party/move/evm/move-to-yul/tests/fallback-receive-test/expect-failure/FallbackReciveFailure.exp
  third_party/move/evm/move-to-yul/tests/test-dispatcher/ExternalCallFailure.exp
  third_party/move/evm/move-to-yul/tests/test-dispatcher/signature-parsing-test/baseline/parsing_failure/IllegalDataLocation.exp
  third_party/move/evm/move-to-yul/tests/test-dispatcher/signature-parsing-test/baseline/parsing_failure/IllegalFunctionName.exp
  third_party/move/evm/move-to-yul/tests/test-dispatcher/signature-parsing-test/baseline/parsing_failure/IllegalTypeList.exp
  third_party/move/evm/move-to-yul/tests/test-dispatcher/signature-parsing-test/baseline/parsing_failure/IncompatibileType.exp
  third_party/move/evm/move-to-yul/tests/test-events/compilation_failure/ParsingEventSigFailure.exp
  third_party/move/move-compiler-v2/tests/ability-checker/ability_violation.exp
  third_party/move/move-compiler-v2/tests/ability-checker/invalid_struct_def.exp
  third_party/move/move-compiler-v2/tests/checking/inlining/break_continue_in_lambda.exp
  third_party/move/move-compiler-v2/tests/checking/inlining/private_call_3.exp
  third_party/move/move-compiler-v2/tests/checking/naming/duplicate_type_parameter_struct.exp
  third_party/move/move-compiler-v2/tests/checking/naming/generics_with_type_parameters.exp
  third_party/move/move-compiler-v2/tests/checking/naming/unbound_struct_in_current.exp
  third_party/move/move-compiler-v2/tests/checking/naming/unresolved_type_no_args.exp
  third_party/move/move-compiler-v2/tests/checking/naming/unresolved_type_with_args.exp
  third_party/move/move-compiler-v2/tests/checking/specs/schemas_err.exp
  third_party/move/move-compiler-v2/tests/checking/typing/bad_type_argument_arity_const.exp
  third_party/move/move-compiler-v2/tests/checking/typing/bad_type_argument_arity_struct.exp
  third_party/move/move-compiler-v2/tests/checking/typing/bind_wrong_type.exp
  third_party/move/move-compiler-v2/tests/checking/typing/constant_invalid_base_type.exp
  third_party/move/move-compiler-v2/tests/checking/typing/constant_non_base_type.exp
  third_party/move/move-compiler-v2/tests/checking/typing/instantiate_signatures.exp
  third_party/move/move-compiler-v2/tests/checking/typing/lambda.exp
  third_party/move/move-compiler-v2/tests/checking/typing/native_structs_pack_unpack.exp
  third_party/move/move-compiler-v2/tests/checking/typing/other_builtins_invalid.exp
  third_party/move/move-compiler-v2/tests/checking/typing/pack_invalid_argument.exp
  third_party/move/move-compiler-v2/tests/checking/unused/private_call_3.exp
  third_party/move/move-compiler-v2/tests/explicit-drop/unused_var.exp
  third_party/move/move-compiler-v2/tests/folding/bad_type_argument_arity_const.exp
  third_party/move/move-compiler-v2/tests/folding/constants_blocks.exp
  third_party/move/move-compiler-v2/tests/folding/unfoldable_constants.exp
  third_party/move/move-compiler-v2/tests/live-var/explicit_move.exp
  third_party/move/move-compiler-v2/tests/reference-safety/v1-tests/return_borrowed_local_invalid.exp
  third_party/move/move-compiler-v2/tests/visibility-checker/constant_use_across_mod.exp
  third_party/move/move-model/src/model.rs
  third_party/move/move-model/tests/sources/schemas_err.exp
  third_party/move/move-prover/tests/sources/functional/ModifiesErrorTest.exp
  third_party/move/move-prover/tests/sources/functional/aborts_if.exp
  third_party/move/move-prover/tests/sources/functional/aborts_if_with_code.exp
  third_party/move/move-prover/tests/sources/functional/arithm.exp
  third_party/move/move-prover/tests/sources/functional/cast.exp
  third_party/move/move-prover/tests/sources/functional/choice.exp
  third_party/move/move-prover/tests/sources/functional/consts.exp
  third_party/move/move-prover/tests/sources/functional/emits.exp
  third_party/move/move-prover/tests/sources/functional/fixed_point_arithm.exp
  third_party/move/move-prover/tests/sources/functional/generic_invariants.exp
  third_party/move/move-prover/tests/sources/functional/global_invariants.exp
  third_party/move/move-prover/tests/sources/functional/global_vars.exp
  third_party/move/move-prover/tests/sources/functional/loop_invariant_invalid.exp
  third_party/move/move-prover/tests/sources/functional/loops.exp
  third_party/move/move-prover/tests/sources/functional/loops_with_memory_ops.exp
  third_party/move/move-prover/tests/sources/functional/mono.exp
  third_party/move/move-prover/tests/sources/functional/nested_invariants.exp
  third_party/move/move-prover/tests/sources/functional/nonlinear_arithm.exp
  third_party/move/move-prover/tests/sources/functional/shift.exp
  third_party/move/move-prover/tests/sources/functional/trace.exp
  third_party/move/move-prover/tests/sources/functional/verify_custom_table.exp
  third_party/move/move-prover/tests/sources/functional/verify_table.exp
Labels: compiler-v2

#11661 Update Docker images
  docker/builder/docker-bake-rust-all.hcl
Labels: CICD:run-e2e-tests

#11259 check chaos experiment status during forge tests
  Cargo.lock
  testsuite/forge/Cargo.toml
  testsuite/forge/src/backend/k8s/chaos_schema.rs
  testsuite/forge/src/backend/k8s/mod.rs
  testsuite/forge/src/backend/k8s/swarm.rs
  testsuite/forge/src/backend/local/swarm.rs
  testsuite/forge/src/interface/swarm.rs
  testsuite/testcases/src/lib.rs
  testsuite/testcases/src/modifiers.rs
  testsuite/testcases/src/multi_region_network_test.rs
  testsuite/testcases/src/network_bandwidth_test.rs
  testsuite/testcases/src/network_loss_test.rs
  testsuite/testcases/src/network_partition_test.rs
  testsuite/testcases/src/public_fullnode_performance.rs
  testsuite/testcases/src/three_region_simulation_test.rs
Labels: CICD:run-forge-e2e-perf

#9888 Update scheduler.rs inconsistent comments
  aptos-move/block-executor/src/scheduler.rs
Labels: Stale

#11651 state computer working with block metadata ext
  consensus/consensus-types/src/block.rs
  consensus/consensus-types/src/executed_block.rs
  consensus/src/block_storage/block_store.rs
  consensus/src/epoch_manager.rs
  consensus/src/execution_pipeline.rs
  consensus/src/pipeline/execution_schedule_phase.rs
  consensus/src/pipeline/ordering_state_computer.rs
  consensus/src/state_computer.rs
  consensus/src/state_computer_tests.rs
  consensus/src/state_replication.rs
  consensus/src/test_utils/mock_state_computer.rs
  types/src/block_metadata_ext.rs
  types/src/proptest_types.rs
  types/src/transaction/mod.rs
Labels: DKG

#11647 block metadata ext + related type refactoring
  api/types/src/convert.rs
  api/types/src/transaction.rs
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/move_vm_ext/session.rs
  aptos-move/aptos-vm/src/system_module_names.rs
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__module_publishing__bad_module_address.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_bad_sig_function_dep.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_code_unverifiable.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_nested_type_argument_module_does_not_exist.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_non_existing_function_dep.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_none_existing_module_dep.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__scripts__script_type_argument_module_does_not_exist.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_arbitrary_script_execution.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_module_dependency_fails_verification.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_module_transitive_dependency_fails_verification.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_open_publishing.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_open_publishing_invalid_address.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_script_dependency_fails_verification.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_script_transitive_dependency_fails_verification.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_type_tag_dependency_fails_verification.exp
  aptos-move/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__test_type_tag_transitive_dependency_fails_verification.exp
  consensus/consensus-types/src/block.rs
  consensus/consensus-types/src/executed_block.rs
  consensus/consensus-types/src/randomness.rs
  consensus/src/block_storage/block_store.rs
  consensus/src/epoch_manager.rs
  consensus/src/execution_pipeline.rs
  consensus/src/pipeline/execution_schedule_phase.rs
  consensus/src/pipeline/ordering_state_computer.rs
  consensus/src/rand/rand_gen/block_queue.rs
  consensus/src/rand/rand_gen/rand_manager.rs
  consensus/src/rand/rand_gen/rand_store.rs
  consensus/src/rand/rand_gen/reliable_broadcast_state.rs
  consensus/src/rand/rand_gen/test_utils.rs
  consensus/src/rand/rand_gen/types.rs
  consensus/src/state_computer.rs
  consensus/src/state_computer_tests.rs
  consensus/src/state_replication.rs
  consensus/src/test_utils/mock_state_computer.rs
  crates/aptos-rosetta/src/types/objects.rs
  dkg/src/dkg_manager/mod.rs
  dkg/src/dkg_manager/tests.rs
  dkg/src/dummy_dkg.rs
  dkg/src/epoch_manager.rs
  execution/executor-types/src/parsed_transaction_output.rs
  execution/executor/src/components/chunk_output.rs
  storage/backup/backup-cli/src/backup_types/transaction/analysis.rs
  testsuite/smoke-test/src/rosetta.rs
  types/src/block_metadata_ext.rs
  types/src/lib.rs
  types/src/proptest_types.rs
  types/src/randomness.rs
  types/src/transaction/mod.rs
Labels: CICD:run-e2e-tests, DKG

#11653 execute dkg txn in aptos vm
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/lib.rs
  aptos-move/aptos-vm/src/move_vm_ext/session.rs
  aptos-move/aptos-vm/src/move_vm_ext/vm.rs
  aptos-move/aptos-vm/src/system_module_names.rs
  aptos-move/aptos-vm/src/validator_txns/dkg.rs
  aptos-move/aptos-vm/src/validator_txns/dummy.rs
  aptos-move/aptos-vm/src/validator_txns/mod.rs
  aptos-move/vm-genesis/src/lib.rs
  aptos-node/src/lib.rs
  config/src/config/identity_config.rs
  consensus/src/payload_client/mixed.rs
  crates/aptos-rest-client/src/lib.rs
  dkg/src/dkg_manager/mod.rs
  dkg/src/dummy_dkg.rs
  dkg/src/epoch_manager.rs
  dkg/src/lib.rs
  dkg/src/transcript_aggregation.rs
  dkg/src/transcript_aggregation/mod.rs
  dkg/src/transcript_aggregation/tests.rs
  testsuite/generate-format/tests/staged/api.yaml
  testsuite/generate-format/tests/staged/aptos.yaml
  testsuite/generate-format/tests/staged/consensus.yaml
  testsuite/smoke-test/src/consensus/quorum_store_fault_tolerance.rs
  testsuite/smoke-test/src/lib.rs
  testsuite/smoke-test/src/utils.rs
  testsuite/smoke-test/src/validator_txns.rs
  types/src/dkg/dummy_dkg/mod.rs
  types/src/dkg/dummy_dkg/tests.rs
  types/src/dkg/mod.rs
  types/src/on_chain_config/consensus_config.rs
  types/src/proptest_types.rs
  types/src/validator_txn.rs
  types/src/validator_verifier.rs
Labels: CICD:run-e2e-tests, DKG

#11746 cherry pick DKG changes to main
  api/types/src/convert.rs
  api/types/src/transaction.rs
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/move_vm_ext/session.rs
  consensus/consensus-types/src/block.rs
  consensus/consensus-types/src/executed_block.rs
  consensus/consensus-types/src/randomness.rs
  consensus/src/block_storage/block_store.rs
  consensus/src/epoch_manager.rs
  consensus/src/execution_pipeline.rs
  consensus/src/pipeline/execution_schedule_phase.rs
  consensus/src/pipeline/ordering_state_computer.rs
  consensus/src/rand/rand_gen/block_queue.rs
  consensus/src/rand/rand_gen/rand_manager.rs
  consensus/src/rand/rand_gen/rand_store.rs
  consensus/src/rand/rand_gen/reliable_broadcast_state.rs
  consensus/src/rand/rand_gen/test_utils.rs
  consensus/src/rand/rand_gen/types.rs
  consensus/src/state_computer.rs
  consensus/src/state_computer_tests.rs
  consensus/src/state_replication.rs
  consensus/src/test_utils/mock_state_computer.rs
  crates/aptos-rosetta/src/types/objects.rs
  execution/executor-types/src/parsed_transaction_output.rs
  execution/executor/src/components/chunk_output.rs
  storage/backup/backup-cli/src/backup_types/transaction/analysis.rs
  testsuite/generate-format/src/api.rs
  testsuite/generate-format/src/aptos.rs
  testsuite/generate-format/src/consensus.rs
  testsuite/generate-format/tests/staged/api.yaml
  testsuite/generate-format/tests/staged/aptos.yaml
  testsuite/generate-format/tests/staged/consensus.yaml
  testsuite/smoke-test/src/rosetta.rs
  types/src/block_metadata_ext.rs
  types/src/lib.rs
  types/src/proptest_types.rs
  types/src/randomness.rs
  types/src/transaction/mod.rs
  types/src/validator_txn.rs
Labels: CICD:run-e2e-tests

#11612 dkg manager state transition
  aptos-move/aptos-vm/src/validator_txns/dkg.rs
  aptos-move/vm-genesis/src/lib.rs
  consensus/src/pipeline/ordering_state_computer.rs
  crates/validator-transaction-pool/src/lib.rs
  dkg/src/agg_trx_producer.rs
  dkg/src/dkg_manager/mod.rs
  dkg/src/dkg_manager/tests.rs
  dkg/src/epoch_manager.rs
  dkg/src/lib.rs
  dkg/src/network.rs
  dkg/src/transcript_aggregation/mod.rs
  dkg/src/transcript_aggregation/tests.rs
  dkg/src/types.rs
  testsuite/generate-format/tests/staged/api.yaml
  testsuite/generate-format/tests/staged/aptos.yaml
  testsuite/generate-format/tests/staged/consensus.yaml
  types/src/contract_event.rs
  types/src/dkg/mod.rs
  types/src/validator_txn.rs
Labels: CICD:run-e2e-tests, DKG

#11698 dynamic tasks for processing the fullnode parsing.
  Cargo.lock
  config/src/config/indexer_grpc_config.rs
  ecosystem/indexer-grpc/indexer-grpc-fullnode/Cargo.toml
  ecosystem/indexer-grpc/indexer-grpc-fullnode/src/fullnode_data_service.rs
  ecosystem/indexer-grpc/indexer-grpc-fullnode/src/localnet_data_service.rs
  ecosystem/indexer-grpc/indexer-grpc-fullnode/src/runtime.rs
  ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs
  ecosystem/indexer-grpc/indexer-grpc-utils/src/lib.rs
Labels: CICD:build-images

#11582 Compute correct accumulated effective block gas fees with module publishing txn(s) in the block
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/limit_processor.rs
  aptos-move/block-executor/src/txn_last_input_output.rs
  execution/executor-benchmark/src/lib.rs
  types/src/block_executor/config.rs
  types/src/on_chain_config/execution_config.rs
Labels: CICD:run-execution-performance-test

#11777 integrate real wvuf
  Cargo.lock
  aptos-node/src/lib.rs
  aptos-node/src/services.rs
  config/src/config/identity_config.rs
  consensus/Cargo.toml
  consensus/src/consensus_provider.rs
  consensus/src/epoch_manager.rs
  consensus/src/logging.rs
  consensus/src/network.rs
  consensus/src/network_interface.rs
  consensus/src/pipeline/ordering_state_computer.rs
  consensus/src/pipeline/tests/buffer_manager_tests.rs
  consensus/src/rand/rand_gen/aug_data_store.rs
  consensus/src/rand/rand_gen/mod.rs
  consensus/src/rand/rand_gen/network_messages.rs
  consensus/src/rand/rand_gen/rand_manager.rs
  consensus/src/rand/rand_gen/rand_store.rs
  consensus/src/rand/rand_gen/reliable_broadcast_state.rs
  consensus/src/rand/rand_gen/storage/db.rs
  consensus/src/rand/rand_gen/storage/in_memory.rs
  consensus/src/rand/rand_gen/storage/interface.rs
  consensus/src/rand/rand_gen/storage/schema.rs
  consensus/src/rand/rand_gen/test_utils.rs
  consensus/src/rand/rand_gen/types.rs
  consensus/src/twins/twins_node.rs
  testsuite/smoke-test/Cargo.toml
  testsuite/smoke-test/src/randomness/e2e_correctness.rs
  testsuite/smoke-test/src/randomness/mod.rs
  types/src/dkg/real_dkg/mod.rs
  types/src/randomness.rs
Labels: CICD:run-e2e-tests

#11801 [NFT Metadata Crawler] Enable better quality from configs + add IPFS gateway auth
  ecosystem/nft-metadata-crawler-parser/src/utils/constants.rs
  ecosystem/nft-metadata-crawler-parser/src/utils/image_optimizer.rs
  ecosystem/nft-metadata-crawler-parser/src/utils/uri_parser.rs
  ecosystem/nft-metadata-crawler-parser/src/worker.rs
Labels: CICD:build-images

#11786 [Cargo] Update tokio to the latest version.
  Cargo.lock
  Cargo.toml
Labels: CICD:run-e2e-tests

#11819 [Rust] Upgrade to rust 1.75.0
  .cargo/config.toml
  Cargo.toml
  api/src/context.rs
  api/src/tests/state_test.rs
  api/types/src/move_types.rs
  aptos-move/aptos-release-builder/src/utils.rs
  aptos-move/aptos-sdk-builder/src/rust.rs
  aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
  aptos-move/framework/cached-packages/src/aptos_token_objects_sdk_builder.rs
  aptos-move/framework/cached-packages/src/aptos_token_sdk_builder.rs
  aptos-move/framework/src/module_metadata.rs
  aptos-move/framework/src/release_bundle.rs
  consensus/safety-rules/src/safety_rules_manager.rs
  consensus/src/dag/anchor_election/mod.rs
  consensus/src/dag/mod.rs
  consensus/src/epoch_manager.rs
  consensus/src/quorum_store/quorum_store_builder.rs
  consensus/src/sender_aware_shuffler.rs
  consensus/src/test_utils/mod.rs
  crates/aptos-api-tester/src/tests/publish_module.rs
  crates/aptos-crypto/src/secp256r1_ecdsa/secp256r1_ecdsa_sigs.rs
  crates/aptos-openapi/src/lib.rs
  crates/aptos-rosetta/src/types/misc.rs
  crates/aptos-rosetta/src/types/objects.rs
  crates/aptos-telemetry/src/sender.rs
  crates/aptos/CHANGELOG.md
  crates/indexer/src/models/coin_models/coin_utils.rs
  crates/indexer/src/processors/token_processor.rs
  crates/transaction-generator-lib/src/workflow_delegator.rs
  docker/builder/docker-bake-rust-all.hcl
  ecosystem/indexer-grpc/indexer-grpc-fullnode/src/tests/mod.rs
  ecosystem/indexer-grpc/indexer-grpc-fullnode/src/tests/proto_converter_tests.rs
  execution/block-partitioner/src/test_utils.rs
  execution/executor-benchmark/src/lib.rs
  execution/executor-benchmark/src/transaction_generator.rs
  mempool/src/core_mempool/mod.rs
  mempool/src/counters.rs
  mempool/src/shared_mempool/mod.rs
  rust-toolchain.toml
  scripts/update_docker_images.py
  testsuite/smoke-test/src/aptos_cli/validator.rs
  testsuite/smoke-test/src/genesis.rs
  testsuite/smoke-test/src/rosetta.rs
  testsuite/smoke-test/src/test_utils.rs
  testsuite/testcases/src/lib.rs
  third_party/move/evm/move-to-yul/src/events.rs
  third_party/move/evm/move-to-yul/src/native_functions.rs
  third_party/move/evm/move-to-yul/src/tables.rs
  third_party/move/evm/move-to-yul/src/vectors.rs
  third_party/move/move-borrow-graph/src/graph.rs
  third_party/move/move-bytecode-verifier/src/reference_safety/mod.rs
  third_party/move/move-bytecode-verifier/src/signature_v2.rs
  third_party/move/move-command-line-common/src/files.rs
  third_party/move/move-compiler-v2/src/lib.rs
  third_party/move/move-compiler/src/cfgir/liveness/mod.rs
  third_party/move/move-model/src/builder/exp_builder.rs
  third_party/move/move-prover/src/lib.rs
  third_party/move/move-vm/runtime/src/loader/modules.rs
  third_party/move/move-vm/runtime/src/loader/script.rs
Labels: CICD:run-e2e-tests

#11833 [Randomness][Fix] check feature flags
  aptos-move/aptos-vm/src/validator_txns/dkg.rs
  aptos-move/aptos-vm/src/validator_txns/mod.rs
  consensus/src/block_storage/tracing.rs
  consensus/src/counters.rs
  consensus/src/dag/bootstrap.rs
  consensus/src/dag/rb_handler.rs
  consensus/src/dag/tests/rb_handler_tests.rs
  consensus/src/epoch_manager.rs
  consensus/src/liveness/proposal_generator.rs
  consensus/src/logging.rs
  consensus/src/round_manager.rs
  consensus/src/round_manager_fuzzing.rs
  consensus/src/round_manager_test.rs
  dkg/src/agg_trx_producer.rs
  dkg/src/epoch_manager.rs
  types/src/on_chain_config/aptos_features.rs
  types/src/on_chain_config/consensus_config.rs
  types/src/validator_txn.rs
Labels: CICD:run-e2e-tests

#11756 [move-compiler-v2] Implement unused parameter and unused local warnings as an AST pass
  third_party/move/move-compiler-v2/src/flow_insensitive_checkers.rs
  third_party/move/move-compiler-v2/src/inliner.rs
  third_party/move/move-compiler-v2/src/lib.rs
  third_party/move/move-compiler-v2/tests/bytecode-generator/borrow.exp
  third_party/move/move-compiler-v2/tests/bytecode-generator/globals.exp
  third_party/move/move-compiler-v2/tests/bytecode-generator/tuple.exp
  third_party/move/move-compiler-v2/tests/bytecode-generator/tuple_invalid.exp
  third_party/move/move-compiler-v2/tests/checking/access_specifiers/access_ok.exp
  third_party/move/move-compiler-v2/tests/checking/inlining/shadowing_unused_nodecl.exp
  third_party/move/move-compiler-v2/tests/checking/naming/generics_shadowing.exp
  third_party/move/move-compiler-v2/tests/checking/specs/inline_spec_inference_bitvector.exp
  third_party/move/move-compiler-v2/tests/checking/specs/inline_spec_inference_vector.exp
  third_party/move/move-compiler-v2/tests/checking/typing/assign_nested.exp
  third_party/move/move-compiler-v2/tests/checking/typing/assign_nested.move
  third_party/move/move-compiler-v2/tests/checking/typing/assign_tuple.exp
  third_party/move/move-compiler-v2/tests/checking/typing/declare_with_type_annot.exp
  third_party/move/move-compiler-v2/tests/checking/typing/eq_inline.exp
  third_party/move/move-compiler-v2/tests/checking/typing/unused_lambda_param.exp
  third_party/move/move-compiler-v2/tests/checking/typing/unused_lambda_param.move
  third_party/move/move-compiler-v2/tests/checking/typing/unused_local.exp
  third_party/move/move-compiler-v2/tests/checking/typing/unused_local.move
  third_party/move/move-compiler-v2/tests/copy-propagation/call_1.exp
  third_party/move/move-compiler-v2/tests/copy-propagation/dead_assignment_1.exp
  third_party/move/move-compiler-v2/tests/copy-propagation/immut_refs_2.exp
  third_party/move/move-compiler-v2/tests/explicit-drop/unused_var.exp
  third_party/move/move-compiler-v2/tests/file-format-generator/borrow.exp
  third_party/move/move-compiler-v2/tests/file-format-generator/const.exp
  third_party/move/move-compiler-v2/tests/file-format-generator/globals.exp
  third_party/move/move-compiler-v2/tests/testsuite.rs
  third_party/move/move-compiler-v2/tests/uninit-use-checker/use_twice_before_assign.exp
  third_party/move/move-compiler-v2/tests/uninit-use-checker/uses_before_assign.exp
  third_party/move/move-compiler-v2/tests/uninit-use-checker/v1-commands/move_before_assign.exp
  third_party/move/move-compiler-v2/tests/uninit-use-checker/v1-commands/use_before_assign.exp
  third_party/move/move-compiler-v2/transactional-tests/tests/inlining/multi_param.exp
  third_party/move/move-compiler-v2/transactional-tests/tests/no-safety/simple_map_keys.exp
  third_party/move/move-model/src/symbol.rs
Labels: compiler-v2

#11832 [Executor] Refactor errors, prepare for resource group bcs fallback
  aptos-move/aptos-aggregator/src/types.rs
  aptos-move/aptos-vm/src/block_executor/mod.rs
  aptos-move/block-executor/src/errors.rs
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/proptest_types/baseline.rs
  aptos-move/block-executor/src/proptest_types/tests.rs
  aptos-move/block-executor/src/proptest_types/types.rs
  aptos-move/block-executor/src/txn_last_input_output.rs
Labels: CICD:run-e2e-tests
