Repository aptos-labs/aptos-core, pull requests merged in 2025-06, with the labels that each got.

#16653 replay-verify: print mismatches as found.
  .github/workflows/workflow-run-replay-verify-on-archive.yaml
  storage/db-tool/src/replay_on_archive.rs
  testsuite/replay-verify/main.py
  testsuite/replay-verify/replay-verify-worker-template.yaml
Labels: CICD:build-images

#16747 [refactoring] Remove display for tags
  api/src/accounts.rs
  api/src/response.rs
  api/src/state.rs
  api/types/src/convert.rs
  aptos-move/aptos-gas-profiling/src/aggregate.rs
  aptos-move/aptos-gas-profiling/src/erased.rs
  aptos-move/aptos-gas-profiling/src/flamegraph.rs
  aptos-move/aptos-gas-profiling/src/render.rs
  aptos-move/aptos-gas-profiling/src/report.rs
  aptos-move/aptos-sdk-builder/src/common.rs
  aptos-move/aptos-sdk-builder/src/golang.rs
  aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs
  aptos-move/e2e-move-tests/src/tests/token_event_store.rs
  aptos-move/framework/src/natives/cryptography/algebra/mod.rs
  aptos-move/framework/src/natives/string_utils.rs
  aptos-move/framework/src/natives/type_info.rs
  crates/aptos-rosetta/src/common.rs
  crates/aptos-rosetta/src/types/objects.rs
  crates/aptos/src/account/balance.rs
  crates/aptos/src/account/list.rs
  crates/indexer/src/models/coin_models/coin_activities.rs
  crates/indexer/src/processors/coin_processor.rs
  execution/executor-benchmark/src/db_access.rs
  experimental/bulk-txn-submit/src/event_lookup.rs
  state-sync/inter-component/event-notifications/src/lib.rs
  state-sync/inter-component/event-notifications/src/tests.rs
  testsuite/fuzzer/fuzz/fuzz_targets/move/type_tag_to_string.rs
  testsuite/smoke-test/src/randomness/mod.rs
  testsuite/smoke-test/src/utils.rs
  third_party/move/extensions/move-table-extension/src/lib.rs
  third_party/move/move-core/types/src/effects.rs
  third_party/move/move-core/types/src/function.rs
  third_party/move/move-core/types/src/language_storage.rs
  third_party/move/move-core/types/src/parser.rs
  third_party/move/move-core/types/src/value.rs
  third_party/move/move-stdlib/src/natives/debug.rs
  third_party/move/move-stdlib/tests/type_name_tests.move
  third_party/move/move-vm/runtime/src/data_cache.rs
  third_party/move/move-vm/runtime/src/interpreter.rs
  third_party/move/move-vm/runtime/src/loader/function.rs
  third_party/move/move-vm/types/src/values/function_values_impl.rs
  third_party/move/move-vm/types/src/values/serialization_tests.rs
  third_party/move/tools/move-resource-viewer/src/lib.rs
  third_party/move/tools/move-unit-test/src/extensions.rs
  types/src/access_path.rs
  types/src/transaction/script.rs
Labels: CICD:run-e2e-tests

#16713 [API] Extend simulation filtering support.
  config/src/config/transaction_filter_type.rs
  consensus/src/transaction_filter/mod.rs
Labels: CICD:run-e2e-tests

#16126 [consensus] opt proposal
  config/src/config/consensus_config.rs
  consensus/consensus-types/src/block.rs
  consensus/consensus-types/src/block_data.rs
  consensus/consensus-types/src/lib.rs
  consensus/consensus-types/src/opt_block_data.rs
  consensus/consensus-types/src/opt_proposal_msg.rs
  consensus/consensus-types/src/proposal_ext.rs
  consensus/src/block_storage/block_store.rs
  consensus/src/block_storage/tracing.rs
  consensus/src/counters.rs
  consensus/src/epoch_manager.rs
  consensus/src/liveness/proposal_generator.rs
  consensus/src/logging.rs
  consensus/src/network.rs
  consensus/src/network_interface.rs
  consensus/src/round_manager.rs
  consensus/src/round_manager_fuzzing.rs
  consensus/src/round_manager_test.rs
  testsuite/generate-format/tests/staged/consensus.yaml
Labels: CICD:run-e2e-tests

#16804 [Priority Fee] Add new types.
  api/types/src/convert.rs
  aptos-move/aptos-debugger/src/aptos_debugger.rs
  aptos-move/aptos-e2e-comparison-testing/src/data_collection.rs
  aptos-move/aptos-transaction-benchmarks/src/transaction_bench_state.rs
  aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs
  aptos-move/aptos-vm-profiling/src/bins/run_aptos_p2p.rs
  aptos-move/aptos-vm/src/sharded_block_executor/sharded_executor_service.rs
  aptos-move/aptos-vm/tests/sharded_block_executor.rs
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/proptest_types/bencher.rs
  aptos-move/block-executor/src/proptest_types/delta_tests.rs
  aptos-move/block-executor/src/proptest_types/group_tests.rs
  aptos-move/block-executor/src/proptest_types/module_tests.rs
  aptos-move/block-executor/src/proptest_types/resource_tests.rs
  aptos-move/block-executor/src/proptest_types/tests.rs
  aptos-move/block-executor/src/txn_provider/blocking_txns_provider.rs
  aptos-move/block-executor/src/txn_provider/default.rs
  aptos-move/block-executor/src/txn_provider/mod.rs
  aptos-move/block-executor/src/unit_tests/mod.rs
  aptos-move/e2e-tests/src/executor.rs
  aptos-move/replay-benchmark/src/workload.rs
  consensus/src/execution_pipeline.rs
  consensus/src/pipeline/pipeline_builder.rs
  consensus/src/state_computer.rs
  execution/executor-benchmark/src/block_preparation.rs
  execution/executor-benchmark/src/lib.rs
  execution/executor-benchmark/src/native/aptos_vm_uncoordinated.rs
  execution/executor-benchmark/src/native/parallel_uncoordinated_block_executor.rs
  execution/executor-service/src/test_utils.rs
  execution/executor-test-helpers/src/integration_test_impl.rs
  execution/executor/src/block_executor/mod.rs
  execution/executor/src/chunk_executor/mod.rs
  execution/executor/src/chunk_executor/transaction_chunk.rs
  execution/executor/src/db_bootstrapper/mod.rs
  execution/executor/src/tests/mock_vm/mock_vm_test.rs
  execution/executor/src/tests/mock_vm/mod.rs
  execution/executor/src/tests/mod.rs
  execution/executor/src/workflow/do_get_execution_output.rs
  storage/db-tool/src/replay_on_archive.rs
  testsuite/generate-format/tests/staged/api.yaml
  testsuite/generate-format/tests/staged/aptos.yaml
  testsuite/generate-format/tests/staged/consensus.yaml
  types/src/block_executor/partitioner.rs
  types/src/transaction/block_epilogue.rs
  types/src/transaction/mod.rs
Labels: CICD:run-e2e-tests

#16850 [pipeline] default to use pipeline and cleanup all old code
  config/src/config/consensus_config.rs
  config/src/config/consensus_observer_config.rs
  consensus/consensus-types/src/lib.rs
  consensus/consensus-types/src/pipeline_execution_result.rs
  consensus/consensus-types/src/pipelined_block.rs
  consensus/src/block_storage/block_store.rs
  consensus/src/block_storage/block_tree.rs
  consensus/src/block_storage/tracing.rs
  consensus/src/consensus_observer/observer/consensus_observer.rs
  consensus/src/consensus_observer/observer/epoch_state.rs
  consensus/src/consensus_provider.rs
  consensus/src/counters.rs
  consensus/src/dag/adapter.rs
  consensus/src/dag/dag_driver.rs
  consensus/src/epoch_manager.rs
  consensus/src/execution_pipeline.rs
  consensus/src/lib.rs
  consensus/src/liveness/proposal_generator.rs
  consensus/src/liveness/proposal_generator_test.rs
  consensus/src/payload_client/mixed.rs
  consensus/src/payload_client/mod.rs
  consensus/src/payload_client/user/mod.rs
  consensus/src/payload_client/user/quorum_store_client.rs
  consensus/src/pipeline/buffer_item.rs
  consensus/src/pipeline/buffer_manager.rs
  consensus/src/pipeline/decoupled_execution_utils.rs
  consensus/src/pipeline/execution_client.rs
  consensus/src/pipeline/execution_schedule_phase.rs
  consensus/src/pipeline/persisting_phase.rs
  consensus/src/pipeline/pipeline_builder.rs
  consensus/src/pipeline/tests/buffer_manager_tests.rs
  consensus/src/pipeline/tests/execution_phase_tests.rs
  consensus/src/pipeline/tests/mod.rs
  consensus/src/rand/rand_gen/test_utils.rs
  consensus/src/round_manager.rs
  consensus/src/round_manager_test.rs
  consensus/src/state_computer.rs
  consensus/src/state_computer_tests.rs
  consensus/src/state_replication.rs
  consensus/src/test_utils/mock_execution_client.rs
  consensus/src/test_utils/mock_payload_manager.rs
  consensus/src/test_utils/mock_state_computer.rs
  consensus/src/test_utils/mod.rs
  consensus/src/twins/basic_twins_test.rs
  consensus/src/twins/twins_node.rs
  testsuite/smoke-test/src/consensus/dag/dag_fault_tolerance.rs
Labels: CICD:run-forge-e2e-perf

#16477 Fix typos: addresss -> address, iteratable -> iterable, continously -> continuously
  ecosystem/indexer-grpc/indexer-transaction-generator/src/config_template.yaml
  storage/README.md
Labels: Stale

#16912 Patch transaction_validation.move auth key check
  aptos-move/e2e-move-tests/src/tests/fee_payer.rs
  aptos-move/framework/aptos-framework/doc/transaction_validation.md
  aptos-move/framework/aptos-framework/sources/transaction_validation.move
Labels: v1.31, v1.32

#16884 [Forge] Increase CO fallback threshold for failures.
  testsuite/forge-cli/src/suites/realistic_environment.rs
Labels: CICD:run-e2e-tests

#16958 Prune transaction summaries only in ledger db
  storage/aptosdb/src/pruner/ledger_pruner/transaction_pruner.rs
  storage/aptosdb/src/transaction_store/mod.rs
  storage/aptosdb/src/utils/truncation_helper.rs
Labels: v1.31, v1.32
