Repository aptos-labs/aptos-core, pull requests merged in 2025-05, with the labels that each got.

#16295 Add transaction_summaries API endpoint
  api/goldens/aptos_api__tests__transactions_test__test_get_transaction_by_hash_with_delayed_internal_indexer.json
  api/goldens/aptos_api__tests__transactions_test__test_get_transactions_output_user_transaction_with_entry_function_payload.json
  api/goldens/aptos_api__tests__transactions_test__test_get_transactions_returns_last_page_when_start_version_is_not_specified.json
  api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_entry_function_validation.json
  api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_invalid_entry_function_address.json
  api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_invalid_entry_function_arguments.json
  api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_invalid_entry_function_module_name.json
  api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_invalid_entry_function_name.json
  api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_invalid_script_payload_bytecode.json
  api/goldens/aptos_api__tests__transactions_test__test_get_txn_execute_failed_by_missing_entry_function_arguments.json
  api/goldens/aptos_api__tests__transactions_test__test_post_bcs_format_transaction.json
  api/goldens/aptos_api__tests__transactions_test__test_simulation_failure_with_detail_error.json
  api/goldens/aptos_api__tests__transactions_test__test_simulation_failure_with_move_abort_error_rendering.json
  api/src/context.rs
  api/src/transactions.rs
  api/types/src/convert.rs
  api/types/src/lib.rs
  api/types/src/transaction.rs
  aptos-move/aptos-validator-interface/src/rest_interface.rs
  crates/aptos-rest-client/src/lib.rs
  crates/transaction-emitter-lib/src/emitter/submission_worker.rs
  crates/transaction-emitter-lib/src/emitter/transaction_executor.rs
  experimental/bulk-txn-submit/src/coordinator.rs
  sdk/src/transaction_builder.rs
  testsuite/smoke-test/src/rest_api.rs
Labels: CICD:run-e2e-tests

#16307 Transaction validation for orderless transactions
  .gitignore
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/aptos-vm/src/transaction_validation.rs
  aptos-move/framework/aptos-framework/doc/big_ordered_map.md
  aptos-move/framework/aptos-framework/doc/genesis.md
  aptos-move/framework/aptos-framework/doc/nonce_validation.md
  aptos-move/framework/aptos-framework/doc/overview.md
  aptos-move/framework/aptos-framework/doc/transaction_validation.md
  aptos-move/framework/aptos-framework/sources/datastructures/big_ordered_map.move
  aptos-move/framework/aptos-framework/sources/genesis.move
  aptos-move/framework/aptos-framework/sources/nonce_validation.move
  aptos-move/framework/aptos-framework/sources/transaction_validation.move
  aptos-move/framework/aptos-framework/sources/transaction_validation.spec.move
  aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
  aptos-move/framework/move-stdlib/doc/features.md
  aptos-move/framework/move-stdlib/sources/configs/features.move
  execution/executor/tests/internal_indexer_test.rs
  testsuite/smoke-test/src/txn_emitter.rs
  types/src/on_chain_config/aptos_features.rs
  vm-validator/src/unit_tests/vm_validator_test.rs
Labels: CICD:run-e2e-tests

#16510 [indexer] Add test txn for burnt secondary store
  ecosystem/indexer-grpc/indexer-test-transactions/Cargo.toml
  ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/generated_transactions.rs
  ecosystem/indexer-grpc/indexer-test-transactions/src/json_transactions/imported_mainnet_txns/2662373625_fa_secondary_store_burnt_with_deletion_event.json
  ecosystem/indexer-grpc/indexer-transaction-generator/imported_transactions/imported_transactions.yaml
Labels: CICD:run-e2e-tests

#16536 DB: tolerate missing cfs when open read-only
  storage/schemadb/src/lib.rs
Labels: CICD:build-images, CICD:run-e2e-tests

#16515 replay-on-archive: remove hack to ignore failure on first txn of each…
  storage/db-tool/src/replay_on_archive.rs
Labels: CICD:build-images

#16447 BlockSTMv2 PR [1/n]: scheduler_status and tests
  aptos-move/block-executor/src/lib.rs
  aptos-move/block-executor/src/scheduler_status.rs
  aptos-move/block-executor/src/scheduler_v2.rs
Labels: CICD:run-e2e-tests

#16499 Update x25519-dalek to use a version with zeroize 1.6
  Cargo.toml
Labels: CICD:run-e2e-tests

#16524 Add the URI scheme field to the evm daa abstract signature + add MessageV2
  aptos-move/framework/aptos-framework/doc/ethereum_derivable_account.md
  aptos-move/framework/aptos-framework/sources/account/common_account_abstractions/ethereum_derivable_account.move
  testsuite/smoke-test/src/account_abstraction.rs
Labels: CICD:build-images, CICD:run-e2e-tests, CICD:run-coverage, CICD:run-all-unit-tests

#16571 Enlarge HotState
  storage/aptosdb/src/state_store/hot_state.rs
  storage/aptosdb/src/state_store/persisted_state.rs
  storage/aptosdb/src/state_store/tests/speculative_state_workflow.rs
Labels: CICD:run-e2e-tests

#16603 [Consensus Observer] Fix parent pipeline futures in CO.
  consensus/src/consensus_observer/observer/consensus_observer.rs
Labels: CICD:run-e2e-tests, v1.30

#16246 [Block Executor] Capturing MetadataAndSize, no default API forwarding. View changes [1/4]
  aptos-move/aptos-vm-types/src/abstract_write_op.rs
  aptos-move/aptos-vm-types/src/resolver.rs
  aptos-move/aptos-vm-types/src/resource_group_adapter.rs
  aptos-move/aptos-vm/src/move_vm_ext/session/view_with_change_set.rs
  aptos-move/block-executor/src/captured_reads.rs
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/view.rs
  aptos-move/mvhashmap/src/types.rs
  aptos-move/mvhashmap/src/unsync_map.rs
  execution/executor-benchmark/src/native/native_vm.rs
Labels: CICD:run-e2e-tests

#16710 [forge] era as random hex
  testsuite/forge/src/backend/k8s/cluster_helper.rs
Labels: CICD:run-e2e-tests

#16720 Reapply "replay-on-archive: remove hack to ignore failure on first tx…
  storage/db-tool/src/replay_on_archive.rs
Labels: CICD:build-images
