Repository aptos-labs/aptos-core, pull requests merged in 2025-03, with the labels that each got.

#15998 consolidate per shard RocksDB properties
  crates/aptos-faucet/metrics-server/src/gather_metrics.rs
  crates/aptos-inspection-service/src/server/utils.rs
  storage/aptosdb/src/metrics.rs
  storage/aptosdb/src/rocksdb_property_reporter.rs
Labels: CICD:run-e2e-tests

#15536 [CLI] Add `--assume-yes` to all `aptos update` subcommands
  crates/aptos/src/update/aptos.rs
  crates/aptos/src/update/movefmt.rs
  crates/aptos/src/update/prover_dependencies.rs
  crates/aptos/src/update/prover_dependency_installer.rs
  crates/aptos/src/update/revela.rs
  crates/aptos/src/update/update_helper.rs
Labels: Stale

#16062 replay-verify: improve range allocation
  storage/db-tool/src/replay_on_archive.rs
  testsuite/replay-verify/main.py
Labels: CICD:build-images

#16068 replay-verify: fail the workflow if any task fails
  testsuite/replay-verify/main.py
Labels: CICD:run-e2e-tests

#15976 [2/n] Make loader V2 default
  aptos-move/aptos-release-builder/src/components/feature_flags.rs
  types/src/on_chain_config/aptos_features.rs
Labels: CICD:build-images

#16070 replay-verify: fix a log line
  testsuite/replay-verify/main.py
Labels: CICD:run-e2e-tests

#16073 replay-verify: ignore hash mismatch at the begining of a chunk
  storage/db-tool/src/replay_on_archive.rs
Labels: CICD:build-images

#15860 [backpressure] proposals can add a per-block gas limit
  aptos-move/block-executor/src/executor.rs
  aptos-move/block-executor/src/limit_processor.rs
  config/src/config/consensus_config.rs
  config/src/config/quorum_store_config.rs
  consensus/consensus-types/src/block.rs
  consensus/consensus-types/src/common.rs
  consensus/consensus-types/src/payload.rs
  consensus/consensus-types/src/pipelined_block.rs
  consensus/src/block_preparer.rs
  consensus/src/consensus_observer/network/observer_message.rs
  consensus/src/consensus_observer/observer/payload_store.rs
  consensus/src/consensus_observer/publisher/consensus_publisher.rs
  consensus/src/counters.rs
  consensus/src/dag/tests/helpers.rs
  consensus/src/epoch_manager.rs
  consensus/src/execution_pipeline.rs
  consensus/src/liveness/proposal_generator.rs
  consensus/src/liveness/proposal_generator_test.rs
  consensus/src/payload_manager/co_payload_manager.rs
  consensus/src/payload_manager/direct_mempool_payload_manager.rs
  consensus/src/payload_manager/mod.rs
  consensus/src/payload_manager/quorum_store_payload_manager.rs
  consensus/src/pipeline/pipeline_builder.rs
  consensus/src/quorum_store/proof_manager.rs
  consensus/src/quorum_store/quorum_store_builder.rs
  consensus/src/quorum_store/tests/proof_manager_test.rs
  consensus/src/round_manager_fuzzing.rs
  consensus/src/round_manager_test.rs
  consensus/src/test_utils/mock_execution_client.rs
  consensus/src/util/db_tool.rs
  testsuite/forge-cli/src/suites/dag.rs
  testsuite/forge-cli/src/suites/realistic_environment.rs
  testsuite/generate-format/tests/staged/consensus.yaml
  types/src/block_executor/config.rs
  types/src/on_chain_config/execution_config.rs
  types/src/transaction/block_epilogue.rs
Labels: CICD:run-forge-e2e-perf

#16119 [CO] fix pipeline futures
  consensus/src/consensus_observer/observer/consensus_observer.rs
  consensus/src/pipeline/buffer_manager.rs
Labels: CICD:build-images

#14076 [execution window] blocks support a window, along with block storage and sync
  consensus/consensus-types/src/block_retrieval.rs
  consensus/consensus-types/src/pipelined_block.rs
  consensus/src/block_storage/block_store.rs
  consensus/src/block_storage/block_store_test.rs
  consensus/src/block_storage/block_tree.rs
  consensus/src/block_storage/execution_pool/block_window_test.rs
  consensus/src/block_storage/execution_pool/common_test.rs
  consensus/src/block_storage/execution_pool/mod.rs
  consensus/src/block_storage/execution_pool/target_block_retrieval_test.rs
  consensus/src/block_storage/mod.rs
  consensus/src/block_storage/pending_blocks.rs
  consensus/src/block_storage/sync_manager.rs
  consensus/src/consensus_observer/network/observer_message.rs
  consensus/src/consensus_observer/observer/active_state.rs
  consensus/src/consensus_observer/observer/ordered_blocks.rs
  consensus/src/consensus_observer/observer/payload_store.rs
  consensus/src/consensus_observer/observer/pending_blocks.rs
  consensus/src/epoch_manager.rs
  consensus/src/liveness/proposal_generator_test.rs
  consensus/src/network.rs
  consensus/src/network_tests.rs
  consensus/src/persistent_liveness_storage.rs
  consensus/src/recovery_manager.rs
  consensus/src/round_manager_fuzzing.rs
  consensus/src/round_manager_test.rs
  consensus/src/test_utils/mock_storage.rs
  consensus/src/test_utils/mod.rs
  consensus/src/util/mod.rs
  testsuite/smoke-test/src/aptos_cli/validator.rs
  testsuite/smoke-test/src/consensus/quorum_store_fault_tolerance.rs
  testsuite/smoke-test/src/execution_pool.rs
  testsuite/smoke-test/src/lib.rs
  testsuite/smoke-test/src/utils.rs
  types/src/on_chain_config/consensus_config.rs
  types/src/on_chain_config/mod.rs
Labels: CICD:run-forge-e2e-perf

#16144 [CP for 1.28 of #16128] Rename to derivable account abstraction
  aptos-move/aptos-vm/src/aptos_vm.rs
  aptos-move/framework/aptos-framework/doc/account_abstraction.md
  aptos-move/framework/aptos-framework/doc/auth_data.md
  aptos-move/framework/aptos-framework/sources/account/account_abstraction.move
  aptos-move/framework/aptos-framework/sources/account/auth_data.move
  aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
  execution/executor/tests/internal_indexer_test.rs
  sdk/src/types.rs
  testsuite/generate-format/src/api.rs
  testsuite/generate-format/src/aptos.rs
  testsuite/generate-format/src/consensus.rs
  testsuite/generate-format/tests/staged/api.yaml
  testsuite/generate-format/tests/staged/aptos.yaml
  testsuite/generate-format/tests/staged/consensus.yaml
  types/src/transaction/authenticator.rs
  types/src/transaction/mod.rs
Labels: CICD:run-e2e-tests, CICD:run-framework-upgrade-test

#16217 default ledger prune window: 100m
  config/src/config/storage_config.rs
Labels: v1.28

#16235 [gha] continuous forge on main, composite action for wait images
  .github/actions/wait-images-ci/action.yaml
  .github/workflows/forge-continuous-land-blocking-test.yaml
Labels: CICD:build-images, CICD:build-failpoints-images, CICD:build-performance-images
